### ISSUE TITLE
OrderBy 报错

### ISSUE THREAD

**Issue by FreeTimeWorker** [shuxinqin/Chloe#100]
source.OrderBy("(case 0 when 0 then (case when (Id=0) then 1 else 0 end) else Id end) desc");
需要在排序的时候执行特定的新增列，达到将特定的数据排序到第一行，于是有了如上的写法，但是发现有报错
{"Invalid order text '(case 0 when 0 then (case when (Id=0) then 1 else 0 end) else Id end) desc'"}
希望可以添加相应的解析

**Comment by shuxinqin** [comment]
不支持这样的，用lambda来吧，q.OrderByDesc(a=> Case.When(a.Gender == Gender.Man).Then("Man").When(a.Gender == Gender.Woman).Then("Woman").Else(null));

**Comment by Zhang123Ashan** [comment]
谢谢，使用您的框架很久了，极少发现有问题。这个问题通过另外一种方式解决了，祝您生活愉快！------------------ 原始邮件 ------------------
发件人: "so"<notifications@github.com>
发送时间: 2019年6月9日(星期天) 凌晨0:31
收件人: "shuxinqin/Chloe"<Chloe@noreply.github.com>;
抄送: "Zhang123Ashan"<295180200@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [shuxinqin/Chloe] OrderBy 报错 (#100)



不支持这样的，用lambda来吧，q.OrderByDesc(a=> Case.When(a.Gender == Gender.Man).Then("Man").When(a.Gender == Gender.Woman).Then("Woman").Else(null));
 
&mdash;

**Comment by tangming91** [comment]
OrderBy可以扩展下动态查询么？
