### ISSUE TITLE
解析lambda表达式报错

### ISSUE THREAD

**Issue by Hansdas** [shuxinqin/Chloe#102]
![QQ截图20190618113044](https://user-images.githubusercontent.com/35918028/59651540-cf576080-91bc-11e9-9f47-590da94f653f.png)

**Comment by shuxinqin** [comment]
Q: 使用过程遇到问题/异常怎么办？
A: 请查看 ex.Message、ex.StackTrace 以及 ex.InnerException.Message、ex.InnerException.StackTrace 查找关键错误信息。当然你也可以在github上提issue或者咨询作者，不过寻求帮助时一定要把问题描述清楚，比如用法、框架版本、数据库、错误异常Message和StackTrace等重要信息，最好能一次性提供（搭配代码、截图更佳），以便对方高效理解和排查问题，节省你我时间。

**Comment by Hansdas** [comment]
这个貌似与数据库没关系,我用的实体都是{get;privite set}，正常的传入lambda(s => s.Account == "admin")作为条件，然后调用chloe，
![QQ截图20190618114501](https://user-images.githubusercontent.com/35918028/59652076-d2535080-91be-11e9-91c6-b1fa93d3b6d9.png)

**Comment by Hansdas** [comment]
你这貌似不支持privte set吧

**Comment by shuxinqin** [comment]
对，不支持private
