### ISSUE TITLE
项目问题

### ISSUE THREAD

**Issue by xcomlong** [shuxinqin/Chloe#103]
我看到页面使用了aspnetcore2.1 但是其他库都是framework2.0,有的电脑上打开项目没问题,有的电脑打开项目报不兼容,不可以提供一个aspnetcore专用的版本吗?nuget上也搜不到支持aspnetcore的版本

**Comment by shuxinqin** [comment]
这个库的代码是多版本的，支持framework4.0和net core。
nuget上的包也是多版本的。

**Comment by xcomlong** [comment]
好的,谢谢,我再试一下

**Comment by xcomlong** [comment]
好的,谢谢,我再试一下.另外那个群满人了,能在开个新群不
