### ISSUE TITLE
chloe.orm可以添加临时表吗

### ISSUE THREAD

**Issue by xhxxgzf** [shuxinqin/Chloe#106]
chloe.orm可以添加临时表吗

**Comment by shuxinqin** [comment]
啥意思？

**Comment by xhxxgzf** [comment]
就是我先添加临时表，然后再用临时表进行exists子查询，不知道chloe有没有添加临时表的功能



------------------ 原始邮件 ------------------
发件人: "so"<notifications@github.com>; 
发送时间: 2019年6月28日(星期五) 上午10:19
收件人: "shuxinqin/Chloe"<Chloe@noreply.github.com>; 
抄送: "帅`得掉猹"<794867784@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [shuxinqin/Chloe] chloe.orm可以添加临时表吗 (#106)




啥意思？

**Comment by shuxinqin** [comment]
没有哦
