### ISSUE TITLE
为什么BeginTransaction()之后，IsInTransaction为false？

### ISSUE THREAD

**Issue by yuwochangzai** [shuxinqin/Chloe#108]

**Comment by shuxinqin** [comment]
不可能的啊。除非BeginTransaction()方法报错。

**Comment by yuwochangzai** [comment]
没报错，我改用了UseTransaction()的写法，IsInTransaction也为false，请看我断点调试的截图：
![image](https://user-images.githubusercontent.com/6983001/60491154-acf43580-9cda-11e9-83fa-1681fbabf50e.png)

**Comment by shuxinqin** [comment]
好邪门啊，我这边测是没问题的，你是不是改过源码？

**Comment by yuwochangzai** [comment]
没有改过源码

**Comment by shuxinqin** [comment]
我这边测没问题的哦，- -真不懂了哦

**Comment by xcomlong** [comment]
我遇到的问题刚好跟你相反,IsInTransaction 为true,两个isnert,第一个insert数据直接更新到表里边去了,后一个insert报错,理论要回滚,结果没回滚
