### ISSUE TITLE
net core IDbContext 怎么释放资源

### ISSUE THREAD

**Issue by nodyang** [shuxinqin/Chloe#109]
services.AddScoped<Chloe.IDbContext>((serviceProvider) =>
    {
        return new Chloe.SqlServer.MsSqlContext("Your connection string");
    });
net core 是不是通过容器去处理 IDbContext 资源释放问题？ 我不用太关心资源释放的问题。

**Comment by shuxinqin** [comment]
对。

**Comment by nodyang** [comment]
3Q
