### ISSUE TITLE
mysql的lambda方式更新时where条件中等号怎么写

### ISSUE THREAD

**Issue by war3xiaofeng** [shuxinqin/Chloe#110]
如题，我写了 context.Update<user>(u => **u.id = id**, u => new user()会在 .cs代码里报错，如果写成 context.Update<user>(u => **u.id == id**, u => new user() 会在运行时提示 where 语句有错误，感谢并期待你的回答！

**Comment by shuxinqin** [comment]
不懂你在说啥- -

**Comment by war3xiaofeng** [comment]
不好意思，表达不到位。我要根据user的id来更新name，我该怎么写这个lambda表达式呢？上面粗体部分的写法（**u.id = id** 和  **u.id == id**）都报错了。

**Comment by war3xiaofeng** [comment]
![image](https://user-images.githubusercontent.com/10287619/61105799-95bd0100-a4ad-11e9-902c-0b574497c40a.png)

**Comment by war3xiaofeng** [comment]
实际上表中是有这个字段的

**Comment by shuxinqin** [comment]
确定是acount不是account？

**Comment by war3xiaofeng** [comment]
谢谢！浪费你的时间了，抱歉哈
