### ISSUE TITLE
高并发下的异常

### ISSUE THREAD

**Issue by nodyang** [shuxinqin/Chloe#111]
Connection Timeout Expired.  The timeout period elapsed during the post-login phase.  The connection could have timed out while waiting for server to complete the login process and respond;  Or it could have timed out while attempting to create multiple a

经常处理这个问题。是不是我那个地方配置出问题了

**Comment by shuxinqin** [comment]
是不是连接池连接耗完？

**Comment by nodyang** [comment]
这个我也不太清楚 我用的autofac  想找你确认下是不是连接池满了
cb.Register(x =>
                    new MsSqlContext(AutofacContainer.Container.Resolve<IOptions<ConnectionString>>().Value
                        .Mdm))
                .Keyed<IDbContext>(EnumSqlState.Mdm).InstancePerLifetimeScope()
                .OnActivated(x =>
                {
                   
                })
                .OnRelease((x) =>
                {
                    Console.WriteLine("释放资源"+x.ToString());
                    
                });
日志也打印了。释放了资源。

**Comment by shuxinqin** [comment]
根据错误消息，貌似跟框架没关系，你百度下吧。

**Comment by nodyang** [comment]
![image](https://user-images.githubusercontent.com/3090191/61675052-41c1e000-ad29-11e9-81eb-6c940ebd6407.png)
源码我也跟踪了 。也释放了。我查查吧。赶紧是数据库链接出问题了

**Comment by nodyang** [comment]
https://www.cnblogs.com/xiaxiaolu/p/10309064.html  跟我的现象差不多。但我用的2014 的 数据库。会不会是System.Data.sqlClient 版本的问题？

**Comment by shuxinqin** [comment]
你可以引入指定的System.Data.sqlClient 版本试试

**Comment by nodyang** [comment]
1 System.Data.SqlClient 4.6.1 +sqlConnect 
![image](https://user-images.githubusercontent.com/3090191/61679092-a1bf8300-ad37-11e9-8e8c-a759207478ae.png) 基本满足要求
2 System.Data.SqlClient 4.4.6 +sqlConnect  好多的问题。。
3  github 老外的建议。不要去兼容4.0
4 大佬 又没有可能把Chole net core 版本。如果不提供我们可能深度去改下。我们打算全core 话。到时候多沟通。但公司不一定同意开源。。哎

**Comment by shuxinqin** [comment]
不用改chloe的源码，在你的项目中引入指定的System.Data.SqlClient 版本就行。

**Comment by shuxinqin** [comment]
目前chloe默认依赖System.Data.SqlClient 4.4.0。你可以在你的项目中引入比4.4.0版本号高的版本。兼容的。

**Comment by nodyang** [comment]
jar:file:/C:/Program%20Files/JetBrains/JetBrains%20Rider%202019.1.1/lib/rider.jar!/resharper/ProjectModel/CsharpCoreProject.svg | Chloe.SqlServer | 4.4.0 | false | false
-- | -- | -- | -- | --

**Comment by nodyang** [comment]
![image](https://user-images.githubusercontent.com/3090191/61681125-c834ec80-ad3e-11e9-8fa3-155e22cddafc.png)
