### ISSUE TITLE
请教个问题

### ISSUE THREAD

**Issue by nodyang** [shuxinqin/Chloe#113]
![image](https://user-images.githubusercontent.com/3090191/62029354-f326b100-b214-11e9-8cf0-a32b10048cdc.png)
1 如果都用同步 没有问题
2 如果都用异步 也没有问题
3 我们禁止使用left 所有会出现 异步查询明细。同步去查主表。然后属性赋值
线上出现了异常  
System.InvalidOperationException: Timeout expired.  The timeout period elapsed prior to obtaining a connection from the pool.  This may have occurred because all pooled connections were in use and max pool size was reached.
我用本地的数据库。偶尔也会出现这样的问题 就我自己用 不会出现并发的问题 
我去源码看来。好像也没有啥问题。就异步了。求解

**Comment by shuxinqin** [comment]
多线程问题。不要并行查询。如需并行查询，new 多个DbContext吧
