### ISSUE TITLE
OrderBy和Distinct取出的数据并没有去重

### ISSUE THREAD

**Issue by swpudp** [shuxinqin/Chloe#115]
![image](https://user-images.githubusercontent.com/11451713/62618449-d4c46200-b946-11e9-9cf6-1edecc99d946.png)
取出来的数据是这样的：
![image](https://user-images.githubusercontent.com/11451713/62618503-f3c2f400-b946-11e9-98fc-445db029e68e.png)
不知道是用法不对还是bug？（数据库是MySql）

**Comment by shuxinqin** [comment]
打印出的sql是不是预期的？

**Comment by shuxinqin** [comment]
https://github.com/shuxinqin/Chloe/issues/90  之前的distinct有个bug，你看下你的版本是不是bug版本

**Comment by swpudp** [comment]
> #90 之前的distinct有个bug，你看下你的版本是不是bug版本

#90 也是我提的，不是#90 的bug。
打印的sql如下：`SELECT `T`.`C` AS `C` FROM (SELECT DISTINCT `PrintQueues`.`BatchId` AS `C`,`PrintQueues`.`QueueTime` AS `C0` FROM `PrintQueues` AS `PrintQueues` WHERE `PrintQueues`.`TaxpayerNumber` = '88552138623JS852' ORDER BY `PrintQueues`.`QueueTime` ASC) AS `T` ORDER BY `T`.`C0` ASC LIMIT 0,100`，里层的QueueTime字段值是不重复的，加Distinct起不了作用。

**Comment by shuxinqin** [comment]
看样子，按你用法生成的sql是正确的

**Comment by swpudp** [comment]
> 看样子，按你用法生成的sql是正确的

但结果不是想要的，外层的select加distinct？
