### ISSUE TITLE
关于执行Sql参数数组传递问题

### ISSUE THREAD

**Issue by a164325164325** [shuxinqin/Chloe#116]
1、希望老哥加个可以转化数组的方法
例： iint[] ids = new int[] { 1,2,3};
context.SqlQuery<User>("select * from User where in (@ids)", new DbParam("@age", ids)).ToList();
2、SQL函数 希望可以加个case when方法，毕竟三元运算符写太多了结构层次不太清楚

**Comment by shuxinqin** [comment]
sqlquery查询这个有待优化。
最新版有case when用法，看文档

**Comment by a164325164325** [comment]
ok
