### ISSUE TITLE
是否支持EF中的GroupJoin

### ISSUE THREAD

**Issue by icelee1987** [shuxinqin/Chloe#118]
类似下面的查询
var group1 = db.Set<t_company>()
                    .GroupJoin(db.Set<t_user_detail>(), com => com.company_id, usr => usr.company_id,
                        (com, usrs) => new
                        {
                            com,//公司
                            usrs//公司下面的所有用户集合
                        });

**Comment by shuxinqin** [comment]
不支持哦

**Comment by icelee1987** [comment]
> 不支持哦

有计划支持吗？大佬
