### ISSUE TITLE
多租户过滤

### ISSUE THREAD

**Issue by SkyChenSky** [shuxinqin/Chloe#119]
请教一下，再Chloe做多租户的查询过滤，只能再filter里拼接where条件吗？

如果不是每一张都需要做多租户的过滤，那怎么去判断是否需要添加这个where语句？

**Comment by fudiwei** [comment]
#124

**Comment by shuxinqin** [comment]
开发ing

**Comment by shuxinqin** [comment]
最新版本已支持过滤器 http://www.52chloe.com/Home/UpgradeNotes/3325175022200291328
