### ISSUE TITLE
关于ORA-03135: Connection lost的问题

### ISSUE THREAD

**Issue by bizhihai** [shuxinqin/Chloe#121]
如果程序隔一段时间没有访问，重新访问数据库的时候，会报“c# ORA-03135: Connection lost”错误，提示主机已经关闭了连接。大概的意思是Oracle已经关闭了连接了，可是.NET Provider还保存着给Chloe在使用。Chloe并不知道连接已经关闭了，因为它取的是.NET Provider里的连接，所以企图open这个连接……所以就报错了。
我不知道理解得对不对，请问大家遇到这样的问题，怎么解决的？

**Comment by shuxinqin** [comment]
请求结束后有没有把DbContext销毁？
