### ISSUE TITLE
建议增加 HasQueryFilter 功能

### ISSUE THREAD

**Issue by fudiwei** [shuxinqin/Chloe#124]
* 场景一

假设项目中的实体带有软删除标识字段 `IsDeleted` 时，在查询时需要手动拼接过滤条件
``` CSharp
query = query.Where(e => !e.IsDeleted);
```

* 场景二

假设项目中包含多租户功能，每个租户的数据存在同一张表中，在查询时通过 `TenantId` 过滤
``` CSharp
query = query.Where(e => e.TenantId = "my_tenant_id");
```

---

以上两个场景中，如果查询过多，需要频繁的手动拼接类似的过滤条件，代码十分冗余，且容易遗漏。

EF Core 中有一个很有用的功能：`HasQueryFilter`，全局过滤器。它可以很方便的为每个查询语句自动追加过滤条件表达式。

能否在 Chloe 中也支持类似的功能，为 *IQuery* 对象在查询时自动追加过滤条件呢？

感谢。

**Comment by fudiwei** [comment]
#119

**Comment by fudiwei** [comment]
#119

**Comment by SkyChenSky** [comment]
非常好的建议，现在我们公司的项目就是得每个语句都拼接商户ID，不仅冗余，而且还容易漏，然而这些小问题只需要在框架层面解决一次就一劳永逸了。所以希望作者采纳以上的建议

**Comment by shuxinqin** [comment]
开发ing

**Comment by shuxinqin** [comment]
最新版本已支持 http://www.52chloe.com/Home/UpgradeNotes/3325175022200291328

**Comment by fudiwei** [comment]
@shuxinqin 官网 v4.x 文档中的 `IJoiningQuery` 还未更新为 `IJoinQuery`。

**Comment by SkyChenSky** [comment]
谢谢作者的辛苦付出
