### ISSUE TITLE
dbcontext设置成static总是会出错

### ISSUE THREAD

**Issue by 154681189** [shuxinqin/Chloe#126]
An exception occurred while executing DbCommand. For details please see the inner exception. 已有打开的与此 Command 相关联的 DataReader，必须首先将它关闭。

应该如何处理呢，每次用之前都New下吗，实例化之后context会自己关闭吗

**Comment by songhejia** [comment]
http://www.52chloe.com/Wiki/Document/3325145866628497408

**Comment by 154681189** [comment]
我用的是mssql，我参加了mysql的写法用了，还是一样

**Comment by songhejia** [comment]
不要设置成static的，用之前要new出来，用完要释放Dispose

**Comment by songhejia** [comment]
继承下面这个类，在子类中调用base.DbContext.Query.....

下面这个类手写的，大概是这个意思，参考下就行
public abstract class baseSQL:IDisposable{

		IDbContext _dbContext;

		public IDbContext DbContext
        {
            get
            {
                if (this._dbContext == null)
                    this._dbContext = new MySqlContext(new MySqlConnectionFactory(connString));
                return this._dbContext;
            }
        }
        public void Dispose()
        {
            if (this._dbContext != null)
            {
                this._dbContext.Dispose();
            }
        }

 }
