### ISSUE TITLE
请问SQLite 在每次操作之后，都需要释放掉DBContext 才能进行下一次操作？

### ISSUE THREAD

**Issue by scymen** [shuxinqin/Chloe#128]
SQLite 在每次操作之后，都需要释放掉DBContext 才能进行下一次操作？

`
           using (IDbContext context = new SQLiteContext(new SqliteDbConnectionFactory(cnn, pwd)))
            {
                string sql1 = "select *  from tttt ";
                var res = context.SqlQuery<Tttt>(sql1, null).ToList();
                string sql2 = "select *  from tttt ";
                var res2 = context.SqlQuery<Tttt>(sql2, null).ToList();
            }

`
第一次查询 sql1没问题，执行第二条 sql2 时，  context.SqlQuery<Tttt>(sql2, null).ToList(); ，就会出错。
错误：
Chloe.Exceptions.ChloeException:“An exception occurred while executing DbCommand. For details please see the inner exception. file is not a database
file is not a database”
内部错误：
SQLiteException: file is not a database
file is not a database

是不是每次操作都实例化一个 dbContext?

`
   using (IDbContext context = new SQLiteContext(new SqliteDbConnectionFactory(cnn, pwd)))
            {
                string sql1 = "select *  from tttt ";
                var res = context.SqlQuery<Tttt>(sql1, null).ToList();
            }
 
   using (IDbContext context = new SQLiteContext(new SqliteDbConnectionFactory(cnn, pwd)))
            {
                string sql2 = "select *  from tttt ";
                var res2 = context.SqlQuery<Tttt>(sql2, null).ToList();
            }

`
以上写法没问题，但是这么写太啰嗦了。

**Comment by shuxinqin** [comment]
上面的写法没问题的，只是为什么出现会报这类型的异常（SQLiteException: file is not a database）倒是没遇上过。。。

**Comment by shuxinqin** [comment]
你看下是不是SqliteDbConnectionFactory，sqlite驱动等问题导致。我这边测试是没问题的。

**Comment by scymen** [comment]
应该是 sqlite 驱动的问题，用的是
nuget -> system.data.sqlite.core 
by sqlite development team
version 1.0.112
