### ISSUE TITLE
NuGet安装的Chloe.SqlServer，没有DoWithTransaction

### ISSUE THREAD

**Issue by crystalsis** [shuxinqin/Chloe#13]
我是参照ace网站里面的写法在那自己学习，那里面用DoWithTransaction来操作数据库同时记日志，我没看错的话，但是我自己用的时候DbContext里面没有DoWithTransaction这个方法，ace里面的DoWithTransaction也确实没法转到实现，这是我哪里姿势不对么？

**Comment by shuxinqin** [comment]
DoWithTransaction是个扩展方法，在另一个dll中，这个dll没上传到nuget
https://github.com/shuxinqin/Chloe/tree/master/src/DotNet/Chloe.Extension
