### ISSUE TITLE
在.net core中启用两个线程的时候报Connection must be valid and open

### ISSUE THREAD

**Issue by pengfeif** [shuxinqin/Chloe#133]
程序运行的时候开启两个线程，两个里面都有查询，可能两个查询同时进行就会报错…这个怎么解决呢？
错误信息：
Chloe.Exceptions.ChloeException
  HResult=0x80131500
  Message=An exception occurred while executing DbCommand. For details please see the inner exception.
  Source=Chloe
  StackTrace:
   at Chloe.Core.InternalAdoSession.ExecuteReader(String cmdText, DbParam[] parameters, CommandType cmdType, CommandBehavior behavior)
   at Chloe.Query.Internals.QueryEnumeratorCreator.QueryEnumerator`1.MoveNext()
   at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.TimerQueue.FireNextTimers()

内部异常 1:
InvalidOperationException: Connection must be valid and open.

**Comment by pengfeif** [comment]
我用您那个网站的源码做了下测试，也不能同时进行查询，以下是我的代码：
`    public class MyTaskService : IHostedService, IDisposable
    {
        private Timer TimerOne, TimerTwo;
        IPostService oneService;
        IRoleService twoService;
        public MyTaskService(IHostingEnvironment hostingEnvironment)
        {
            oneService = (IPostService)ClientHttpContext.ServiceProvider.GetService(typeof(IPostService));
            twoService = (IRoleService)ClientHttpContext.ServiceProvider.GetService(typeof(IRoleService));
        }

        public void Dispose()
        {
            throw new NotImplementedException();
        }

        public Task StartAsync(CancellationToken cancellationToken)
        {
            TimerOne = new Timer(TaskOne, null, TimeSpan.Zero, TimeSpan.FromSeconds(60));
            TimerTwo = new Timer(TaskTwo, null, TimeSpan.Zero, TimeSpan.FromSeconds(60));
            return Task.CompletedTask;
        }

        public Task StopAsync(CancellationToken cancellationToken)
        {
            TimerOne?.Change(Timeout.Infinite,0);
            TimerTwo?.Change(Timeout.Infinite, 0);
            return Task.CompletedTask;
        }

        public void TaskOne(object state)
        {
            oneService.GetList();
        }

        public void TaskTwo(object state)
        {
            twoService.GetList();
        }
    }
    public class ClientHttpContext
    {
        public static IServiceProvider ServiceProvider { get; set; }
    }`

---------------------------------Startup----------------------------------------
`public void ConfigureServices(IServiceCollection services)
{
           //......其他....
           ClientHttpContext.ServiceProvider = services.BuildServiceProvider();
            services.AddSingleton<IServiceProvider, ServiceProvider>();
            services.AddSingleton<IHostedService, MyTaskService>();
}`

**Comment by pengfeif** [comment]
出现这个错误的原因是因为两次查询用了同一个IDbContext，如果每个Service（IPostService,IRoleService ）创建的时候分别创建IDbContext就不会出现这个问题。但是我不确定这样会不会有其他的问题…求大佬解答。万分感谢！

**Comment by shuxinqin** [comment]
是的，IDbContext 是非线程安全的，不要在多线程下使用同一个对象。

**Comment by pengfeif** [comment]
> 是的，IDbContext 是非线程安全的，不要在多线程下使用同一个对象。

那如果要在多线程环境下使用IDbContext，您觉得下面两种改法那种比较合适，或者您有没有其他好的解决方法？

1. 修改ServiceBase里面的构造函数，直接创建IDbContext，相当于创建每个Service的时候都会创建一个IDbContext。
`        protected AppServiceBase(IDbContext dbContext, IServiceProvider services)
        {
            //原有代码
            //this.DbContext = dbContext;
            //this.Services = services;

            //修改后
            string connString = Globals.Configuration["db:ConnString"];
            string dbType = Globals.Configuration["db:DbType"];
            this.DbContext = new DefaultDbContextFactory(dbType, connString).CreateContext();
            this.Services = services;
        }`
2，在被多线程使用的Service的构造函数里面里面创建单独的IDbContext
`        public PostService(IDbContext dbContext, IServiceProvider services) : base(dbContext, services)
        {
            string connString = Globals.Configuration["db:ConnString"];
            string dbType = Globals.Configuration["db:DbType"];
            base.DbContext = new DefaultDbContextFactory(dbType, connString).CreateContext();
            base.Services = services;
        }`

**Comment by nodyang** [comment]
> > 是的，IDbContext 是非线程安全的，不要在多线程下使用同一个对象。
> 
> 那如果要在多线程环境下使用IDbContext，您觉得下面两种改法那种比较合适，或者您有没有其他好的解决方法？
> 
> 1. 修改ServiceBase里面的构造函数，直接创建IDbContext，相当于创建每个Service的时候都会创建一个IDbContext。
>    `        protected AppServiceBase(IDbContext dbContext, IServiceProvider services)
>    {
>    //原有代码
>    //this.DbContext = dbContext;
>    //this.Services = services;
>    ```
>         //修改后
>         string connString = Globals.Configuration["db:ConnString"];
>         string dbType = Globals.Configuration["db:DbType"];
>         this.DbContext = new DefaultDbContextFactory(dbType, connString).CreateContext();
>         this.Services = services;
>     }`
>    ```
> 
> 2，在被多线程使用的Service的构造函数里面里面创建单独的IDbContext
> ` public PostService(IDbContext dbContext, IServiceProvider services) : base(dbContext, services) { string connString = Globals.Configuration["db:ConnString"]; string dbType = Globals.Configuration["db:DbType"]; base.DbContext = new DefaultDbContextFactory(dbType, connString).CreateContext(); base.Services = services; }`

你好。请教下。我也遇见多线程访问的问题。请求你现在有好的解决方案不
