### ISSUE TITLE
How can I bulk insert

### ISSUE THREAD

**Issue by dorian0408** [shuxinqin/Chloe#134]
I saw a bulk insert in the context. I want to bulk insert 200,000 pieces of data. What should I do?

**Comment by shuxinqin** [comment]
Only Chloe.SqlServer support BulkInsert: MsSqlContext.BulkInsert() https://github.com/shuxinqin/Chloe/blob/master/src/Chloe.SqlServer/MsSqlContext.cs#L511

**Comment by dorian0408** [comment]
Can I add a BulkInsert to mysqlContext and send it to PL?

**Comment by dorian0408** [comment]
Can I add BulkInsert to mysqlContext?

**Comment by shuxinqin** [comment]
Of course , but you must implement BulkInsert by youself.
