### ISSUE TITLE
Chloe.MySql.MySqlContext' 형식 개체를 'Chloe.SqlServer.MsSqlContext' 형식으로 캐스팅할 수 없습니다.

### ISSUE THREAD

**Issue by dorian0408** [shuxinqin/Chloe#135]
Occurs when using the same data model class. Is there a way to fix it?

**Comment by shuxinqin** [comment]
Sorry, I do not know what you mean~

**Comment by dorian0408** [comment]
MSQL->MySQL I tried to use the same T to make migration easier.
context.SqlQuery<T>(query).ToList();  
Occurs when the <T> value is already created in msql.
