### ISSUE TITLE
How to Chloe in use ConnectionPool

### ISSUE THREAD

**Issue by dorian0408** [shuxinqin/Chloe#136]
using (MsSqlContext context = new MsSqlContext(DbHelper.GetMssqlConnectionPath))
                    {
                    }
use as
Does ConnectionPool support?

**Comment by shuxinqin** [comment]
Setting in connectionstring like: 
<connectionStrings>
    <add name="connectionstr" connectionString="Database=userDB;Data Source=localhost;User Id=root;Password=abcabc;CharSet=utf8;port=3306;Pooling=true;Max Pool Size=100;"/>
</connectionStrings>

**Comment by dorian0408** [comment]
your answer is empty

**Comment by shuxinqin** [comment]
Setting in connectionstring like:
<connectionStrings>
    <add name="connectionstr" connectionString="Database=userDB;Data Source=localhost;User Id=root;Password=abcabc;CharSet=utf8;port=3306;Pooling=true;Max Pool Size=100;"/>
</connectionStrings>

**Comment by shuxinqin** [comment]
Setting in connectionstring like:
connectionString="Database=userDB;Data Source=localhost;User Id=root;Password=abcabc;CharSet=utf8;port=3306;Pooling=true;Max Pool Size=100;
