### ISSUE TITLE
column datatype map exception

### ISSUE THREAD

**Issue by Mcgrady2009** [shuxinqin/Chloe#137]
DataBase Version mysql5.7
chloe 3.9
`db.SqlQuery<contract_model>("select IFNULL(limit_fuel_l,0) as limit_fuel_l FROM contract");`
enitty 
`public uint limit_fuel_l { get; set; }`
dbcolumn
``limit_fuel_l` int(11) unsigned NOT NULL DEFAULT '0'`
throw exception
Unable to cast object of type 'System.Int64' to type 'System.UInt32'.
Please make sure that the member of the column 'limit_fuel_l'(0,BIGINT,System.Int64) map is the correct type.

**Comment by shuxinqin** [comment]
Two way to solve the problem：
1. change the property type :public long limit_fuel_l { get; set; }
2. register uint mapping type when program start: DbConfiguration.UseMappingType(new MappingType<uint>(DbType.UInt32)) https://github.com/shuxinqin/Chloe/blob/master/src/ChloeDemo
