### ISSUE TITLE
track entity

### ISSUE THREAD

**Issue by TANZAME** [shuxinqin/Chloe#138]
![image](https://user-images.githubusercontent.com/7043207/70706393-c5985b00-1d10-11ea-88a4-20882d78f0b6.png)

这是 bug?

**Comment by shuxinqin** [comment]
值不变，不会更新

**Comment by TANZAME** [comment]
哪是新旧值一样。

**Comment by TANZAME** [comment]
你看我代码，从数据库里查出对象，改字段，保存。这哪是新旧值一样，朋友

**Comment by shuxinqin** [comment]
entity.F_String = entity.F_String + "1";
context.Update(entity)
试试

**Comment by TANZAME** [comment]
很明显是源码写得有问题。
TrackEntity 把一个对象加进去，
比较新旧值的还是这个对象，明显这个对象都是指向同一个内存地址，怎么可能比较得出新旧值来

**Comment by shuxinqin** [comment]
entity.F_String = "123";
context.TrackEntity(entity);
entity.F_String = 123.ToString();
这样update也不会生成sql语句的。因为前后字符串内容不变。
你给的例子中我只看到track之后的值是 121313，那么 track之前 entity.F_String 的值是多少？121313还是别的值？如果是121313的话，那运行结果是预期的。如果不是那么就是bug。

**Comment by TANZAME** [comment]
你不觉得是bug就算了。再说这段测试代码你也完全可以亲手写来验证的，几秒钟的事，是不？

**Comment by TANZAME** [comment]
噢，是我看错了![image](https://user-images.githubusercontent.com/7043207/71061332-b9921a80-21a2-11ea-9e3d-0fcc8812f053.png)
