### ISSUE TITLE
Oracle 执行 Insert<TEntity>(TEntity entity)或Update异常

### ISSUE THREAD

**Issue by anthony6li** [shuxinqin/Chloe#139]
Oracle数据库执行Insert或Update，若直接传递实体对象会出现异常，而使用lambda 的方式可以执行。我有很多空的字段，number(1)对应实体类bool型，有没有什么解决方法呀？

**Comment by shuxinqin** [comment]
请查看 ex.Message、ex.StackTrace 以及 ex.InnerException.Message、ex.InnerException.StackTrace 查找关键错误信息
用法、框架版本、数据库、错误异常Message和StackTrace等重要信息，最好能一次性提供（搭配代码、截图更佳），以便对方高效理解和排查问题

**Comment by shuxinqin** [comment]
http://www.52chloe.com/Wiki/Document 文档

**Comment by anthony6li** [comment]
1. **Oracle数据库截图**：
![image](https://user-images.githubusercontent.com/18346308/71147693-80ba7a00-2264-11ea-8274-e7796dd76a0f.png)

2. **Entity实体**：

![image](https://user-images.githubusercontent.com/18346308/71147704-90d25980-2264-11ea-9309-5f30f7aeee7b.png)

3. **生成上下文**：

![image](https://user-images.githubusercontent.com/18346308/71149690-5a97d880-226a-11ea-88b4-6ec4ed02c156.png)


4.**调用**： 

![image](https://user-images.githubusercontent.com/18346308/71147900-27067f80-2265-11ea-90c5-c6d35ecd9237.png)

5. **会出现异常**：

![image](https://user-images.githubusercontent.com/18346308/71149742-80bd7880-226a-11ea-87b0-6ec2523de47e.png)
![image](https://user-images.githubusercontent.com/18346308/71149763-8dda6780-226a-11ea-93e6-d7a38ac045c0.png)


新哥，您的Wiki我看了很久。虽然Update还可以使用TrackEntity()，但是MVC后台Action函数直接接收的是实体类，已经来不及Track了。
看样子是Oracle数据库，映射数据库的number(1)类型有问题,我试着把代码中所有的bool值都改成int型了，还是无法Update或Insert。
多谢新哥帮我看看这个问题啦~~~

**Comment by anthony6li** [comment]
![image](https://user-images.githubusercontent.com/18346308/71149822-b82c2500-226a-11ea-8b13-1a3245200c04.png)

**Comment by shuxinqin** [comment]
改用number(9)试试，我这用number(9)是没问题的

**Comment by anthony6li** [comment]
刚刚试了，我这儿bool映射还是有问题。很是苦恼，我再研究研究大神的源码。
![image](https://user-images.githubusercontent.com/18346308/71223055-a0f24380-230d-11ea-81ec-c430fea82ebc.png)
![image](https://user-images.githubusercontent.com/18346308/71223070-b0718c80-230d-11ea-8965-70652fe87bb4.png)

**Comment by shuxinqin** [comment]
类型映射 http://www.52chloe.com/Wiki/Document/1249878806332837888
ps：建议使用最新版，更新了不少内容
