### ISSUE TITLE
SUM() 当记录为空时会抛出异常

### ISSUE THREAD

**Issue by fudiwei** [shuxinqin/Chloe#14]
假设存在如下实体：
`class Demo 
{ 
    public int Id {get; set;} 
    public int Amount {get; set;} 
}`

那么执行：
`int ct = dbContext.Query<Demo>().Sum(d => d.Amount);`
如果 Demo 表中不存在记录，或是加上 Where 条件后记录为空，那么会抛出类型转换异常。（同理的还有 AVG()）

而如果将 Amount 字段声明为 int? 类型就不会抛异常。但首先这个字段在数据库中本身就是 NOT NULL 的，在代码中也应该强约束为 int 而非 int?。

建议在 SqlGenerator_Helper.cs 下的 AppendAggregateFunction() 方法里做如下修改：

> /*原始代码省略*/
if (withCast)
{
    generator._sqlBuilder.Append("COALESCE("); // 此处添加
    /*原始代码省略*/
}
/*原始代码省略*/
if (withCast)
{
    generator._sqlBuilder.Append(", 0)"); // 此处添加
}

这样当 SUM() 结果为 NULL 时会自动转换成 0。

**Comment by fudiwei** [comment]
感谢回复。

这种写法确实是不需要修改 Demo 实体类中 Amout 字段的类型，但却需要修改 `int ct` 为 `int? ct`，从代码强约束的角度考虑还是存在一些问题的。

**Comment by shuxinqin** [comment]
1.SUM函数：如果Query().Sum返回的不是可空类型，加COALESCE（exp，0）处理，如果返回的是可空类型则不做COALESCE（exp，0）处理
2.AVG函数：如果sql查询的记录为空，返回0有点不合道理，因此针对AVG函数打算不做任何处理了，就让它报错。
你觉得这样修改如何？

**Comment by fudiwei** [comment]
That will be great! ^_^

**Comment by fudiwei** [comment]
Good.
