### ISSUE TITLE
Mysql 拦截器获取不到参数值

### ISSUE THREAD

**Issue by FlyLolo** [shuxinqin/Chloe#142]
您好，Mysql 拦截器获取到的command.CommandText类似这样INSERT INTO `User`(`UserCode`,`Name`,`Phone`,`WXId`,`UnionID`,`Password`,`Email`,`State`,`CreateTime`,`CreateUser`) VALUES(?P_0,?P_1,?P_2,?P_2,?P_2,?P_3,?P_2,?P_4,?P_5,?P_4);SELECT @@IDENTITY。
环境为asp.net core 3.1 拦截器用的 http://www.52chloe.com/Wiki/Document/3337853076894646272的代码

**Comment by shuxinqin** [comment]
从 NonQueryExecuting(IDbCommand command 参数里获取

**Comment by FlyLolo** [comment]
您好   调用的await _dbContext.InsertAsync<T>(model);   触发的是ScalarExecuting

**Comment by shuxinqin** [comment]
- - 那就冲 ScalarExecuting(IDbCommand command 参数里获取啊- -

**Comment by FlyLolo** [comment]
但是冲 ScalarExecuting(IDbCommand command 参数里获取到的参数值是这样的：(?P_0,?P_1,?P_2,?P_2,?P_2,?P_3,?P_2,?P_4,?P_5,?P_4);  如何能获取到真正的值
