### ISSUE TITLE
关于NotMappedAttribute

### ISSUE THREAD

**Issue by FlyLolo** [shuxinqin/Chloe#143]
是否可以支持System.ComponentModel.DataAnnotations.Schema;命名空间下的NotMappedAttribute，因为实体可能放在其他项目中，但为了加这个，项目中也需要引用Chloe。

**Comment by shuxinqin** [comment]
这个建议用 Fluent mapping吧。可以让映射和实体分开。

**Comment by shuxinqin** [comment]
之所以不用 System.ComponentModel.DataAnnotations 的特性是因为System.ComponentModel.DataAnnotations下的特性满足不了我们定制化需求，所以必须标新立异。
