### ISSUE TITLE
PublicHelper 32行

### ISSUE THREAD

**Issue by nodyang** [shuxinqin/Chloe#144]
![image](https://user-images.githubusercontent.com/3090191/73166168-492ad180-4130-11ea-9bdc-b9afc1b3b31f.png)
是不是改成这个
![image](https://user-images.githubusercontent.com/3090191/73166713-58f6e580-4131-11ea-9114-b7c0af2322f3.png)
在家无聊看看代码。

**Comment by nodyang** [comment]
: base("曾经有一个真挚的 bug 摆在我面前，但我没有修复，等到你看到了这条消息我才后悔莫及，尘世间最痛苦的事莫过于此。如果上天可以给我再来一次的机会，我依然不会对这个 bug 进行修复，因为你是永远看不到这条消息的，洗洗睡吧。")

**Comment by shuxinqin** [comment]
都差不多，不影响结果，问题不大哈哈

**Comment by nodyang** [comment]
哈哈。被困在家里。无聊拜读下大神的代码。晚安
