### ISSUE TITLE
MySQL中使用longblob

### ISSUE THREAD

**Issue by haozekang** [shuxinqin/Chloe#145]
MySQL中使用longblob的字段，domain类中如何定义

**Comment by haozekang** [comment]
是用"byte[]"吗？

**Comment by shuxinqin** [comment]
嗯，试试呗

**Comment by shuxinqin** [comment]
防止数据丢失，最好做个长度判断，不同长度设置不同的mysql blob类型，参考oracle这个配置 https://github.com/shuxinqin/Chloe/blob/master/src/ChloeDemo/String_MappingType.cs#L46
