### ISSUE TITLE
执行sql语句时能否抛出原始异常，不用去封装一次？

### ISSUE THREAD

**Issue by swpudp** [shuxinqin/Chloe#146]
如图，执行sql语句时，抛出异常时做了封装，当需要准确捕捉异常类型需要做类型转换等，没有必要，直接抛出原始异常是否更恰当？

![image](https://user-images.githubusercontent.com/11451713/74298905-0ac72080-4d86-11ea-85a6-f4b2dcfce63b.png)

![image](https://user-images.githubusercontent.com/11451713/74298742-8f656f00-4d85-11ea-8fca-3b924863b190.png)

![image](https://user-images.githubusercontent.com/11451713/74299086-98a30b80-4d86-11ea-9795-dbdfb21682b0.png)

**Comment by shuxinqin** [comment]
这个问题不大，就包装一遍吧，可控~

**Comment by shuxinqin** [comment]
之所以包装一遍是因为方便调用者统一catch属于Chloe框架内产生的异常，如果直接抛出原异常（MySqlException\OracleException ...）就不好catch了
