### ISSUE TITLE
严重Bug:context.SqlQuery<User>("select * from Users where Id=:Id", new { Id = 1 }).ToList();

### ISSUE THREAD

**Issue by Libra321** [shuxinqin/Chloe#153]
context.SqlQuery<User>("select * from Users where Id=:Id", new { Id = 1 }).ToList();
将示例中的Id =1变更为Id=0将报错未将对象引用至对象的实例，并且不支持where Id>=:Id，语句会有很多局限性

**Comment by shuxinqin** [comment]
输出ex.Mesage 和 ex.StackTrace 看看详情

**Comment by Libra321** [comment]
ex.Mesage =未将对象引用设置到对象的实例。
ex.StackTrace={sbyte[24]}
ex. _source= "Anonymously Hosted DynamicMethods Assembly"=

**Comment by shuxinqin** [comment]
ex.StackTrace = null 很难见。这是原异常么？不要对原异常进行包装，把原异常打印出来
还有框架版本等信息贴下

**Comment by Libra321** [comment]
这是原异常的，可能大家使用原生SQL的需求比较少，建议楼主测试下
context.SqlQuery("select * from Users where Id=:Id", new { Id =0 }).ToList();非常诡异的0错误
SqlQuery支持的sql语句我这边测试>=以及!=都不支持

**Comment by shuxinqin** [comment]
经测试 net45 下 使用 https://github.com/shuxinqin/Chloe/blob/master/src/lib/Oracle.ManagedDataAccess.dll
没发现你说的问题。ps：是否修改 DbCommand 参数绑定方式？http://www.52chloe.com/Wiki/Document/3325149282020884480
如果还不行，可以用原生的DbConnection试试，看下是不是你引入的驱动问题。

**Comment by Libra321** [comment]
我这边绑定方式跟你的原文一致 cmd.BindByName = true; 我说下我真实的环境，我这边真实的语句是这样的，SqlQuery<DepartTreeViewModel>("select * from STAFF_V1.UOPR2_DEPARTMENTS where partID>:partID", new { partID = 0 })，只要参数partID<=0就会报上面所述的错误，但是参数 partID取大于0的任何人一个数都没有问题都能正确的返回数据，
PS：我想问题的关键不在于这个以及驱动的问题，因为我其他新增删除修改都没有问题，只要写SQL才遇到这个问题，我这边是Oracle数据库

**Comment by shuxinqin** [comment]
我测试就是oracle数据库，net45环境，按你描述的使用方式，真没发现你说的情况- -
sqlquery内部不会对传入的sql做什么改造啥的特殊处理，你说的这种情况我也想不到哪里问题了。。。

**Comment by shuxinqin** [comment]
不然你写个简单的demo发我？
