### ISSUE TITLE
如何做一个操作记录的功能？

### ISSUE THREAD

**Issue by 2821840032** [shuxinqin/Chloe#154]
需要对新增、修改、修改操作做记录。

最终结果如：
  2020/04/03 20:00:00 新增地址为中国广东，新增昵称为赵信
  2020/04/03 20:00:00 修改地址为广东深圳
  2020/04/03 20:00:00 修改昵称为盖伦

我能想到最好的方法就是新增一个DB操作类，在里面调用chloe.orm的操作函数，并新增操作记录
但是我应该怎么做得到操作的属性值呢？

**Comment by 2821840032** [comment]
![image](https://user-images.githubusercontent.com/29800454/78363079-bdc93300-75ed-11ea-89dd-e61136095bc8.png)

我看到了源代码，能不能在过滤器NonQueryExecuted函数加上操作Columns？

**Comment by shuxinqin** [comment]
object val = ... 这个变量就是属性值

**Comment by 2821840032** [comment]
并不是很懂，能在详细点吗？

**Comment by shuxinqin** [comment]
参考 object val = propertyDescriptor.GetValue(entity);

**Comment by 2821840032** [comment]
好的 谢谢，稍后我会回来的

**Comment by 2821840032** [comment]
看了下insert 和update 代码，似乎没有可扩展的入口，那我只能是在操作外层再封装一层自行解析Expression<Func<T, T>> content 的操作了
![image](https://user-images.githubusercontent.com/29800454/78469514-7e692680-7754-11ea-80d7-cb9ef3fe1c19.png)
