### ISSUE TITLE
有计划支持异步操作吗？

### ISSUE THREAD

**Issue by panda-big** [shuxinqin/Chloe#155]
有计划支持异步操作吗？

**Comment by shuxinqin** [comment]
开发ing...

**Comment by panda-big** [comment]
大概什么时候OK？

**Comment by shuxinqin** [comment]
择日发布

**Comment by panda-big** [comment]
OK 等你 我最近有个新项目 准备使用这个ORM

**Comment by shuxinqin** [comment]
已经开发完了，待测试几天，预计周末发布
https://github.com/shuxinqin/Chloe/tree/shuxin_dev

**Comment by shuxinqin** [comment]
最新版本已经支持异步
https://github.com/shuxinqin/Chloe

**Comment by panda-big** [comment]
好的，我看看

**Comment by panda-big** [comment]
是用 master_V4.1的分支还是shuxin_dev分支还是master主版本？

**Comment by shuxinqin** [comment]
master
用nuget包就好了啊？

**Comment by panda-big** [comment]
哦 我想用源码自己编译，在有需要的情况添加功能

**Comment by panda-big** [comment]
我 3月29号 fork的master 怎么提取不到你这边最近的master版本

**Comment by shuxinqin** [comment]
我也不大懂fork机制哦，不过最新版的代码和3-29的代码改动还是挺大的

**Comment by panda-big** [comment]
我 合并就好了，我直接合并你的代码 应该就是最新的了，目前 我是分支，合并你的master 就可以了

**Comment by panda-big** [comment]
我还想咨询下你，这个orm 和 sqlsugar 有没有本质上一些区别？

**Comment by shuxinqin** [comment]
这个得自行对比咯

**Comment by panda-big** [comment]
对比过哦，你的功能少点，然后代码结构好点，因为功能少撒。理解起来更容易些，其他的都差不多

**Comment by panda-big** [comment]
是否 可以考虑 多用core DI的方式进行注入，例如连接字符串这种？隐藏New

**Comment by shuxinqin** [comment]
参考 https://github.com/shuxinqin/AceBlog/blob/master/src/AceBlog.Repository/ServiceCollectionExtensions.cs

**Comment by panda-big** [comment]
我看了你推荐的这个，这个能不能一个应用里面用多个数据库，因为我每个业务模块对应的数据都不一样，就像ef core一样，一个DbContext 对应一个数据库？

**Comment by panda-big** [comment]
例如：//add ef core
            services.AddDbContext<BusinessDbContext>(options =>
            {
                options.UseMySql(Configuration.GetConnectionString("DefaultConnection"));
            })
            .AddDbContext<SysManageDbContext>(options =>
            {
                options.UseMySql(Configuration.GetConnectionString("DefaultConnection"));
            });

**Comment by panda-big** [comment]
services.AddDbContext<BusinessDbContext>(options =>
            {
                options.UseMySql(Configuration.GetConnectionString("DefaultConnection"));
            })
            .AddDbContext<SysManageDbContext>(options =>
            {
                options.UseMySql(Configuration.GetConnectionString("DefaultConnection"));
            });

**Comment by panda-big** [comment]
```
services.AddDbContext<BusinessDbContext>(options =>
            {
                options.UseMySql(Configuration.GetConnectionString("DefaultConnection"));
            })
            .AddDbContext<SysManageDbContext>(options =>
            {
                options.UseMySql(Configuration.GetConnectionString("DefaultConnection"));
            });
```

**Comment by shuxinqin** [comment]
https://www.cnblogs.com/yilezhu/p/10236163.html#4157891
参考这个评论

**Comment by panda-big** [comment]
差不多，自已已搞定！
