### ISSUE TITLE
insert 操作不会触发触发器的NonQuery函数

### ISSUE THREAD

**Issue by 2821840032** [shuxinqin/Chloe#156]
insert 操作不会触发触发器的NonQuery函数
update和delete操作正常

DC.Insert(new ProductEntity())

版本v4.1.0
Chloe.MySql 4.1.0
Chloe 4.1.0

**Comment by shuxinqin** [comment]
是的，如果实体存在自增id，则不会触发NonQueryExecuting，只会触发 ScalarExecuting.
