### ISSUE TITLE
Async

### ISSUE THREAD

**Issue by MeisterLone** [shuxinqin/Chloe#157]
Hi

Will there be a future version that uses QueryAsync instead of Query? I would like to use Chloe on top of an existing project but I cant synchronize database queries everywhere. If Chloe made use of QueryAsync then I can just feed it an IDbConnection and use it alongside the existing code.

You have done excellent work so far, thank you.

**Comment by shuxinqin** [comment]
Async interface has been developed. It will be released in the next few days.
https://github.com/shuxinqin/Chloe/tree/shuxin_dev

**Comment by shuxinqin** [comment]
Async operation has been supported in last version.
https://github.com/shuxinqin/Chloe

**Comment by MeisterLone** [comment]
Thanks shuxinqin, are you not yet supporting async for Query() ?

https://i.imgur.com/0TfMe3m.png

**Comment by shuxinqin** [comment]
This method does not need to be designed asynchronously. You can query data asynchronously by methods like IQuery.Where().ToListAsync().

**Comment by MeisterLone** [comment]
> This method does not need to be designed asynchronously. You can query data asynchronously by methods like IQuery.Where().ToListAsync().

Perfect, I didnt see ToListAsync()!
