### ISSUE TITLE
是否考虑加入自定义函数功能？

### ISSUE THREAD

**Issue by zmrhi** [shuxinqin/Chloe#16]
比如拼音字母查询：Where(x=>x.Content.ToPY().Contians("OK"))

**Comment by shuxinqin** [comment]
这个暂没考虑过。
框架解析lambda表达式树时会把方法转成与数据库相对应的函数或语法，如 "abcd".Contains("bc") 会转成 like 语法。如果数据库有 ToPY() 对应的函数，自行修改一下源码重新生成dll倒是可以的。
