### ISSUE TITLE
发现一个统计的BUG

### ISSUE THREAD

**Issue by ThisIsSteinsGate** [shuxinqin/Chloe#161]
iQuantity类型在数据库中是DECIMAL（30，10） Null类型
在执行这段代码的时候
var rd11QuantityQuary = u8Context.Query<rdrecord11>()
                        .Where(o =>
                        o.dDate >= taskTime.Date &&
                        o.dDate < FormTime.Date.AddDays(1) &&
                        vendorHelperTask.GetVenGoodWarehouse(maxWorkshop.VenCode).Contains(o.cWhCode) &&
                        !notNeedcRdCode.Contains(o.cRdCode))
                        .LeftJoin<rdrecords11>((rd11, rds11) => rd11.ID == rds11.ID)
                        .Select((rd11, rds11) => new
                        {
                            rds11.cInvCode,
                            sumIQuantity = Sql.Sum(rds11.iQuantity)
                        }).GroupBy(o => o.cInvCode)
                        .Select(o => new SimpleWSInv()
                        {
                            VenCode = maxWorkshop.VenCode,
                            InvCode = o.cInvCode,
                            Quantity = o.sumIQuantity ?? 0M
                        });
翻译的sql会导致统计的数据精度丢失，造成严重后果
这个是ORM翻译的SQL的执行结果
SELECT '080046' AS [VenCode],
       [rdrecords11].[cInvCode] AS [InvCode],
       ISNULL(CAST(SUM([rdrecords11].[iQuantity]) AS DECIMAL(19, 0)), 0) AS [Quantity]
FROM [rdrecord11] AS [rdrecord11]
    LEFT JOIN [rdrecords11] AS [rdrecords11]
        ON [rdrecord11].[ID] = [rdrecords11].[ID]
WHERE (
          [rdrecord11].[dDate] >= CAST('2020-03-25 18:00:00' AS DATE)
          AND [rdrecord11].[dDate] < DATEADD(DAY, 1, CAST('2020-04-20 23:59:59' AS DATE))
          AND [rdrecord11].[cWhCode] IN ( '090042', '090043', '090044', '090045', '090046', '090047' )
          AND NOT ([rdrecord11].[cRdCode] IN ( '216', '219', '222' ))
          AND rdrecords11.cInvCode = 'MA0107'
      )
GROUP BY [rdrecords11].[cInvCode];

VenCode	InvCode	Quantity
080046	MA0107	1
这个是正常的结果
SELECT '080046' AS [VenCode],
       [rdrecords11].[cInvCode] AS [InvCode],
       SUM(ISNULL([rdrecords11].[iQuantity], 0)) AS [Quantity]
FROM [rdrecord11] AS [rdrecord11]
    LEFT JOIN [rdrecords11] AS [rdrecords11]
        ON [rdrecord11].[ID] = [rdrecords11].[ID]
WHERE (
          [rdrecord11].[dDate] >= CAST('2020-03-25 18:00:00' AS DATE)
          AND [rdrecord11].[dDate] < DATEADD(DAY, 1, CAST('2020-04-20 23:59:59' AS DATE))
          AND [rdrecord11].[cWhCode] IN ( '090042', '090043', '090044', '090045', '090046', '090047' )
          AND NOT ([rdrecord11].[cRdCode] IN ( '216', '219', '222' ))
          AND rdrecords11.cInvCode = 'MA0107'
      )
GROUP BY [rdrecords11].[cInvCode];

VenCode	InvCode	Quantity
080046	MA0107	0.7365000000
问题主要是这一句sql导致精度丢失
DECIMAL(19, 0))
ISNULL(CAST(SUM([rdrecords11].[iQuantity]) AS DECIMAL(19, 0)), 0) AS [Quantity]

**Comment by ThisIsSteinsGate** [comment]
对了，都是4.5的版本

**Comment by shuxinqin** [comment]
实体属性iQuantity是什么类型？

**Comment by shuxinqin** [comment]
Chloe.SqlServer v4.5.1 已解决

**Comment by nodyang** [comment]
> Chloe.SqlServer v4.5.1 已解决 提示更新。但是下载不了
