### ISSUE TITLE
Delete range

### ISSUE THREAD

**Issue by MeisterLone** [shuxinqin/Chloe#163]
Hi

Is there a possibility for a delete list of objects in single command/query?

**Comment by shuxinqin** [comment]
List<int> ids = new List<int>();
dbContext.Delete<User>(a=> ids.Contains(a.Id));

**Comment by shuxinqin** [comment]
new version:
dbContext.Delete<Person>(a => !dbContext.Query<City>().IgnoreAllFilters().Select(a => a.Id).ToList().Contains(a.CityId));
/*
 * DELETE FROM [Person] WHERE NOT ([Person].[CityId] IN (SELECT [City].[Id] AS [C] FROM [City] AS [City]))
 */
