### ISSUE TITLE
关于释放的问题

### ISSUE THREAD

**Issue by 756616071** [shuxinqin/Chloe#166]
您好!关于线程安全问题用这种方式可以释放吗
![image](https://user-images.githubusercontent.com/44856671/82227008-cdac9480-9959-11ea-8d35-a9f2b7e11e13.png)

**Comment by shuxinqin** [comment]
1. db => 语法每次调用都会创建一个新的对象，多次调用会导致之前的对象得不到释放
2. 不要手动调用GC.Collect()

**Comment by 756616071** [comment]
那应该怎么调用才能把它全部释放掉呢

**Comment by Libra321** [comment]
同问，那应该怎么调用才能把它全部释放掉呢
