### ISSUE TITLE
long做主键无法映射 mysql bigint 

### ISSUE THREAD

**Issue by xjhmi** [shuxinqin/Chloe#167]
使用实体插入时，使用了long做主键，无法插入

**Comment by shuxinqin** [comment]
参考文档 http://www.52chloe.com/Wiki/Document

**Comment by xjhmi** [comment]
我不知道是我写法问题还是怎么的，我的主键ID再mysql 数据库的类型是非空 bigint ,实体中是long ,使用的是雪花id生成的19位Id，执行insert 出现 FIELD  'Id'  dont has default value 的错误，我把实体中id从long替换成string类型，执行是可以插入的。

**Comment by xjhmi** [comment]
没有作主键的字段同样的映射关系，和ID生成方法，是可以插入的，就是作为主键之后不行

**Comment by xjhmi** [comment]
我再文档找到了解决办法了，没有仔细阅读文档，感谢！
