### ISSUE TITLE
小小建议

### ISSUE THREAD

**Issue by zmrhi** [shuxinqin/Chloe#17]
如果能把多数据库支持集中到单个dll，使用更轻巧方便。可以参考FluentData

**Comment by shuxinqin** [comment]
这个问题不大，各有优劣吧。

**Comment by lymegg** [comment]
同意，这样在部署系统时，可以根据环境或使用规模，部署不同的数据库，而不需要更改代码，这样大部分的数据库操作写一遍就好了，极其特殊的可以通过接口扩展实现，我有好几个公司的小应用都是这样处理，小范围用则部署sqlite本地库，规模大的项目则上mssql或mysql，不知道这样需求普不普遍
