### ISSUE TITLE
lambda 查询, 生成的SQL关键字前默认加"N", 导致在 Oracle(表中3千万记录)查询时索引失效, 需1分钟返回

### ISSUE THREAD

**Issue by me1017** [shuxinqin/Chloe#170]
查询时用lambda生成的sql关键字前默认加"N", 在 ORACEL 3千万记录的表中查询时很慢, 手动测试SQL, 去除"N"后恢复正常. 是否可以通过配置设置此项?

Chloe.Oracle 4.6.0
Oracle Database 11g Release 11.2.0.1.0 - 64bit Production
SQL SERVER 2012 中测试, 无此问题

**Comment by shuxinqin** [comment]
Q: 查询如 q.Where(a=> a.Name == “Chloe”) 为什么生成的不是参数化 sql ？
A: 因为框架内部解析 lambda 时对于常量（ConstantExpression）不做参数化处理（刻意的，不要问为什么），如需参数化，请使用变量，如：

var name = "Chloe";
q = q.Where(a=> a.Name == name);
...
Tip: 自行拼接 lambda 表达式树的注意了，千万不要用 ConstantExpression 包装你的变量，否则会生成非参数化sql哦！！！包装变量方式参考这个 MakeWrapperAccess 方法：https://github.com/shuxinqin/Chloe/blob/master/src/Chloe/Extensions/ExpressionExtension.cs#L117

**Comment by shuxinqin** [comment]
如果字段是varchar类型的话，最好也把对应的属性的DbType设置为DbType.AnsiString

**Comment by me1017** [comment]
好的, 明白了! 感谢急速回复~
Chloe 是我用过众多 ORM 中感觉最顺手的, 加油!
