### ISSUE TITLE
update( List ) 报错

### ISSUE THREAD

**Issue by scymen** [shuxinqin/Chloe#172]
可能是BUG

实体
`public class Sys_Menu
    {
        [NonAutoIncrementAttribute]
        [Column(IsPrimaryKey = true)]
        public long Menu_Id { get; set; }

        public string Menu_Name { get; set; }
  }`

var list = new List<Sys_Menu>(); 
list.Add(XXX);

dbContext.Update(list); 时会一直报错 末指定主键列，实际上已经标注了。
但是，如果使用循环逐个 update 则操作成功。

以上 update 都放在事务里。

**Comment by shuxinqin** [comment]
dbContext.Update 不支持传list

**Comment by scymen** [comment]
明白，谢谢。
