### ISSUE TITLE
insert成功后，自增主键ID并没有赋值到实体类上，请问如何处理

### ISSUE THREAD

**Issue by zxingdream** [shuxinqin/Chloe#173]
User user = new User();
user.Name = "lu";
user.Age = 18;
user.Gender = Gender.Man;
user.CityId = 1;
user.OpTime = DateTime.Now;

/* 会自动将自增 Id 设置到 user 的 Id 属性上 */
user = dbContext.Insert(user);

程序跟踪了下， user.Id依然是0，请问下是怎么个情况，

**Comment by shuxinqin** [comment]
参考 github 上的最新demo。
