### ISSUE TITLE
连表查询的时候 我定义了一个查询返回的类，但是执行查询的时候抛错了，请问是我们原因

### ISSUE THREAD

**Issue by zxingdream** [shuxinqin/Chloe#175]
class SchUserBo是定义了返回类型  *** Select 方法也可以返回自定义类型 。**

```
 public PageList<SchUserBo> GetList(int pageIndex, int pageSize, Expression<Func<SchUserBo, bool>> expression)
        {
            var query = Db.Query<MsUserInfo>().LeftJoin<MsUserGas>((user, gas) => user.UserId == gas.GasUserId);
            var bo = new SchUserBo();
            var qs = query.Select((user, gas) => bo);
            var result = qs.Where(expression).ToList();

            var list = qs.PageList(expression, pageIndex, pageSize);
            return list;
        }
```

```
 public static PageList<T> PageList<T>(this IQuery<T> query, Expression<Func<T, bool>> predicate, int pageIndex, int pageSize)
        {
            var count = query.Where(predicate).Count();
            var items = query.Where(predicate).TakePage(pageIndex, pageSize).ToList();
            return new PageList<T>(pageIndex, pageSize, count, items);
        }
```

执行到    var result = qs.Where(expression).ToList();的时候 抛错：Exception_WasThrown

请问下是什么问题啊

**Comment by shuxinqin** [comment]
http://www.52chloe.com/Wiki/Document

**Comment by zxingdream** [comment]
就是翻遍了官网也没找到呀，

**Comment by shuxinqin** [comment]
Q: 使用过程遇到问题/异常怎么办？
A: 请查看 ex.Message、ex.StackTrace 以及 ex.InnerException.Message、ex.InnerException.StackTrace 查找关键错误信息，以及仔细查看使用文档。当然你也可以在github上提issue或者咨询作者，不过寻求帮助时一定要把问题描述清楚，比如用法、框架版本、数据库、错误异常Message和StackTrace等重要信息，最好能一次性提供（搭配代码、截图更佳），以便对方高效理解和排查问题，节省你我时间。

**Comment by zxingdream** [comment]
`public PageList<SchUserInfoBo> GetList(int pageIndex, int pageSize, Expression<Func<SchUserInfoBo, bool>> expression)
        {
            var query = Db.Query<MsUserInfo>().LeftJoin<MsUserGas>((user, gas) => user.UserId == gas.GasUserId);
            var qs = query.Select((user, gas) => new SchUserInfoBo
            {
                UserId = user.UserId,
                UserAddress = user.UserAddress,
                UserIsDelete = user.UserIsDelete,
                UserMobile = user.UserMobile,
                UserName = user.UserName,
                UserNo = user.UserNo,
                GasId = gas.GasId,
                GasMeterNo = gas.GasMeterNo,
                GasUsedStatus = gas.GasUsedStatus,
                GasUsedType = gas.GasUsedType,
                GasUserType = gas.GasUserType
            });
            var list = qs.PageList(expression, pageIndex, pageSize);
            return list;
        }`
找到问题了 原来是没有给对象赋值

**Comment by zxingdream** [comment]
public PageList<SchUserInfoBo> GetList(int pageIndex, int pageSize, Expression<Func<SchUserInfoBo, bool>> expression)
        {
            var query = Db.Query<MsUserInfo>().LeftJoin<MsUserGas>((user, gas) => user.UserId == gas.GasUserId);
            var qs = query.Select((user, gas) => new SchUserInfoBo
            {
                UserId = user.UserId,
                UserAddress = user.UserAddress,
                UserIsDelete = user.UserIsDelete,
                UserMobile = user.UserMobile,
                UserName = user.UserName,
                UserNo = user.UserNo,
                GasId = gas.GasId,
                GasMeterNo = gas.GasMeterNo,
                GasUsedStatus = gas.GasUsedStatus,
                GasUsedType = gas.GasUsedType,
                GasUserType = gas.GasUserType
            });
            var list = qs.PageList(expression, pageIndex, pageSize);
            return list;
        }

**Comment by zxingdream** [comment]
找到问题了 原来是没有给对象赋值
