### ISSUE TITLE
3.0.0版本以后版本出现的问题

### ISSUE THREAD

**Issue by geflay** [shuxinqin/Chloe#178]
多张表实现同一个接口，利用泛型，我们用3.0.0版本实现数据插入没有问题。后面更新到3.9 发现插入（context.insert<'ILogVariableProperty>(obj)）失败了，提示

InnerMessage:
An exception occurred while executing DbCommand. For details please see the inner exception. 对象名 'ILogVariableProperty' 无效。

StackTrace:
 在 Chloe.Data.AdoSession.<ExecuteNonQuery>d__48.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Chloe.Data.AdoSession.ExecuteNonQuery(String cmdText, DbParam[] parameters, CommandType cmdType)
   在 Chloe.Core.DbSession.ExecuteNonQuery(String cmdText, CommandType cmdType, DbParam[] parameters)
   在 Chloe.DbContext.ExecuteNonQuery(DbCommandInfo dbCommandInfo, Boolean async)
   在 Chloe.SqlServer.MsSqlContext.<Insert>d__10`1.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Chloe.Threading.Tasks.TaskExtension.GetResult[TResult](Task`1 task)
   在 WWS.PIS.Server.LogServ.LogConsumer.Insert(ILogVariableProperty log) 位置 D:\PIS\Code\Server\WWS.PIS.ServerE.LogServ\LogConsumer.cs:行号 204
   在 WWS.PIS.Server.LogServ.LogConsumer.<>c__DisplayClass17_0.<BeginConsume>b__1(Object model, BasicDeliverEventArgs ea) 位置 D:\PIS\Code\Server\WWS.PIS.ServerE.LogServ\LogConsumer.cs:行号 75

**Comment by shuxinqin** [comment]
之前的版本context.insert<T>(entity)方法获取实体的类型用的是传入的对象entity.GetType()，这是不合理。后来的版本改成typeof(T)获取，所以你的代码context.insert<'ILogVariableProperty>(obj)就不能用了。之前可以用，是个bug。这个得你改下用法咯。传入强类型的泛型。就是T是什么，就传入什么对象的实体。

**Comment by geflay** [comment]
唉。。。。我现在的问题是传过来的是一个object ,跟本就不知道他的强类型是什么。。。。

**Comment by shuxinqin** [comment]
把你们封装的方法设计成泛型

**Comment by geflay** [comment]
> 把你们封装的方法设计成泛型

还有个问题就是 使用linq的时候如果传入的参数比如日期在linq中进行转换（converter.ToDateTime）的时候会报错

**Comment by shuxinqin** [comment]
改用DateTime.Parse
