### ISSUE TITLE
枚举类型为 byte 类型时，将枚举值转换为数据库值报错

### ISSUE THREAD

**Issue by ydhydh** [shuxinqin/Chloe#18]
能否增加数据库类型 tinyint 支持？

Chloe.Exceptions.ChloeException: Please make sure that the member of the column 'Foo'(7,tinyint,System.Byte) map is the correct type. ---> System.InvalidCastException: 指定的转换无效。

在 System.Data.SqlClient.SqlBuffer.get_Int32()
   在 System.Data.SqlClient.SqlDataReader.GetInt32(Int32 i)
   在 Chloe.Core.InternalDataReader.GetInt32(Int32 i)
   在 Chloe.Extensions.DataReaderExtension.GetEnum[TEnum](IDataReader reader, Int32 ordinal)
   在 Chloe.Mapper.MRMs.ProductPlanEnterEntity_State_a3fb841.Map(Object , IDataReader , Int32 )
   在 Chloe.Mapper.MappingMemberBinder.SetValue(Object obj, IDataReader reader)
   在 Chloe.Mapper.ObjectActivator.CreateInstance(IDataReader reader)

**Comment by shuxinqin** [comment]
当前版本只支持数据库内int和long类型映射到枚举。 tinyint 下个版本加入吧 !- -

**Comment by ydhydh** [comment]
嗯 多谢。期待下个版本了😀。

**Comment by shuxinqin** [comment]
最新版已经支持tinyint映射到枚举。
