### ISSUE TITLE
拦截器获取不到具体的值

### ISSUE THREAD

**Issue by 756616071** [shuxinqin/Chloe#180]
大佬,您好!
![image](https://user-images.githubusercontent.com/44856671/86890736-5b258d00-c130-11ea-974f-9966333fbb82.png)
UPDATE `ComSaveTest` SET `Code`=?P_0,`Name`=?P_1,`Memo`=?P_2 WHERE `ComSaveTest`.`ID` = ?P_3
p_1  p_2 的值不能输出来 ..只能从那个_items里面断点才看得到,
有什么办法可以不断点把值输出吗
![image](https://user-images.githubusercontent.com/44856671/86891042-c8392280-c130-11ea-8900-97efce8e0c64.png)

**Comment by shuxinqin** [comment]
参考 https://github.com/shuxinqin/Chloe/blob/master/src/ChloeDemo/DbCommandInterceptor.cs#L80

**Comment by 756616071** [comment]
好的,谢谢
