### ISSUE TITLE
Oralce，bool nullable类型，对应数据库字段NUMBER(1,0)为可null，异常

### ISSUE THREAD

**Issue by try3** [shuxinqin/Chloe#183]
实体定义
public class BoolTest
{
        public bool? IsEnable { get; set; }
        public DateTime CreateTime { get; set; }
}
创建表
CREATE TABLE "UNITTEST_BoolTest" ( 
	"ISENABLE" NUMBER(1,0)  ,
	"CREATETIME" TIMESTAMP(4)
)

如果insert数据的时候，实体对IsEnable 不赋值，则异常
dbcontext.insert(new BoolTest(){CreateTime =DateTime.Now});
==
Chloe.Exceptions.ChloeException:“An exception occurred while executing DbCommand. For details please see the inner exception. ORA-03115: 不支持的网络数据类型或表示法”
==
应该和#151有关联

**Comment by shuxinqin** [comment]
用NUMBER(9,0)吧
http://www.52chloe.com/Wiki/Document/1249878806332837888

**Comment by try3** [comment]
> 用NUMBER(9,0)吧
> http://www.52chloe.com/Wiki/Document/1249878806332837888

一样的异常

**Comment by shuxinqin** [comment]
没理由啊~，我这测试一直好的。你下github上的demo试试

**Comment by shuxinqin** [comment]
改成这样试试
CREATE TABLE "UNITTEST_BoolTest" (
"ISENABLE" NUMBER(1,0) NULL ,
"CREATETIME" date NULL
)

**Comment by try3** [comment]
排除下time类型的字段影响，重新换个字段。下载最新的code，在demo里加实体测试：

 [Table("UNITTEST_BOOLTEST")]
public class BoolTest
{
        public bool? IsEnable { get; set; }
        public int TestInt { get; set; }
}

CREATE TABLE "UNITTEST_BOOLTEST" (
 "ISENABLE" NUMBER(9,0) NULL,
 "TESTINT" NUMBER(9,0)  NOT NULL
)

报错：
dbContext.Insert(new BoolTest() );

不报错：
dbContext.Insert(new BoolTest() { IsEnable = true } );

**Comment by shuxinqin** [comment]
好的，晚点我测下这种情况。

**Comment by shuxinqin** [comment]
最新版本 v4.8.0 已修改
