### ISSUE TITLE
批量插入不支持忽略列名大小写

### ISSUE THREAD

**Issue by stilltooyoung** [shuxinqin/Chloe#190]
批量插入不支持忽略列名大小写，而单个插入支持，请问这是什么原因呢

**Comment by shuxinqin** [comment]
什么数据库？Chloe哪个版本？

**Comment by shuxinqin** [comment]
bug

**Comment by flyingfive** [comment]
这个问题应该跟SqlBulkCopy有关。不像普通SQL，BCP方式写入应该默认就是强制对列名大小写（与排序规则无关），以及列的ordinal一致性敏感的，代码中的DataTable结构要保持跟DB中的一致才能正确写入。
