### ISSUE TITLE
如何更新当前对象的同时插入导航属性值

### ISSUE THREAD

**Issue by Echoban** [shuxinqin/Chloe#196]
发现使用save方法时，只能插入当前对象和导航对象，如果想要更新当前对象，并对导航属性的对象值新增貌似做不到

**Comment by shuxinqin** [comment]
这个没有哦

**Comment by Echoban** [comment]
好的，感谢回复😀




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "shuxinqin/Chloe"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月9日(星期三) 下午4:21
收件人:&nbsp;"shuxinqin/Chloe"<Chloe@noreply.github.com&gt;;
抄送:&nbsp;"463427812"<463427812@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [shuxinqin/Chloe] 如何更新当前对象的同时插入导航属性值 (#196)





 
这个没有哦
