### ISSUE TITLE
导航属性一对多关系查询出来的数组很多重复的

### ISSUE THREAD

**Issue by liuxunbiao** [shuxinqin/Chloe#198]
有一个实体里面 实体对应多个一对多的关系，然后通过导航查询出来的数据写在第一个IncludeMany中的数据没有重复，其他的都有很多重复的数据，越到后面越多。

如：         var modelresult = await _dataHelper.Query<testInfo>(q => q.Id == fid && q.DeleteFG == false)
                .IncludeMany(q => q.testUris).AndWhere(item => item.DeleteFG == false)//这个数据没有重复的
                .IncludeMany(q => q.testOrigins).AndWhere(item => item.DeleteFG == false)
               .IncludeMany(q => q.testTypes).AndWhere(item => item.DeleteFG == false)
                 .IncludeMany(q => q.testScopes).AndWhere(item => item.DeleteFG == false)
               .IncludeMany(q => q.testms).AndWhere(item => item.DeleteFG == false)
                 .IncludeMany(q => q.teststrictions).AndWhere(item => item.DeleteFG == false)
                 .IncludeMany(q => q.testectUris).AndWhere(item => item.DeleteFG == false)
                .IncludeMany(q => q.testrties).AndWhere(item => item.DeleteFG == false)
                .FirstOrDefaultAsync();

补充说明下 testInfo 主键和其他对象testid关联

**Comment by shuxinqin** [comment]
输出sql，看是不是预期的

**Comment by liuxunbiao** [comment]
> 输出sql，看是不是预期的

输出的sql肯定都是左连接 ，然后最后的条数是 前面的结果条数*后面的结果条数（如果都有数据的话）这样就会重复很多数据，框架里面没有做这个处理吧？  但是最后的结果并不是所有的集合是同样的大小，离Query函数越近数据条数越准确。

**Comment by shuxinqin** [comment]
关联 https://github.com/shuxinqin/Chloe/issues/275
