### ISSUE TITLE
分库分表怎么实现呢

### ISSUE THREAD

**Issue by zxingdream** [shuxinqin/Chloe#199]
现在有个需求，可能用到分表，请教下作者有没有示例实现分表的

**Comment by shuxinqin** [comment]
DbContext的curd方法都带有表名参数重载，自行传入表名
https://github.com/shuxinqin/Chloe/blob/master/src/Chloe/IDbContext.cs#L125

**Comment by yuwochangzai** [comment]
框架要是能自动实现分表操作就好了，不用传入表名，代码不用变动

**Comment by shuxinqin** [comment]
最新代码已经支持分库分表（需自己建好表~）
https://github.com/shuxinqin/Chloe/blob/master/src/ChloeDemo/Sharding/ShardingTest.cs
