### ISSUE TITLE
不建议使用双if的方式锁定资源

### ISSUE THREAD

**Issue by MyErpSoft** [shuxinqin/Chloe#2]
我在Chloe/Chloe/Core/Emit/ClassGenerator.cs，下看见你用if lock if的方式控制并发资源的锁定，建议使用并发安全的字典：ConcurrentDictionary。他在.net 4之后就已经提供。
如果你要支持.net 4之前的版本，使用读写锁也比这种方式性能好，况且这种方式实际是不安全的，因为在if访问时，使用了可能变动的字段。

**Comment by shuxinqin** [comment]
嗯，这块地方确实有点不妥，非常感谢你的建议。
