### ISSUE TITLE
导航属性一对多，导航的深度好像是无限的，

### ISSUE THREAD

**Issue by xhmg** [shuxinqin/Chloe#201]
GetQuery<Last>().IncludeMany(s => s.Users) ，User内的last会包含last,后又会包含完整的User,以此类推

**Comment by shuxinqin** [comment]
是的，会把相关引用设置到 user 上

**Comment by 0hMyGod** [comment]
> 是的，会把相关引用设置到 user 上

这个没有解决方案吗？

**Comment by shuxinqin** [comment]
这是特性之一，刻意这样设计的。

**Comment by 0hMyGod** [comment]
> 这是特性之一，刻意这样设计的。

是可以控制深度的层级么？比如我不需要无限级，我子表中不需要再出现父表的数据，可以实现吗

**Comment by shuxinqin** [comment]
目前没哦。
