### ISSUE TITLE
多GroupBy 怎么实现

### ISSUE THREAD

**Issue by nodyang** [shuxinqin/Chloe#202]
如题

**Comment by shuxinqin** [comment]
多GroupBy?

**Comment by nodyang** [comment]
可能是我写的有问题。sorry

**Comment by nodyang** [comment]
SELECT COUNT(1) AS [C]
FROM (SELECT [HiMall_DistributionPendingSettlementOrder].[ShopId]                           AS [ShopId],
             [HiMall_DistributionPendingSettlementOrder].[ShopName]                         AS [ShopName],
             ISNULL(SUM([HiMall_DistributionPendingSettlementOrder].[SettlementAmount]), 0) AS [Amount]
      FROM [HiMall_DistributionPendingSettlementOrder] AS [HiMall_DistributionPendingSettlementOrder]
      GROUP BY [HiMall_DistributionPendingSettlementOrder].[ShopId],
               [HiMall_DistributionPendingSettlementOrder].[ShopName]
      ORDER BY ISNULL(SUM([HiMall_DistributionPendingSettlementOrder].[SettlementAmount]), 0) DESC) AS [T]


count 分页是不是必须把orderby 去掉

**Comment by shuxinqin** [comment]
还是get不到你的点上。。。
