### ISSUE TITLE
无法查询oracle的视图

### ISSUE THREAD

**Issue by try3** [shuxinqin/Chloe#203]
无法查询oracle的视图。假设视图名是view1.数据库名为db。
框架生成的sql语句是：select * from view1 view1

但这个语法是错误的，在oracle里应该是
select * from db.view1 才可以查询视图

**Comment by shuxinqin** [comment]
这边测试没问题的，你确定下是不是大小写敏感问题。

**Comment by try3** [comment]
不是大小写问题。有的视图可以，有的视图不行，可能是权限问题
