### ISSUE TITLE
超时设置没有作用呢

### ISSUE THREAD

**Issue by 756616071** [shuxinqin/Chloe#205]
你还, 这个  超时我设置的 5  但是 发生错误还是等待了 30s,这是为啥呢 ,是我没有设置对吗?
![image](https://user-images.githubusercontent.com/44856671/96750163-36fb6c80-13fe-11eb-9e77-34fc84dd9fa0.png)

**Comment by shuxinqin** [comment]
这个是执行命令等待时间哦。

**Comment by 756616071** [comment]
那怎么设置  才会在  语句  或者数据库没有连接上,5s就返回错误呢

**Comment by 756616071** [comment]
![image](https://user-images.githubusercontent.com/44856671/96816045-d9900b80-144f-11eb-9f59-1bdc8598f963.png)

**Comment by shuxinqin** [comment]
连接字符串上设置数据库连接等待时间

**Comment by 756616071** [comment]
所有的数据库  报错, 等待时间都只有在连接字符串上设置吗?

**Comment by shuxinqin** [comment]
数据库连接等待时间和执行命令等待时间是两会事，细品。

**Comment by shuxinqin** [comment]
你先确定是连接数据库超时还是执行sql命令超时吧。
