### ISSUE TITLE
Left Join 的时候如果有一个表的数据为null，怎么处理？

### ISSUE THREAD

**Issue by zxingdream** [shuxinqin/Chloe#206]
> 代码片段如下：
   public PageList<ChkWOderBo> GetWorkCheckOrderList(int pageIndex, int pageSize, Expression<Func<ChkWOderBo, bool>> expression, int planId, int platformId)
        {
            var planLst = Db.Query<MsWorkCheckworker>().Where(a => a.CheckWorkPlanId == planId).ToList();
            var platIds = planLst.Select(a => a.CheckWorkPlanId).ToList();
           //这个query被的实体类被自动屏蔽了  如图示
![image](https://user-images.githubusercontent.com/12619680/97153770-fe68e380-17ad-11eb-89d0-3a519eefcc68.png)
            var query = Db.Query<MsUserInfo>().LeftJoin<MsWorkCheckorder>((user, chk) => user.UserId == chk.CheckorderUserid).Select((user, chk) => new ChkWOderBo
            {
                UserIsDelete = user.UserIsDelete,
                UserPlatformId = user.UserPlatformId ?? 0,
                UserId = user.UserId,
                UserNo = user.UserNo,
                UserName = user.UserName,
                UserMobile = user.UserMobile,
                UserInCommunityId = user.UserInCommunityId ?? 0,
                UserInCommunity = user.UserInCommunity,
                UserAddress = user.UserAddress,
                UserBuildingNo = user.UserBuildingNo,
                UserHouseNo = user.UserHouseNo,
                UserUnitNo = user.UserUnitNo,
                CheckOrderWorkerId = chk == null ? -1 : chk.CheckorderWorkerid,
                CheckOrderAddDate = chk.CheckorderAdddate,
                CheckOrderDoorStatus = chk == null ? -1 : chk.CheckOrderDoorStatus,
                CheckOrderId = chk == null ? -1 : chk.CheckorderId,
                CheckOrderNo = chk.CheckOrderNo,
                CheckOrderResultStatus = chk.CheckorderStatus ?? 0,
                CheckOrderSecurityWorkerName = "",
                CheckOrderStatus = -1,
                CheckOrderPlanId = chk == null ? -1 : chk.CheckorderPlanid
            }).Where(c => !c.UserIsDelete && c.UserPlatformId == platformId && platIds.Contains(c.CheckOrderPlanId));
            var list = query.PageList(expression, pageIndex, pageSize);
            return list;
        }
接收对象类如下：
 public class ChkWOderBo {        
        /// 编号： 类型+问号了 （int？）       
        public **int？** CheckOrderId { get; set; }        
        ///     用户Id        
        public long UserId { get; set; }
        public int UserPlatformId { get; set; }        
        ///     楼号        
        public string UserBuildingNo { get; set; }        
        ///     门牌号        
        public string UserHouseNo { get; set; }        
        /// 单元        
        public string UserUnitNo { get; set; }        
        /// 小区ID        
        public long UserInCommunityId { get; set; }        
        /// 小区        
        public string UserInCommunity { get; set; }
        public bool UserIsDelete { get; set; }        
        ///     用户编号        
        public string UserNo { get; set; }        
        ///     用户姓名        
        public string UserName { get; set; }        
        ///     用户手机        
        public string UserMobile { get; set; }        
        ///     地址        
        public string UserAddress { get; set; }        
        ///   安检结果：  类型+问号了        
        public **int？** CheckOrderResultStatus { get; set; }        
        ///     入户状态：  类型+问号了        
        public **int？** CheckOrderDoorStatus { get; set; }        
        ///   安检状态：  类型+问号了        
        public int？ CheckOrderStatus { get; set; }        
        ///   安检编号        
        public string CheckOrderNo { get; set; }        
        ///   安检员ID：  类型+问号了        
        public **int？** CheckOrderWorkerId { get; set; }        
        ///   安检员        
        public string CheckOrderSecurityWorkerName { get; set; }        
        ///   日期：  类型+问号了        
        public **DateTime？** CheckOrderAddDate { get; set; }        
        /// 安检任务ID：  类型+问号了        
        public **int？** CheckOrderPlanId { get; set; }
    }
现在有两个问题：
1、**MsWorkCheckorder表**的数据有可能为null，然后就导致映射的时候出错，
2、**WHERE** 条件里的  platIds.Contains(c.CheckOrderPlanId) 提示语法错误，原因还是因为上表的数据有可能为null

请指教下怎么这个问题我应该怎么去改  ，谢谢，谢谢， 谢谢！！！

**Comment by shuxinqin** [comment]
把属性设置为可空类型

**Comment by zxingdream** [comment]
/// 安检任务ID： 类型+问号了
public int？ CheckOrderPlanId { get; set; }
这里其实都设置过，还是会抛错的

**Comment by shuxinqin** [comment]
Q: 使用过程遇到问题/异常怎么办？
A: 请查看 ex.Message、ex.StackTrace 以及 ex.InnerException.Message、ex.InnerException.StackTrace 查找关键错误信息，以及仔细查看使用文档。当然你也可以在github上提issue或者咨询作者，不过寻求帮助时一定要把问题描述清楚，比如用法、框架版本、数据库、错误异常Message和StackTrace等重要信息，最好能一次性提供（搭配代码、截图更佳），以便对方高效理解和排查问题，节省你我时间。

**Comment by zxingdream** [comment]
其实抛错的原因我找到了是因为：
var query = Db.Query<MsUserInfo>().LeftJoin<MsWorkCheckorder>((user, chk) => user.UserId == chk.CheckorderUserid); **这里映射的chk对象有可能为null**
var data = query.Select((user, chk) => new ChkWOderBoDb { })
var list = data.PageList(expression, pageIndex, pageSize);//然后就导致这个分页抛错，错误描述如下图
![image](https://user-images.githubusercontent.com/12619680/97672094-6c6e1d00-1ac4-11eb-95db-a07decce5475.png)

**Comment by shuxinqin** [comment]
data.PageList(expression, pageIndex, pageSize) 的 expression  可能有问题
