### ISSUE TITLE
关于主键默认自增的建议

### ISSUE THREAD

**Issue by flyingfive** [shuxinqin/Chloe#21]
先申明一下，并不是挑刺．
看到了你TypeDescriptor.cs里101行的说明．如果实体只存在１个主键，属性为支持自增的数据类型，并且没有显式为属性标记非自增特性，则默认属性映射为自增列．这点我觉得不太合理，甚至设计自增和非自增两个Attribute的存在也不合理．
１，如果我数据库主键就是int型，非自增为主键．该主键由业务计算，由代码校验确认全局唯一性，或者如snowflake这类算法生成全局唯一ID．并非自增，如何支持？
２，对于自增标识特性，从逻辑上理解，标识了就是，未标识就不是．设计自增与非自增两个映射特性，有点冗余．(未了解Ｏracle，ＭySql等是否同时存在自增与非自增两种列设置功能)

**Comment by shuxinqin** [comment]
最早的版本是没有默认自增规则的，就如你所说需要显示标记自增。后来我们在使用过程中发现，如果主键是int、long等值类型，大部分是自增的，所以，经深思熟虑后在某个版本中才增加了这个默认规则。从设计角度着实有点不合理，但从使用角度省了一些工作。

**Comment by flyingfive** [comment]
看来你们大部分项目中还是青睐于数值型自增主键的.虽有违设计,也无伤大雅.

**Comment by 2821840032** [comment]
数据库ID是用的snowflake ID 出了这个问题，不得不把在类库引用chloe包，每个ID打上标签...

**Comment by shuxinqin** [comment]
如果不想让实体有侵入，可以考虑FluentMapping http://www.52chloe.com/Wiki/Document/1012941695404347392
