### ISSUE TITLE
执行存储过程返回2个结果集怎么获取？

### ISSUE THREAD

**Issue by panda-big** [shuxinqin/Chloe#213]
我有一个存储过程里面需要返回2个集合数据，我应该怎么获取？
目前执行存储过程的是用dbContext.SqlQuery<User>("Proc_GetUser", CommandType.StoredProcedure, id)这种方法。

当然我可以用datatable的方式。我想知道有没有更好方式？

**Comment by shuxinqin** [comment]
没有哦~

**Comment by panda-big** [comment]
好的
