### ISSUE TITLE
Task执行问题

### ISSUE THREAD

**Issue by swpudp** [shuxinqin/Chloe#216]
![QQ图片20201125181144](https://user-images.githubusercontent.com/11451713/100214524-f76af780-2f4a-11eb-955f-228c8d0cb7fb.png)

**Comment by shuxinqin** [comment]
所有的InsertRangeAsync都不执行？

**Comment by swpudp** [comment]
private Task Execute(Func<IDbContext, Task> func)
        {
            using (IDbContext ctx = new MySqlContext(new MySqlConnectionFactory()))
            {
                return func(ctx);
            }
        }

        /// <summary>
        /// 批量写入测试1
        /// </summary>
        /// <returns></returns>
        [TestMethod]
        public async Task BulkCreateOneTaskTest()
        {
            List<TestLog> logs1 = Enumerable.Range(0, 10).Select(_ => new TestLog
            { Id = Guid.NewGuid(), Level = "INFO", Logged = DateTime.Now, Logger = "unit_test1" }).ToList();

            List<TestLog> logs2 = Enumerable.Range(0, 10).Select(_ => new TestLog
            { Id = Guid.NewGuid(), Level = "INFO", Logged = DateTime.Now, Logger = "unit_test2" }).ToList();

            await Execute(ctx =>
            {
                Task task1 = ctx.InsertRangeAsync(logs2, "log1").ContinueWith(t =>
                {
                    //IDbContext ctx1 = ctx;
                    ctx.InsertRangeAsync(logs2, "log2");
                });
                return Task.WhenAll(task1);
            });
        }

      /// <summary>
        /// 批量写入测试2
        /// </summary>
        /// <returns></returns>
        [TestMethod]
        public async Task BulkCreateManyTaskTest()
        {
            List<TestLog> logs1 = Enumerable.Range(0, 10).Select(_ => new TestLog
            { Id = Guid.NewGuid(), Level = "INFO", Logged = DateTime.Now, Logger = "unit_test1" }).ToList();

            List<TestLog> logs2 = Enumerable.Range(0, 10).Select(_ => new TestLog
            { Id = Guid.NewGuid(), Level = "INFO", Logged = DateTime.Now, Logger = "unit_test2" }).ToList();

            List<TestLog> logs3 = Enumerable.Range(0, 10).Select(_ => new TestLog
            { Id = Guid.NewGuid(), Level = "INFO", Logged = DateTime.Now, Logger = "unit_test3" }).ToList();

            List<TestLog> logs4 = Enumerable.Range(0, 10).Select(_ => new TestLog
            { Id = Guid.NewGuid(), Level = "INFO", Logged = DateTime.Now, Logger = "unit_test4" }).ToList();

            await Execute(ctx =>
            {
                Task task1 = ctx.InsertRangeAsync(logs1, "log1");
                Task task2 = ctx.InsertRangeAsync(logs2, "log2").ContinueWith(t =>
                {
                    IDbContext ctx1 = ctx;
                    ctx1.InsertRangeAsync(logs3, "log3");
                });

                Task task3 = ctx.InsertRangeAsync(logs4, "log4");

                return Task.WhenAll(task1, task2, task3);
            });
        }

这是我搞的单元测试，两个测试都是ContinueWith里面的未执行


swpudp@163.com
 
发件人： so
发送时间： 2020-11-27 00:30
收件人： shuxinqin/Chloe
抄送： Ping Ting; Author
主题： Re: [shuxinqin/Chloe] Task执行问题 (#216)
所有的InsertRangeAsync都不执行？

**Comment by shuxinqin** [comment]
这个得你自己去研究研究了哦
