### ISSUE TITLE
使用微软官方特性标注实体自增列

### ISSUE THREAD

**Issue by xiaolu6t** [shuxinqin/Chloe#217]
```
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Key]
        [Column("Id")]
        public int Id { get; set; }
```
1. 其中Key相当于IsPrimaryKey.
2. DatabaseGenerated(DatabaseGeneratedOption.Identity)相当于AutoIncrement
3. DatabaseGenerated(DatabaseGeneratedOption.None)相于当NoAutoIncrement.
4. 官方Table特性,希望也能支持一下.
这些特性是微软EF专用的.如果兼容一下,两个实体就可以通用.可能是之前并不了解.因此才自定了这些特性.

**Comment by shuxinqin** [comment]
官方的特性标注不能满足特定的需求，所以没考虑了。
