### ISSUE TITLE
多线程中事务批量插入or更新操作抛错Connection must be valid and open to rollback transaction

### ISSUE THREAD

**Issue by zxingdream** [shuxinqin/Chloe#220]
![image](https://user-images.githubusercontent.com/12619680/100842420-c8590680-34b3-11eb-9302-093f16d86687.png)
这是具体执行插入或者更新的事务操作，
然后另外一个地方有用到其他查询，然后这里就抛错了：
![image](https://user-images.githubusercontent.com/12619680/100842373-b5463680-34b3-11eb-88e4-d685e6fb9563.png)

**Comment by zxingdream** [comment]
两个function是同步操作的

**Comment by shuxinqin** [comment]
DbContext对象是非线程安全的，注意用法~
