### ISSUE TITLE
ToList<T>()时报错

### ISSUE THREAD

**Issue by kygl** [shuxinqin/Chloe#221]
数据表的列是
BrandID，与BrandName

现在创建如下实体   
 [Table("Brand")]
    public class Brand
    {
       [Column(IsPrimaryKey = true)]
        public int BrandID { get; set; }
        [Column(Size = 20)]
        public string BrandCode { get; set; }
        [Column(Name = "BrandName", Size = 50)]
        public string BrandNameB { get; set; }
    }

            var q = dbContext.Query<Brand>()
                .Select(a => new
                {
                    a.BrandID, a.BrandCode
                })
                .OrderByDesc(a => a.BrandID);
            var l = q.ToList<Brand>();

抛出异常了。

同问Column的Name属性不是用来支持别名吗？

**Comment by shuxinqin** [comment]
var l = q.ToList(); 就行，不要写泛型了 

Q: 使用过程遇到问题/异常怎么办？
A: 请查看 ex.Message、ex.StackTrace 以及 ex.InnerException.Message、ex.InnerException.StackTrace 查找关键错误信息，以及仔细查看使用文档。当然你也可以在github上提issue或者咨询作者，不过寻求帮助时一定要把问题描述清楚，比如用法、框架版本、数据库、错误异常Message和StackTrace等重要信息，最好能一次性提供（搭配代码、截图更佳），以便对方高效理解和排查问题，节省你我时间。

**Comment by kygl** [comment]
是可以的。
