### ISSUE TITLE
为什么生成的sql会有好多CAST()类型转换

### ISSUE THREAD

**Issue by kygl** [shuxinqin/Chloe#223]
mysql数据库
Status列为smallint类型
代码：
short status = 1;
IQuery<Activity> q = dbContext.Query<Activity>().Where(a => a.Status == status);
生成的sql的查询条件会
WHERE CAST(`Activity`.`Status` AS SIGNED) = ?P_0

**Comment by shuxinqin** [comment]
a.Status 什么类型？

**Comment by kygl** [comment]
a.Status只要不是int都会生成Cast来转类型
