### ISSUE TITLE
IOrderedQuery<T> OrderBy<T>(this IQuery<T> q, string orderString) 异常

### ISSUE THREAD

**Issue by anthony6li** [shuxinqin/Chloe#225]
![image](https://user-images.githubusercontent.com/18346308/102583943-7addca00-4140-11eb-8572-47a421b0426b.png)
![image](https://user-images.githubusercontent.com/18346308/102583974-88934f80-4140-11eb-9c6a-4bacb7d1e1fb.png)

**Comment by shuxinqin** [comment]
升级dll到最新
