### ISSUE TITLE
截断二进制数据

### ISSUE THREAD

**Issue by 756616071** [shuxinqin/Chloe#226]
这条SQL语句在数据库中直接执行没有问题,但是不知道为啥 ,用query  或者用  reader  都会异常
![image](https://user-images.githubusercontent.com/44856671/102687490-60801b00-422a-11eb-83bf-529741acfab9.png)

![image](https://user-images.githubusercontent.com/44856671/102687490-60801b00-422a-11eb-83bf-529741acfab9.png)

**Comment by 756616071** [comment]
![Uploading image.png…]()

**Comment by shuxinqin** [comment]
Q: 使用过程遇到问题/异常怎么办？
A: 请查看 ex.Message、ex.StackTrace 以及 ex.InnerException.Message、ex.InnerException.StackTrace 查找关键错误信息，以及仔细查看使用文档。当然你也可以在github上提issue或者咨询作者，不过寻求帮助时一定要把问题描述清楚，比如用法、框架版本、数据库、错误异常Message和StackTrace等重要信息，最好能一次性提供（搭配代码、截图更佳），以便对方高效理解和排查问题，节省你我时间。
