### ISSUE TITLE
有些字段查询赋值 不了到实体

### ISSUE THREAD

**Issue by kygl** [shuxinqin/Chloe#227]
mysql的表
DeviceID int
Num tinyint
Type tinyint

实体
int DeviceID
byte Num
byte Type

Input Int32 ?P_0 = 484;
Input Int32 ?P_1 = 4;
Input Int32 ?P_2 = 2;
SELECT `device_data`.`deviceID` AS `DeviceID`,`device_data`.`type` AS `Type`,`device_data`.`num` AS `Num` FROM `device_data` AS `device_data` WHERE (`device_data`.`deviceID` = ?P_0 AND CAST(`device_data`.`type` AS SIGNED) = ?P_1 AND CAST(`device_data`.`num` AS SIGNED) = ?P_2) LIMIT 0,1

代码
var q = mDbContext.Query<DeviceData>()
                .Select(a => new DeviceData()
                {
                   DeviceID = a.DeviceID,
                    Type = a.Type,
                   Num = a.Num
                })
                .Where(a => a.DeviceID == param.ID && a.Type == param.Type && a.Num == param.Num);
var deviceData = q.First();
读出来deviceData.Type与deviceData.Num一直都是1

为什么？

**Comment by shuxinqin** [comment]
拿到sql，在数据库里运行看结果。

**Comment by kygl** [comment]
数据库出来的结果正常的，试过将表字段tinyint改为smallint。。生成的实体用short就能赋值了。说明tinyint到byte转换是不是有问题。

**Comment by kygl** [comment]
问题找到了，连接串里加入TreatTinyAsBoolean=false就行了。
