### ISSUE TITLE
如何使用nolock？

### ISSUE THREAD

**Issue by SkyChenSky** [shuxinqin/Chloe#228]
是否有提供nolock方法？我查了文档没有找到

**Comment by shuxinqin** [comment]
https://github.com/shuxinqin/Chloe/blob/master/src/Chloe/IDbContext.cs#L20
https://github.com/shuxinqin/Chloe/blob/master/src/Chloe/LockType.cs

**Comment by SkyChenSky** [comment]
非常感谢回复
