### ISSUE TITLE
请问是否可以用于 UWP 项目？

### ISSUE THREAD

**Issue by XuJinNet** [shuxinqin/Chloe#23]
现在公司在做 UWP 项目，需要用到 ORM 框架，用了一段时间微软推荐的 EF 框架，效果不理想，准备更换框架。
请问该 Chloe 是否可以用于 UWP 项目？

**Comment by shuxinqin** [comment]
我没弄过UWP，我也不懂能不能用。你可以试试，如果不支持告诉我下。

**Comment by fudiwei** [comment]
@XuJinNet 可以用，但是项目类型得改，需要自己编译 Chole.Sqlite 的源码吧。

BTW，微软啥时候推荐在 UWP 里使用 EF 了……

**Comment by liuyl1992** [comment]
@XuJinNet EF的定位本身就是服务器后端来用，啥时候推荐APP用EF了，App就适合轻便框架dapper或者这个

**Comment by XuJinNet** [comment]
@liuyl1992 @fudiwei  好的，谢谢
