### ISSUE TITLE
sqlserver的datetime

### ISSUE THREAD

**Issue by try3** [shuxinqin/Chloe#231]
c#的DateTime.MinValue => 0001/01/01 00:00:00

sqlsever的SqlDateTime.MinValue.Value  => 1753/01/01 00:00:00 

建议当c#为最小值时，sqlsever能自动转换为 1753/01/01 00:00:00  而不是 0001/01/01 00:00:00

**Comment by shuxinqin** [comment]
呃....建议不错，但群主不打算接受~o(∩_∩)o

**Comment by try3** [comment]
那只能自己修改代码了
