### ISSUE TITLE
IDbValueConverter的使用

### ISSUE THREAD

**Issue by try3** [shuxinqin/Chloe#233]
继承IDbValueConverter接口，实现了public object Convert(object value)

使用DbConfiguration.ConfigureMappingType<DateTime>().HasDbValueConverter<xxx>()注册了

但这接口不起作用？请问下是这么使用的吗？

**Comment by shuxinqin** [comment]
只有当数据库类型和C#类型对应不上时才会调用。比如数据库类型是int类型，实体属性是long/string类型。

**Comment by try3** [comment]
当前系统有什么方法可以重写的方法吗？

**Comment by shuxinqin** [comment]
不懂你要说啥~
