### ISSUE TITLE
属性的特性

### ISSUE THREAD

**Issue by hargenhz** [shuxinqin/Chloe#235]
有没有可以标记不显示到查询结果的属性的特性

**Comment by shuxinqin** [comment]
Chloe.Annotations.NotMappedAttribute
http://www.52chloe.com/Wiki/Document/3324793835434803200

**Comment by hargenhz** [comment]
好的，谢谢。我看到了这个特性NotMapped，是不映射属性字段，其实我想说的是“排除”这个属性，也就是不显示输出到查询结果，虽然我可以显示的映射 select(x=>new {a=x.a,b=x.b}) ，或者 干脆定义一个新的model

**Comment by shuxinqin** [comment]
http://www.52chloe.com/Wiki/Document/3432725391804989440

**Comment by hargenhz** [comment]
好的，谢谢，我看到了，很有帮助。虽然我的本意是尽量少的定义额外的model，当前我使用的匿名对象方式。
