### ISSUE TITLE
Update方法目前提供的重载在实际业务场景使用上不方便

### ISSUE THREAD

**Issue by 15168440402** [shuxinqin/Chloe#236]
/// <summary>
    /// 后台管理员用户
    /// </summary>
    public class AdminUser : GuidPrimaryKey
    {
        /// <summary>
        /// 登录名称
        /// </summary>
        public string LoginName { get; set; }
        /// <summary>
        /// 登录密码
        /// </summary>
        [JsonIgnore]
        public string Password { get; set; }
        /// <summary>
        /// 显示名称
        /// </summary>
        public string DisplayName { get; set; }
        /// <summary>
        /// 联系方式
        /// </summary>
        public string ContactWay { get; set; }
        /// <summary>
        /// 备注
        /// </summary>
        public string Remark { get; set; }
        /// <summary>
        /// 是否启用
        /// </summary>
        public bool Enable { get; set; }
        /// <summary>
        /// 角色Id
        /// </summary>
        public Guid? RoleId { get; set; }
        /// <summary>
        /// 商铺Id
        /// </summary>
        public Guid? ShopId { get; set; }
    }

第一点：比如我只想修改用户的Enable属性，而update方法必须提供整个AdminUser对象，再指定字段。
我目前对应的解决方案是这样的：

    /// <summary>
    /// 后台用户启用/停用入参
    /// </summary>
    [Table("AdminUser")]
    public class AdminUserSwitchInput
    {
        /// <summary>
        /// 后台用户Id
        /// </summary>
        public Guid Id { get; set; }
        /// <summary>
        /// 角色Id
        /// </summary>
        public bool Enable { get; set; }
    }
 await _dbContext.UpdateAsync(adminUserSwitchInput) 

第二点：AdminUserd对象里属性很多，修改用户基础信息时，其中CreateTime属性我不想修改，Update时就需要把AdminUser中除了CreateTime属性都要写一遍！，当然，这里也可以使用我上面那种方法解决，但是这样我就需要维护不止一套用户基础信息类了。
请问下作者，在目前的chloe框架上是否有可能实现类似IQuery中的Ignore功能，或者说在ColumnAttribute中提供QueryOnly、InsertOnly、UpdateOnly这种指定呢？

**Comment by shuxinqin** [comment]
1. 不需要传入整个对象更新，dbContext.Update<User>(a => a.Id = 1, a => new User() { Enable = true });
2. QueryOnly、InsertOnly、UpdateOnly不错的建议。

**Comment by shuxinqin** [comment]
最新版本4.12已经支持对指定字段设置不更新。UpdateIgnoreAttribute

**Comment by 15168440402** [comment]
@shuxinqin  很惊喜，作者接纳了我的建议，并且迅速进行了框架升级发版，UpdateIgnoreAttribute解决了我三年的痛点，谢谢作者，赞。
