### ISSUE TITLE
使用sqllite3 tolist报错请问是怎么回事呢？

### ISSUE THREAD

**Issue by xrf116** [shuxinqin/Chloe#24]
在 System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   在 System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
   在 Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
   在 System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   在 System.Threading.ThreadHelper.ThreadStart()</StackTrace><ExceptionString>Chloe.Exceptions.ChloeException: An error occurred while mapping the column 'Id'(0,integer,System.Int64). For details please see the inner exception. ---&amp;gt; System.TypeAccessException: 方法“Chloe.Mapper.MRMs.ImageInfo_Id_ded071.Map(System.Object, System.Data.IDataReader, Int32)”尝试访问类型“PictureDetective.Modle.ImageInfo”失败。
   在 Chloe.Mapper.MRMs.ImageInfo_Id_ded071.Map(Object , IDataReader , Int32 )
   在 Chloe.Mapper.ObjectActivator.CreateInstance(IDataReader reader)

数据库中id是integer类型

**Comment by shuxinqin** [comment]
尝试访问类型“PictureDetective.Modle.ImageInfo”失败，类和属性要 public

**Comment by xrf116** [comment]
是这样的谢谢，
