### ISSUE TITLE
大佬，帮我解决远程sql server 断开连接的问题吧

### ISSUE THREAD

**Issue by MonsterUncle** [shuxinqin/Chloe#243]
麻烦大佬了
这是我的项目https://gitee.com/qian_wei_hong/WaterCloud
net5分支
DBfirst的项目，数据库在database文件夹下面
远程连接sqlserver的时候，有时候会报 A transport-level error has occurred when receiving results from the server. (provider: Session Provider, error: 19 - Physical connection is not usable的异常，诡异的就是偶发性
本地连接是没有问题

**Comment by shuxinqin** [comment]
这个问题只能谷歌了
https://stackoverflow.com/questions/22714569/cannot-get-rid-of-physical-connection-is-not-usable-exception

**Comment by MonsterUncle** [comment]
这里面也没有什么好的解决方案
