### ISSUE TITLE
查询空值处理

### ISSUE THREAD

**Issue by gangdoufu** [shuxinqin/Chloe#248]
oracle 数据库 版本11.2.4 在查询的时候有一列的值为null 导致报错。需要怎么处理？~

**Comment by gangdoufu** [comment]
clone 版本是4.1

**Comment by gangdoufu** [comment]
Chloe 版本是4.1

**Comment by shuxinqin** [comment]
Q: 使用过程遇到问题/异常怎么办？
A: 请查看 ex.Message、ex.StackTrace 以及 ex.InnerException.Message、ex.InnerException.StackTrace 查找关键错误信息，以及仔细查看使用文档。当然你也可以在github上提issue或者咨询作者，不过寻求帮助时一定要把问题描述清楚，比如用法、框架版本、数据库、错误异常Message和StackTrace等重要信息，最好能一次性提供（搭配代码、截图更佳），以便对方高效理解和排查问题，节省你我时间。

**Comment by shuxinqin** [comment]
closing
