### ISSUE TITLE
请教大佬，我这写个DBHelper有没有问题，用在net5 ioc中

### ISSUE THREAD

**Issue by MonsterUncle** [shuxinqin/Chloe#250]
public class DBContexHelper
    {
        private static string dbType = GlobalContext.SystemConfig.DBProvider;
        private static string dbConnectionString = GlobalContext.SystemConfig.DBConnectionString;
        private static string DBCommandTimeout = GlobalContext.SystemConfig.DBCommandTimeout;

        public static IDbContext Contex(string ConnectStr = "", string providerName = "")
        {
            ConnectStr = string.IsNullOrEmpty(ConnectStr) ? dbConnectionString : ConnectStr;
            providerName = string.IsNullOrEmpty(providerName) ? dbType : providerName;
            IDbContext context;
            switch (providerName)
            {
                case Define.DBTYPE_SQLSERVER:
                    SqlConnection.ClearAllPools();
                    var dbContext = new MsSqlContext(new MSSqlConnectionFactory(ConnectStr));
                    //2012以上版本切换使用 OFFSET FETCH 分页方式
                    //dbContext.PagingMode = PagingMode.OFFSET_FETCH;
                    context = dbContext;
                    context.Session.CommandTimeout = int.Parse(DBCommandTimeout);
                    break;
                case Define.DBTYPE_MYSQL:
                    context = new MySqlContext(new MySqlConnectionFactory(ConnectStr));
                    context.Session.CommandTimeout = int.Parse(DBCommandTimeout);
                    break;
                case Define.DBTYPE_ORACLE:
                    var con = new OracleContext(new OracleConnectionFactory(ConnectStr));
                    con.Session.CommandTimeout = int.Parse(DBCommandTimeout);
                    con.ConvertToUppercase = false;
                    context = con;
                    break;
                default:
                    context = new MsSqlContext(ConnectStr);
                    context.Session.CommandTimeout = int.Parse(DBCommandTimeout);
                    break;
            }
            return context;
        }
    }

           在startup中
            //注入数据库连接
            services.AddScoped<Chloe.IDbContext>((serviceProvider) =>
            {
                return DBContexHelper.Contex();
            });

**Comment by MonsterUncle** [comment]
环境net5
版本最新的


有个BUG，SQLserver中，当主键类型为int或者long，不自增的情况下，使用insert时被忽略了

**Comment by shuxinqin** [comment]
未能重现你所说的问题。
检查下是否打了Chloe.Annotations.NonAutoIncrementAttribute标记？

**Comment by MonsterUncle** [comment]
我的意思是 int 或者long类型 主键的话，ORM默认认为是自增的是吗？


我后面贴了Chloe.Annotations.NonAutoIncrementAttribute就可以了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "shuxinqin/Chloe"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月10日(星期四) 晚上10:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [shuxinqin/Chloe] 请教大佬，我这写个DBHelper有没有问题，用在net5 ioc中 (#250)





 
未能重现你所说的问题。
 检查下是否打了Chloe.Annotations.NonAutoIncrementAttribute标记？

**Comment by shuxinqin** [comment]
嗯，是的。属性名为id，并且是int，long类型，不打特性的话默认自增。

**Comment by MonsterUncle** [comment]
大佬，建议加个git服务器 gitee的，让国内的人能够访问，git可以设置双服务器，类似这样的

**Comment by shuxinqin** [comment]
矫情~！！😡

**Comment by MonsterUncle** [comment]
如何获取存储过程里面的renturn的参数，存储过程本身没有定义out参数

**Comment by shuxinqin** [comment]
Chloe貌似不支持~！

**Comment by MonsterUncle** [comment]
存储过程确实不支持returnvalue，建议可以支持下，我看ef dapper和sqlsugar都是支持的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "shuxinqin/Chloe"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月25日(星期五) 晚上7:02
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [shuxinqin/Chloe] 请教大佬，我这写个DBHelper有没有问题，用在net5 ioc中 (#250)





 
Chloe貌似不支持~！

**Comment by shuxinqin** [comment]
用dbContext.Session. 下的方法执行存储过程，用法基本和原生驱动一样，理论上驱动支持，Chloe也是支持的。你可以试下。

**Comment by shuxinqin** [comment]
最新版本已加上ParamDirection.ReturnValue支持~

**Comment by MonsterUncle** [comment]
好的，谢谢大佬




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "shuxinqin/Chloe"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月26日(星期六) 凌晨0:09
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [shuxinqin/Chloe] 请教大佬，我这写个DBHelper有没有问题，用在net5 ioc中 (#250)





 
最新版本已加上ParamDirection.ReturnValue支持~
