### ISSUE TITLE
有个疑问

### ISSUE THREAD

**Issue by nodyang** [shuxinqin/Chloe#253]
![image](https://user-images.githubusercontent.com/3090191/123374007-f8cfd180-d5b8-11eb-8c8d-1d96c2da7b48.png)
![image](https://user-images.githubusercontent.com/3090191/123374021-02f1d000-d5b9-11eb-8397-c8dfb5962b44.png)

Name 和 name 必需大小写一样吗？   测试大小写一样OK

**Comment by nodyang** [comment]
有没有可能去兼容大小写

**Comment by shuxinqin** [comment]
我这边不打算做兼容。MapTo是个扩展方法，你可以考虑参考MapTo源码自己改一下。

**Comment by nodyang** [comment]
3Q
