### ISSUE TITLE
有没有考虑过db的自动释放配置

### ISSUE THREAD

**Issue by MonsterUncle** [shuxinqin/Chloe#255]
大佬，可以的话，能增加个db的自动释放配置，IOC中可以有作用域，但是我手动切换时，就没法保证这个db能被释放掉

**Comment by shuxinqin** [comment]
如果有ioc的话，所有的db包括手动切换的db都通过ioc创建就好了。
如果没有ioc的项目的话，自建一个db管理器，请求管道里结束时全部销毁掉就了。

**Comment by shuxinqin** [comment]
补充一下：没开事务的情况下，每次查询完都会Close掉DbConnection，即调用DbConnection.Close。DbContext.Dispose只把DbConnection销毁，即DbConnection.Dispose。对于一个请求来说，不需要每次查询完就Dispose掉一个DbConnection对象，那是不合理的。
