### ISSUE TITLE
oracle 库执行产生莫名语句

### ISSUE THREAD

**Issue by xulei-Itachi** [shuxinqin/Chloe#256]
为什么在Oracle中，使用该Orm会有一条奇怪的语句在执行？我单独写了个程序，做一次简单查询就会有。

语句内容为：
DECLARE  err_code VARCHAR2(2000);  err_msg VARCHAR2(2000);  BEGIN  SELECT VALUE into :p_nls_comp from nls_session_parameters where PARAMETER='NLS_COMP'; SELECT VALUE into :p_nls_length_semantics from nls_session_parameters where PARAMETER='NLS_LENGTH_SEMANTICS'; SELECT VALUE into :p_nls_nchar_conv_excep from nls_session_parameters where PARAMETER='NLS_NCHAR_CONV_EXCP'; SELECT '0' into :p_err_code from dual;  SELECT '0' into :p_err_msg from dual;  END;

![1626331017124](https://user-images.githubusercontent.com/39308586/125740950-c9125ef2-5437-4c6c-803d-aeac3b849455.jpg)

**Comment by shuxinqin** [comment]
这个不是orm生成的。可能是驱动或者...我也不知道了。。。
