### ISSUE TITLE
SqlServer同时插入二个实体数据的问题

### ISSUE THREAD

**Issue by AHLIRL** [shuxinqin/Chloe#258]
问题描述:SqlServer,  有类型T1和T2, 对应实体t1,t2, 比如单据和单据明细, 同时插入t1和t2时:
1. 执行Inset t1后Inset t2时异常, 这个时候怎么回滚? 在Insert前开启事务, 异常时Rollback是否可行?  
2. 如果  t1和t2都是List, 我看Inset List<Entity>的代码里已经使用了事务 , 那么在插入集合t1后插入集合t2时异常, 怎么回滚? 插入集合t1时已经使用事务提交了数据.
作者能否解答下. 有没有什么可行的方法

**Comment by shuxinqin** [comment]
按照文档开启事务操作就好了 https://github.com/shuxinqin/Chloe/wiki/Transaction

**Comment by AHLIRL** [comment]
我已经使用了事务,
using(ITransientTransaction tran = dbContext.BeginTransaction())
{
//t1,t2都是集合
    dbContext.InsertRange(t1);
    dbContext.InsertRange(t2);
}
我的问题是在InsertRange的结尾已经用了事务, 我这里再用事务无法还能回滚吗?
第386行
https://github.com/shuxinqin/Chloe/blob/master/src/Chloe.SqlServer/MsSqlContext.cs

**Comment by shuxinqin** [comment]
如果外面已经开启了事务，就不会运行到386行了
https://github.com/shuxinqin/Chloe/blob/master/src/Chloe.SqlServer/MsSqlContext.cs#L379

**Comment by AHLIRL** [comment]
好的谢谢
