### ISSUE TITLE
小小的建议

### ISSUE THREAD

**Issue by JHeLiu** [shuxinqin/Chloe#26]
1、API设计的非常优雅。很喜欢，
2、在调用储存过程中，希望可以借鉴下Dapper的模式，比如大多数的时候可能都喜欢这样使用。

```
var dbParm = new DbParam();
dbParm.AddDynamic(new {Name="",Sex=0}); //都是一样的输入类型参数，可能会选择匿名类 或者实体类
dbParm.Add("OutMsg","",DbType.String,ParamDirection.Output);
dbParm.Add("OutMsg1","",DbType.String,ParamDirection.Output);


//执行方法
ontext.Session.ExecuteNonQuery("PROC_NAME",dbParm);

//获取的想要的输出参数
dbParm.Get<string>("OutMsg");
dbParm.Get<string>("OutMsg1");

```
 

还有我的储存过程 可能会返回数据集，或许我并不知道它的多少。可能是DataTable 也可能是DataSet类型。或者我会返回输出参数+数据集一起都出现。

3、希望能把所有的库跟核心库融合在一起，因为并不想去选择对应版本的类库。希望这件事由代码帮我去做.

希望层主加油，非常感谢你的分享库，

**Comment by shuxinqin** [comment]
1. 喜欢就好，嘿嘿😁
2. 执行sql接口不是咱这个框架的重心，所以不会像dapper那样优化执行原生sql的接口。不过也提供了不少的扩展方法支持参数是匿名类或者实体类以及返回datatable和dataset的方法，https://github.com/shuxinqin/Chloe/blob/master/src/DotNet/Chloe.Extension/DbSessionExtension.cs
3. 库跟核心库分开在使用上可能会麻烦那么一点，这都是小事，问题不大。但在框架更新和升级上可维护性相对融合一起的做法强一些，而且也很灵活，因此暂时还没把所有的库跟核心库融合在一起念头。
😄
