### ISSUE TITLE
更新时不支持Math.Round的问题

### ISSUE THREAD

**Issue by AHLIRL** [shuxinqin/Chloe#260]
执行更新操作dbcontext.Update<T>(c=>c.id==115,c=>new T {width=Math.Round(c.width*3.1415926,4)});
抛出异常
Does not support method 'Math.Round(Decimal d,Int32 decimals,MidpointRounding mode)'.
也就是Chloe不支持c# 的四舍五入, Chloe 有没有替代的实现? Sql这个类没发现Round方法

**Comment by shuxinqin** [comment]
是的，没对round做支持

**Comment by AHLIRL** [comment]
有没有替代的方法? 下次更新能加入对Round的支持吗?

**Comment by shuxinqin** [comment]
1. 自定义函数映射 https://github.com/shuxinqin/Chloe/wiki/Custom-function
2. 设置方法解析器 https://github.com/shuxinqin/Chloe/wiki/Method-handler
以上两种方法都可以注入自己的函数解析
