### ISSUE TITLE
执行sql查询的时候有办法获取到DataTable这样的对象吗

### ISSUE THREAD

**Issue by wxk0248** [shuxinqin/Chloe#264]
可能存在多种数据库源的情况下，要读取的表结构又不确定，只能确定表中包含ID，创建时间之类的字段，查询公共方法中是否有能获取类似DataTable这样的对象？

**Comment by shuxinqin** [comment]
https://github.com/shuxinqin/Chloe/wiki/Chloe.Extension

**Comment by wxk0248** [comment]
好的，谢谢！
