### ISSUE TITLE
有没有途径 指定生成SQL的FROM 子句表的别名

### ISSUE THREAD

**Issue by yangzhinong** [shuxinqin/Chloe#265]
文档中没有找到， 比如 context.Query<User>().Where(x=>x.Id==1).FirstOrDefault()；
生成语句是这样：
SELECT "USERS"."ID" AS "ID","USERS"."NAME" AS "NAME","USERS"."GENDER" AS "GENDER","USERS"."AGE" AS "AGE","USERS"."CITYID" AS "CITYID","USERS"."OPTIME" AS "OPTIME" FROM "USERS" "USERS" WHERE ("USERS"."ID" = 1 AND ROWNUM < 2)

**Comment by shuxinqin** [comment]
不明白啥意思

**Comment by yangzhinong** [comment]
就是变成from uese u 呀，在多表连接更是如此，方便调试时阅读生成的sql 语句是否正确。

**Comment by shuxinqin** [comment]
没这个功能，也不打算支持。

**Comment by yangzhinong** [comment]
嗯，这个功能并不是必须的
