### ISSUE TITLE
有没有一个选项， 让生成的SQL,不要带参数，参数值直接写入生成的SQL语句中

### ISSUE THREAD

**Issue by yangzhinong** [shuxinqin/Chloe#266]
如题， 如果没有，能不能增加这个功能？ 其实SQL注入，有经验的人都知道怎么规避。

**Comment by yangzhinong** [comment]
自已花了一上午，跟了很久的代码，发现 在各数据库的 SqlGenerator 中的 public override DbExpression Visit(DbParameterExpression exp) 函数 ， public override DbExpression Visit(DbConstantExpression exp) 和 Utilty/PublicHeper 中 MakeCondition改一下，就可以了。 

我现在写死的， 改成如下了： 
// src/chloe/utity/PublicHelper.cs
 public static DbExpression MakeCondition(PairList<PrimitivePropertyDescriptor, object> propertyValuePairs, DbTable dbTable)
        {
            DbExpression conditionExp = null;
            foreach (var pair in propertyValuePairs)
            {
                PrimitivePropertyDescriptor propertyDescriptor = pair.Item1;
                object val = pair.Item2;

                DbExpression right = null;
                DbExpression left = new DbColumnAccessExpression(dbTable, propertyDescriptor.Column);
                if (Utils.IsToStringableNumericType(propertyDescriptor.PropertyType))
                {
                    right = DbExpression.Constant(val, propertyDescriptor.PropertyType);
                }
                else if (Utils.IsTypeStr(propertyDescriptor.PropertyType))
                {
                    right = DbExpression.Constant(val, PublicConstants.TypeOfString);
                }
                else
                {
                    right = DbExpression.Parameter(val, propertyDescriptor.PropertyType, propertyDescriptor.Column.DbType);
                }
                DbExpression equalExp = new DbEqualExpression(left, right);
                conditionExp = conditionExp.And(equalExp);
            }

            return conditionExp;
        }

----------------
//src/chloe.Oracle/SqlGenerator.cs
     public override DbExpression Visit(DbParameterExpression exp)
        {
            object paramValue = exp.Value;
            Type paramType = exp.Type.GetUnderlyingType();

            if (paramType.IsEnum)
            {
                paramType = Enum.GetUnderlyingType(paramType);
                if (paramValue != null)
                    paramValue = Convert.ChangeType(paramValue, paramType);
            }
            else if (paramType == PublicConstants.TypeOfBoolean)
            {
                paramType = PublicConstants.TypeOfInt32;
                if (paramValue != null)
                {
                    paramValue = (bool)paramValue ? Boxed_1 : Boxed_0;
                }

                if (exp.DbType == null || exp.DbType == DbType.Boolean)
                {
                    exp.DbType = DbType.Int32;
                }
            }

            if (paramValue == null)
                paramValue = DBNull.Value;

            if (paramValue == DBNull.Value)
            {
                this.SqlBuilder.Append("null");
                return exp;
            }
            else if (paramType == PublicConstants.TypeOfBoolean)
            {
                this.SqlBuilder.Append(paramValue);
            }
            else if (Utils.IsToStringableNumericType(paramType))
            {
                this.SqlBuilder.Append(paramValue);
                return exp;
            }
            else if (paramType.IsEnum)
            {
                this.SqlBuilder.Append((int)paramValue);
                return exp;
            }
            else if (paramType == PublicConstants.TypeOfString)
            {
                this.SqlBuilder.Append(SafeSqlStr(paramValue));
                return exp;
            }

            DbParam p = this._parameters.Find(paramValue, paramType, exp.DbType);

            if (p != null)
            {
                this.SqlBuilder.Append(p.Name);
                return exp;
            }

            string paramName = GenParameterName(this._parameters.Count);
            p = DbParam.Create(paramName, paramValue, paramType);

            if (paramValue.GetType() == PublicConstants.TypeOfString)
            {
                if (exp.DbType == DbType.AnsiStringFixedLength || exp.DbType == DbType.StringFixedLength)
                    p.Size = ((string)paramValue).Length;
                else if (((string)paramValue).Length <= 4000)
                    p.Size = 4000;
            }

            if (exp.DbType != null)
                p.DbType = exp.DbType;

            this._parameters.Add(p);
            this.SqlBuilder.Append(paramName);
            return exp;
        }
//常量表达式
public override DbExpression Visit(DbConstantExpression exp)
        {
            if (exp.Value == null || exp.Value == DBNull.Value)
            {
                this.SqlBuilder.Append("NULL");
                return exp;
            }

            var objType = exp.Value.GetType();
            if (objType == PublicConstants.TypeOfBoolean)
            {
                this.SqlBuilder.Append(((bool)exp.Value) ? "1" : "0");
                return exp;
            }
            else if (objType == PublicConstants.TypeOfString)
            {
                this.SqlBuilder.Append(SafeSqlStr(exp.Value));
                //if (string.Empty.Equals(exp.Value))

                //else
                //    this.SqlBuilder.Append("N'", exp.Value, "'");
                return exp;
            }
            else if (objType.IsEnum)
            {
                this.SqlBuilder.Append(Convert.ChangeType(exp.Value, Enum.GetUnderlyingType(objType)).ToString());
                return exp;
            }
            else if (NumericTypes.ContainsKey(exp.Value.GetType()))
            {
                this.SqlBuilder.Append(exp.Value);
                return exp;
            }

            DbParameterExpression p = new DbParameterExpression(exp.Value);
            p.Accept(this);

            return exp;
        }
// 辅助函数
private string SafeSqlStr(object str)
        {
            if (str == null) return "''";
            var s = str.ToString();
            if (string.IsNullOrWhiteSpace(s))
            {
                return $"'{ s}'";
            }
            return $"'{ s.Replace("'", "''")}'";
        }

**Comment by shuxinqin** [comment]
友情提醒：注意安全

**Comment by yangzhinong** [comment]
是的；但这也同时解决了有了oracle  必须按参数顺序的问题。

**Comment by yangzhinong** [comment]
对了. 刚看到大佬提到过 MakeWrapperAccess 这个表达式，它的使用场景是什么？是否提供一个简单的使用示例不？

**Comment by shuxinqin** [comment]
将常量变成变量。因为框架生成sql时不会把常量参数化，所以有些情况需要将常量变成MemberAccess，这样可以参数化。
