### ISSUE TITLE
更新Lambda语法增强

### ISSUE THREAD

**Issue by yangzhinong** [shuxinqin/Chloe#267]
不知道 这样是不是一个好的方案，请大佬看看： 
                var test= new Test() { Pat = "y'zn", Visit = u.Id, Val = 44 };
                context.Update<Test>(
                                x => x.Pat == "yzn" && x.Visit == 1,
                                x => test);  //这里不再需要写成 new Test(){....}

修改文件： \src\Chloe\Core\Visitors\InitMemberExtractor.cs
 public override Dictionary<MemberInfo, Expression> Visit(Expression exp)
        {
            if (exp == null)
                return null;

            switch (exp.NodeType)
            {
                case ExpressionType.Lambda:
                    {
                        LambdaExpression lambdaExp = exp as LambdaExpression;
                        if (lambdaExp.Body is MemberExpression)
                        {
                            Dictionary<MemberInfo, Expression> ret = new Dictionary<MemberInfo, Expression>();
                            var body = lambdaExp.Body as MemberExpression;
                            var obj = lambdaExp.Compile().DynamicInvoke(new object[] { null });
                            foreach (PropertyInfo prop in body.Type.GetProperties())
                            {
                                var v = prop.GetValue(obj, null);
                                ret.Add(prop, ExpressionExtension.MakeWrapperAccess(v, prop.PropertyType));
                            }
                            return ret;
                        }
                        else
                        {
                            return this.VisitLambda((LambdaExpression)exp);
                        }
                    }
                case ExpressionType.MemberInit:
                    return this.VisitMemberInit((MemberInitExpression)exp);

                default:
                    throw new Exception(string.Format("Unhandled expression type: '{0}'", exp.NodeType));
            }
        }

**Comment by yangzhinong** [comment]
刚再次看了大佬的 public override int Update<TEntity>(TEntity entity, string table) 这个， 才发现更新Lambda 更新有很多细节未处理，比如RowVersion字段。

**Comment by shuxinqin** [comment]
是的，根据lambda更新是不会做RowVersion处理。因为框架不知道是要更新一条还是多条数据，没办法设置rowversion新值。

context.Update(
x => x.Pat == "yzn" && x.Visit == 1,
x => test); //这里不再需要写成 new Test(){....} 这种用法可以自行添加个扩展，自行解析一些test和Entity的映射，然后转成 context.Update(
x => x.Pat == "yzn" && x.Visit == 1,
x => new Entity() { Name = test.Name }  );
