### ISSUE TITLE
DotNetCore一些优化建议

### ISSUE THREAD

**Issue by lsd930** [shuxinqin/Chloe#27]
粗略试用了一下，发现还是有些问题，可能是我用的方法不对。
1.优化 增删查改相关参数值参数化，这个很重要，如果没有参数化，程序很容易受SQL注入式攻击
2.新增 打印SQL和参数
3.新增 实体类字段加忽略标识，查表或增改忽略该字段
4.优化 UPDATE时支持LINQ格式: context.Update < Entity > (new { name="xxx",title="xxxx" },p=>p.id==1);

**Comment by shuxinqin** [comment]
1.增删查改都是参数化的，除非在lambda里使用常量
2.如需打印sql或者参数，可以使用拦截器 http://www.52chloe.com/Wiki/Document/3337853076894646272
3.如果一个属性不参与任何映射，可以打上NotMappedAttribute标记
4.UPDATE时支持LINQ格式 http://www.52chloe.com/Wiki/Document/3324837696316112896

**Comment by lsd930** [comment]
谢谢
