### ISSUE TITLE
生成SQL代码优化

### ISSUE THREAD

**Issue by yangzhinong** [shuxinqin/Chloe#272]
花了一天跟代码，总算实现了。
生成SQL结果如图：
![image](https://user-images.githubusercontent.com/21005073/132997164-f3aac0c3-8c33-4c1d-9e83-4dcb5f3d6763.png)

下面是大概的实现。
![image](https://user-images.githubusercontent.com/21005073/132997128-0cf954f2-f2d6-477a-b4b2-69b690930ff2.png)
![image](https://user-images.githubusercontent.com/21005073/132997141-d37d4b16-dc9b-4ba8-a0fc-65f6081d38c1.png)
![image](https://user-images.githubusercontent.com/21005073/132997146-5254dafe-d5fe-4256-9802-e3ddadb7eba0.png)
![image](https://user-images.githubusercontent.com/21005073/132997151-1f4164b0-e22c-45ed-984e-a2af9c0e487c.png)

**Comment by shuxinqin** [comment]
为啥有这样的需求？

**Comment by yangzhinong** [comment]
方便调试，易于阅读。复杂的查询orm 语法更是如此，想知道生成的sql 是否正确。

**Comment by nodyang** [comment]
哈哈 要不赋值真的很麻烦。。这样挺好的

**Comment by yangzhinong** [comment]
今天又花两个小时，把JoinQuery根据连接的Lambda表达式的参数，作为别名. 改好了。
现在这样写： 
![image](https://user-images.githubusercontent.com/21005073/133254034-ba0b464e-4570-4293-8309-341c6503bc17.png)
就能生成下面的SQL语句了。
![image](https://user-images.githubusercontent.com/21005073/133253994-f68be1aa-68cb-4a57-9d17-307b530f8fa6.png)

改动的主要地止是Joinquery`.cs类的构造函数： 
![image](https://user-images.githubusercontent.com/21005073/133254213-93fd3e57-42cd-4619-b034-c4903c0ec31d.png)

**Comment by shuxinqin** [comment]
手动狗头

**Comment by shuxinqin** [comment]
强行使用Lambda表达式的参数作为别名，那么所有的相关参数名必须都一致，还能像下面那样用么？
q.Where(a =>a.xxx..).Where(b => ...) 注意，第一个Where 用的是 a，第二个Where里用的是b

**Comment by yangzhinong** [comment]
我是这样实现的， 如果只有一个表的查询，我用的是as， 如果是多表连接，是在多表的取连接表达式的参数。 
![image](https://user-images.githubusercontent.com/21005073/134484736-a1d023cc-e1de-4889-a340-a4bc10f97282.png)
多表时，如前面的截图所示。 目前使用来看没有什么问题。

**Comment by shuxinqin** [comment]
呃...那还行，你们喜欢就好. 手动狗头
