### ISSUE TITLE
多个HasMany会导致其中一个子表Model数据*2

### ISSUE THREAD

**Issue by jifeilong9** [shuxinqin/Chloe#275]
![image](https://user-images.githubusercontent.com/24316291/135053193-bac648a6-411b-4abd-92ca-b9a514275099.png)
![image](https://user-images.githubusercontent.com/24316291/135053541-53cf962c-f877-4bf8-9468-6fb1559a61fe.png)
如上例子CityTestsList里的数据会重复

**Comment by xjhmii** [comment]
这个BUG修复了么
