### ISSUE TITLE
动态排序代码会报错

### ISSUE THREAD

**Issue by flytom** [shuxinqin/Chloe#276]
那个动态排序
personQuery = personQuery.OrderBy("Age asc,Id desc");/* 传入字符串，多个排序以 ',' 分隔 */ 
这样子写代码会报错，怎么回事呢
报错：无法从用法中推断出方法“IQuery<PlatCustomer>.OrderBy<K>(Expression<Func<PlatCustomer, K>>)”的类型参数。请尝试显式指定类型参数

**Comment by shuxinqin** [comment]
Q: 使用过程遇到问题/异常怎么办？
A: 请查看 ex.Message、ex.StackTrace 以及 ex.InnerException.Message、ex.InnerException.StackTrace 查找关键错误信息，以及仔细查看使用文档。当然你也可以在 github 上提 issue 或者咨询作者，不过寻求帮助时一定要把问题描述清楚，比如用法、框架版本、数据库、错误异常 Message 和 StackTrace 等重要信息，最好能一次性提供（搭配代码、截图更佳），以便对方高效理解和排查问题，节省你我时间。
