### ISSUE TITLE
SqlQueryFmt（仅.NET Core版本支持）：

### ISSUE THREAD

**Issue by 15926391823** [shuxinqin/Chloe#278]
![image](https://user-images.githubusercontent.com/90998099/141064050-34c00bce-58ec-4f27-93fe-6e00df8b1bfc.png)
![image](https://user-images.githubusercontent.com/90998099/141064169-f9738c76-4bf3-431d-af7b-b28cf3fff032.png)
SqlQueryFmt<T>   方法报错，试了好几种都不行，请问下这是官方bug么

**Comment by 15926391823** [comment]
An exception occurred while executing DbCommand. For details please see the inner exception. 42601: syntax error at or near "'@P_0'"   报错是语法错误。

   var table = "Role";
            FormattableString count_sql = $"select count(*) from '{table}' ";

    FormattableString page_sql = @$"select * from  
                                (  select T1.*,ROW_NUMBER() over
                                (  order by '{orderByStr}') rn 
                                    from ( {sql} ) T1 ) T2 
                                    where rn between {(pageIndex - 1) * pageSize + 1} and {pageIndex * pageSize}";


            var totalCount1 = db.SqlQueryFmt<int>(count_sql)?.FirstOrDefault() ?? 0;
            var list1 = db.SqlQueryFmt<TOut>(page_sql).ToList();


这是demo实例，这个应该不是我使用得问题把。郁闷了，弄了好久，一直不行

  var page_sql1 = @"select * from 
                             (
	                             select T1.*,ROW_NUMBER() over(order by '{1}') rn from 
	                             (
		                             {0}
	                             ) T1
                             ) T2
                             where rn between {2} and {3}";

            page_sql1 = string.Format(page_sql1, sql, orderByStr, (pageIndex - 1) * pageSize + 1, pageIndex * pageSize);
            var count_sql1 = string.Format("select count(*) from ({0}) a", sql);


            var totalCount = db.SqlQuery<int>(count_sql1)?.FirstOrDefault() ?? 0;
            var list = db.SqlQuery<TOut>(page_sql1).ToList();

用原生得SqlQuery试没问题得，一样得sql语句

**Comment by shuxinqin** [comment]
SqlQueryFmt 内部会把占位部分变成参数，也就是  '{table}' 变成 ‘@Param’ ...所以你这种情况不适合用 SqlQueryFmt 了...

**Comment by 15926391823** [comment]
那我想问下哈，我们这种情况是不是只能使用dbparam了，有什么其他方法么，我这个需要做分页得，所以无法  写死table

**Comment by shuxinqin** [comment]
反正不能用SqlQueryFmt了。。。
