### ISSUE TITLE
导航属性字段动态排序

### ISSUE THREAD

**Issue by xjhmii** [shuxinqin/Chloe#280]
您好，我在做动态排序的时候有这样的排序需求，需要使用导航属性内的字段进行排序
![1637135076(1)](https://user-images.githubusercontent.com/94520125/142157630-d413b117-49dc-4602-b49d-5aebb49179a5.png)
第一种写死的形式是可以正确排序的，第二种实体本身字段，生成 lamba 方式 也可以排序  但是第三种方式 使用第二种的方式进行导航属性字段排序的时候无法实现，目前框架是否支持导航属性动态排序的功能

**Comment by xjhmii** [comment]
目前我的代码全是封装成模板自动生成的，所以我希望通过实体的配置来完成查询功能内容的编写，示例内的方法的话我需要几乎每个查询方法体都需要手写，工作量会偏大

**Comment by shuxinqin** [comment]
query.OrderBy("Person.Age asc,Person.Id desc"); 这样就是支持导航属性排序了啊

**Comment by xjhmii** [comment]
好的，我试下，感谢

**Comment by shuxinqin** [comment]
最近有点忙，暂时可能抽不出时间来搞。弄好了会在你的issue里说的。

**Comment by shuxinqin** [comment]
多个HasMany会导致其中一个子表Model数据*2 这个问题已修复
