### ISSUE TITLE
多进程如何共享上下文？

### ISSUE THREAD

**Issue by tangming91** [shuxinqin/Chloe#282]
IIS开启多进程后，执行事务报”Current session does not open a transaction“错误。

**Comment by shuxinqin** [comment]
线程安全问题。检查你们的代码吧

**Comment by xkissboss** [comment]
您发给我的信件已经收到。
我会尽快处理，谢谢！

肖振清

**Comment by liuxunbiao** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
谢谢！ 非常感谢。。。
