### ISSUE TITLE
Select(p=>new {})语句中匿名类型如何支持可空类型？

### ISSUE THREAD

**Issue by wxk0248** [shuxinqin/Chloe#283]
`            var askingForLeaveQuery = db.Query<AskingForLeave>().Where(leaveWhere).GroupBy(p => p.JobNum)
                .Select(p => new
                {
                    JobNum = p.JobNum,
                    LeaveAbsence= new decimal?(Sql.Sum(Case.When(p.Type==1).Then(p.Hours).Else(0))),//事假
                    LeaveSick = new decimal?(Sql.Sum(Case.When(p.Type == 2).Then(p.Hours).Else(0))),//病假
                    LeaveAnnual = new decimal?(Sql.Sum(Case.When(p.Type == -6).Then(p.Hours).Else(0))),//年假
                    LeaveMarriage = new decimal?(Sql.Sum(Case.When(p.Type == 7).Then(p.Hours).Else(0))),//婚假
                });`
在使用LeftJoin时，会导致右侧表字段关联后为空的情况，但是Select语句中使用匿名类型无法得出可空类型的结果，尝试了下使用new decimal?或者new Nullable<decimal>的方式，但是报了错误System.NotImplementedException:“new Nullable`1(Sum(When((p.Type == 1)).Then(p.Hours).Else(0)))”
请问这种场景下只能显式声明实体么？是否可以支持匿名类型中的字段可以使用可空类型？在LeftJoin/RightJoin场景中如何把关联后出现的null类型字段设置为该类型的默认值？

**Comment by shuxinqin** [comment]
使用强转
Select(p => new { JobNum =  (decimal?)p.JobNum, LeaveAbsence= (decimal?)(Sql.Sum(Case.When(p.Type==1).Then(p.Hours).Else(0).....

**Comment by wxk0248** [comment]
> 使用强转 Select(p => new { JobNum = (decimal?)p.JobNum, LeaveAbsence= (decimal?)(Sql.Sum(Case.When(p.Type==1).Then(p.Hours).Else(0).....

非常谢谢，测试可用！
