### ISSUE TITLE
对象映射

### ISSUE THREAD

**Issue by LyonJack** [shuxinqin/Chloe#289]
是否可以在属性上添加一种对象映射Attribute，即[ConverterAttribute(Type)],其中Type定义一类IConverter包行Convert和ConvertBack两个方法，以便于将object类型转为一种可存储的数据格式（比如json）

**Comment by shuxinqin** [comment]
对于实体属性必须得是强类型。不打算支持object或者一些比较泛的类型。
当然目前可以注册要映射的类型，参考 https://github.com/shuxinqin/Chloe/blob/master/src/ChloeDemo/String_MappingType.cs
ps：对于json的支持，正在计划中... https://github.com/shuxinqin/Chloe/issues/274

**Comment by LyonJack** [comment]
好的，非常感谢



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年12月31日(星期五) 下午2:13
收件人: "shuxinqin/Chloe";
抄送: "Author";
主题: Re: [shuxinqin/Chloe] 对象映射 (Issue #289)





 
对于实体属性必须得是强类型。不打算支持object或者一些比较泛的类型。
 当然目前可以注册要映射的类型，参考 https://github.com/shuxinqin/Chloe/blob/master/src/ChloeDemo/String_MappingType.cs
 ps：对于json的支持，正在计划中... #274
 
&mdash;
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
