### ISSUE TITLE
关于 2.22.0 版本的建议

### ISSUE THREAD

**Issue by fudiwei** [shuxinqin/Chloe#29]
个人见解，程序本身应该尽可能的向前兼容。

有关 Lambda 中考虑 null 值的问题，应该算做一个 Feature 而非 BugFix，那么不应该是简单粗暴的做破坏性升级（即新旧版本表现不一致）。

往往当使用 a.XName = b.YName 来做联结查询条件的情况，XName 和 YName 在 a、b 中一般都会有索引（实际充当了逻辑外键），且很少需要考虑 IS NULL 的情况，因为往往两边都是非空；而更重要的是，IS NULL 这种情况，是不会命中索引的！

所以我更建议建议把 Sql.Equals 和 Sql.NotEquals 当作该版本新增的 Feature 的实现方法，而不是改变已有的 Lambda ==，这样对以前的代码反而造成了影响。

一家之言，欢迎探讨。

**Comment by shuxinqin** [comment]
有考虑过这个问题，但最后还是选择直接修改==的解析方式
1. 在join on条件上不会出现is null的判断
2. a => a.Name==name/"shuxin" 这种表达式不会出现is null，只有a.Name==a.XName这种的才会出现。
在实际使用过程中我感觉在where条件里使用a.Name==a.XName的情况不会太多(但不排除没有)，所以我感觉问题没想象中的那么大，如果有这样的个别用户，希望升级慎重，也希望理解。
感谢你的建议！

**Comment by CurryHan** [comment]
@shuxinqin  意思是a=>a.Name==null 这种情况会报错吗
