### ISSUE TITLE
搜索表情符号的时候,查询结果不正确.

### ISSUE THREAD

**Issue by qx105b** [shuxinqin/Chloe#290]
表字段里存储这微信群的对话内容, 复制对话内容中的一个表情去搜索,无法搜索出结果.
例如这样的表情☀️, 我实际操作下来发现只要在搜索的时候将表情转化为N'☀️' 这样就可以.
但是我在c#代码里该如何操作呢?

**Comment by shuxinqin** [comment]
Q: 使用过程遇到问题/异常怎么办？

A: 请查看 ex.Message、ex.StackTrace 以及 ex.InnerException.Message、ex.InnerException.StackTrace 查找关键错误信息，以及仔细查看使用文档。当然你也可以在 github 上提 issue 或者咨询作者，不过寻求帮助时一定要把问题描述清楚，比如用法、框架版本、数据库、错误异常 Message 和 StackTrace 等重要信息，最好能一次性提供（搭配代码、截图更佳），以便对方高效理解和排查问题，节省你我时间。
