### ISSUE TITLE
IQuery能否添加一个WhereOr或Or的方法

### ISSUE THREAD

**Issue by haozekang** [shuxinqin/Chloe#291]
我想生成形如如下的SQL语句：
`SELECT * FROM table WHERE (name = 'a' && sex = '1') OR (name LIKE '%b%');`
在代码中，可以如下调用：
`query.Where(x => x.Name == 'a' && sex == '1').WhereOr(x => x.Name.Contains('b'));`

**Comment by shuxinqin** [comment]
如果Where或者WhereOr调用多了，最终谁跟谁是and，谁跟谁又是or关系很乱，最后开发者自己都懵了~所以暂不打算支持。
如果有需要这种or场景，一个是在query.Where(x => (x.Name == 'a' && sex == '1') || x.Name.Contains('b') )就行。我想这种用法是肯定满足不了你的需求。不然你也不会来这问了。所以我建议自行拼接lambda然后传入 Where..
