### ISSUE TITLE
Upate方法更新Postgresql数据库timestamp和timestamptz类型字段存在时区问题

### ISSUE THREAD

**Issue by wxk0248** [shuxinqin/Chloe#292]
操作系统和Postgesql时区一致，都为东8时区
1. 当数据库字段字段类型为timestamp时，调用Update方法更新指定类型字段时，实际更新时间会少8个小时。
`dal.Update(p => p.Id == "1000501064416362496", p => new BoardLane { UpdateTime = DateTime.Now });`
调用`dal.Update(new BoardLane{ Id = "1000501064416362496", UpdateTime = DateTime.Now});`时间更新无误。
2. 当数据库字段类型为timestamptz时，调用Update方法更新指定字段，时间更新无误，但是调用dal.Update(model)更新整个实体时时间会加8个小时。调用`dal.Update(new BoardLane{ Id = "1000501064416362496", UpdateTime = DateTime.Now});`时间会增加8个小时。

**Comment by shuxinqin** [comment]
你描述的问题也不确定是什么原因，但运行本质如下，得你自己根据实际环境分析具体原因了。

使用lambda更新p => new BoardLane { UpdateTime = DateTime.Now } 中的 DateTime.Now 会被翻译成数据库获取时间的函数 NOW() （非utc）。
dal.Update(new BoardLane{ Id = "1000501064416362496", UpdateTime = DateTime.Now}); 中的 DateTime.Now 直接在程序里获取当前时间（非utc）。

ps：对于pgsql数据库，目前还不支持在 lambda 中使用 DateTime.UtcNow，因为之前作者比较水，没找到pgsql获取utc时间的方式~后续会考虑加上支持

**Comment by wxk0248** [comment]
> 

感谢答疑，我使用了拦截器打印出了执行的sql，确实如你所说，在使用lambda表达式时DateTime.Now被翻译成数据库函数 NOW() 。`UPDATE "PM_BoardLane" SET "UpdateTime"=NOW() WHERE "PM_BoardLane"."Id" = N'1000501064416362496'`
数据库字段类型为timestamp，更新时间莫名少了8个小时，但是在数据库中手动执行打印出的sql时间却是正常的。

**Comment by wxk0248** [comment]
经过测试可以通过在链接字符串上增加时区参数解决：
`"User ID=postgres;Password=123;Host=127.0.0.1;Port=5432;Database=Test.DB;Encoding=utf-8;Timezone=Asia/Shanghai"`
但是测试结果挺有意思，不加Timezone参数等效于Timezone=UTC，但是Timezone=UTC+8时间反而比实际时间向前移了16个小时，也就是说是UTC-8等效于Asia/Shanghai，是-8不是+8这个就是挺诡异的
