### ISSUE TITLE
连接查询返回结果的问题

### ISSUE THREAD

**Issue by AHLIRL** [shuxinqin/Chloe#293]
有User表的列 Id,Name,CId,显示字段CName
City表的列 Id,Name, 
有连接查询 var view= db,db.Query<User>().LeftJoin<City>((u,c)=>u.CId==c.Id);
常规的返回结果 User 应该是 view.select((u,c)=>new User{Id=u.Id,CName=c.Name})
现在的需求想实现效果 view.select((u,c)=>{u.CName=c.Name; return u;}) ;
在List集合进行select操作的时候, 接收的参数是Fun<T1,T2>, 可以实现上面的效果, 那么在Chloe里应该怎么实现. Chloe的select的参数是Expresstion<Fun<T1,T2>>

User只有几个属性的时候可以返回 new User(), 当User属性多达几十个的时候, 这么写就非常麻烦了

**Comment by shuxinqin** [comment]
Chloe: 无能为力

**Comment by AHLIRL** [comment]
好吧
