### ISSUE TITLE
没有必要锁定的资源

### ISSUE THREAD

**Issue by MyErpSoft** [shuxinqin/Chloe#3]
在 Chloe/Chloe/Descriptors/PropertyDescriptor.cs 中
资源：this._valueGetter，无论哪个线程创建他，其结果都是相等的，所以我建议无需锁定，而是直接：
if (this._valueGetter == null){
   this._valueGetter = Get....
}

return this._valueGetter;

**Comment by shuxinqin** [comment]
DelegateGenerator.CreateValueGetter(this._propertyInfo);这里面的代码极其消耗性能，所以我能减少执行他就尽量减少。如果不加锁，在多线程同时访问的情况下有可能会出现多次调用，很浪费资源。所以这里我用if (Monitor.TryEnter(this))锁住，这样如果有一个线程在创建valueGetter了，其他线程不用等待，可以去调用this._propertyInfo.GetValue(instance, null);，这样线程不会受到阻塞。
