### ISSUE TITLE
给作者提交一个低级BUG

### ISSUE THREAD

**Issue by haozekang** [shuxinqin/Chloe#306]
此BUG是我们项目偶然间发现的，在调用UpdateOnly时，总是找到父类的一个int属性，但是属性改成int?就可以解决，或者是给父类的这个同名属性换个名字。。。明明已经标记NotMapped了，但还是报错，，，后来发现是这里好像还在调用null对象的属性
![image](https://user-images.githubusercontent.com/10943139/157681313-3e6b44c9-17fd-477b-b9be-af9b0c852b87.png)
![image](https://user-images.githubusercontent.com/10943139/157681809-e977f487-6fb0-4a3b-be0d-a795ed163154.png)

**Comment by shuxinqin** [comment]
呃...........这好像还真挺低级的...
