### ISSUE TITLE
原生sql 数据库可以执行(mysql)

### ISSUE THREAD

**Issue by ImXINCAT** [shuxinqin/Chloe#308]
![image](https://user-images.githubusercontent.com/56582047/161365516-3a59082b-37cb-4e40-a8d6-cce3563f1df7.png)

SELECT
	( @i := @i + 1 ) sort,
	a.ParentId,
	COUNT( a.PlayerId ) AS SumPlayerId,
	COUNT( a.Score >= 20000 OR NULL ) AS ActiveSumPlayerId,
	SUM( a.Score ) AS SumScore 
FROM
	award_statistic a,(
	SELECT
		@i := 0 
	) t 
GROUP BY
	a.ParentId 
HAVING
	COUNT( a.PlayerId ) BETWEEN 1 
	AND 100 
ORDER BY
	SumPlayerId DESC 
	LIMIT 0,
	30

**Comment by ImXINCAT** [comment]
MySqlException: Parameter '@i' must be defined.

**Comment by shuxinqin** [comment]
这个应该是驱动不支持...
我没这么玩过，我也不知道咋整哦~
