### ISSUE TITLE
bool类型的UpdateOnlyAsync，实体类传递True，数据库表为false

### ISSUE THREAD

**Issue by zxingdream** [shuxinqin/Chloe#309]
代码片段为：
![image](https://user-images.githubusercontent.com/12619680/161410143-5409d55b-6799-49f4-a809-b49fb709ce05.png)
数据库表为：
![1648956717(1)](https://user-images.githubusercontent.com/12619680/161410160-2510f48c-47e3-41fa-b6fa-e03f51f26a5c.png)
实体类属性为：
![image](https://user-images.githubusercontent.com/12619680/161410169-20a77183-b2ed-4f9a-b3f6-fa14d9a39bcd.png)

请大佬闲余之时修复此Bug，万分感谢！！！
另附： 用UpdateAnsync则正常，附下图：
![image](https://user-images.githubusercontent.com/12619680/161410209-eea8fcc5-d238-4b69-8481-2353b9f95621.png)

**Comment by zxingdream** [comment]
哦哦对了  数据库是MsSql，
经过跟踪sql语句发现，**代码片段图**执行的sql语句为：
exec sp_executesql N'UPDATE [ms_customer_bind] SET [Bind_IsCall]=@P_0,[Bind_CmpId]=@P_1,[Bind_CmpName]=@P_2,[Bind_CstId]=@P_3,[Bind_CstName]=@P_4 WHERE [ms_customer_bind].[Bind_Id] = @P_5',N'@P_0 bit,@P_1 int,@P_2 nvarchar(4000),@P_3 int,@P_4 nvarchar(4000),@P_5 bigint',@P_0=1,@P_1=21,@P_2=N'山东丽吉康生物科技有限公司',@P_3=76,@P_4=N'张静',@P_5=0

**Comment by shuxinqin** [comment]
so，bug 是什么？看不懂

**Comment by zxingdream** [comment]
BUG是  UpdateOnlyAsync执行更新的时候， 不起作用，bit字段不更新，【图1注释的代码】
换成UpdateAsync则更新成功

**Comment by shuxinqin** [comment]
exec sp_executesql N'UPDATE [ms_customer_bind] SET [Bind_IsCall]=@P_0,[Bind_CmpId]=@P_1,[Bind_CmpName]=@P_2,[Bind_CstId]=@P_3,[Bind_CstName]=@P_4 WHERE [ms_customer_bind].[Bind_Id] = @P_5',N'@P_0 bit,@P_1 int,@P_2 nvarchar(4000),@P_3 int,@P_4 nvarchar(4000),@P_5 bigint',@P_0=1,@P_1=21,@P_2=N'山东丽吉康生物科技有限公司',@P_3=76,@P_4=N'张静',@P_5=0
生成的sql就@P_0=1了，怎么会不更新呢？？

**Comment by zxingdream** [comment]
WHERE [ms_customer_bind].[Bind_Id] = @P_5

**Comment by zxingdream** [comment]
**WHERE [ms_customer_bind].[Bind_Id] = @P_5**，我这才发下 UpdateOnlyAsync这个是根据主键Id 去更新的，sql语句里才发下 这个主键ID,@P_5=0

**Comment by shuxinqin** [comment]
你要给你的实体主键赋值啊，不然读取到的就是默认值 0

**Comment by zxingdream** [comment]
所以 这个更新可以优化下 指定条件去更新，跟UpdateOnly一样
