### ISSUE TITLE
什么时候可以支持批量更新

### ISSUE THREAD

**Issue by zxingdream** [shuxinqin/Chloe#310]
如题

**Comment by shuxinqin** [comment]
批量更新？
是指传入多个实体更新吗？

**Comment by zxingdream** [comment]
对对对，希望能支持类似 UpdateOnly的那种方式，根据实体的属性字段来更新的列
另外就是UpdateOnly希望能支持 自定义where条件去更新

**Comment by shuxinqin** [comment]
1. 传入多个实体更新，这种批量更新目前除了循环挨个更新，没啥好办法~自己写个UpdateRange扩展方法就好。
2. 想自定义条件更新的话直接使用lambda方式更新就行了，我个人觉得已经够用了。
ps：UpdateOnly最终转成调用lambda方式更新dbContext.Update<Person>(a => a.Id == 1, a => new Person()
{
    Name = a.Name,
    Age = a.Age + 1,
    Gender = Gender.Male,
    EditTime = DateTime.Now
});
如果你想UpdateOnly基础上再加上自定义条件，也可以自行参考源码自己扩展个方法就好，我就不提供实现了。
