### ISSUE TITLE
sharding下如果是contains的情况下是否走的equal但是各个表应该是or吧这种情况怎么办

### ISSUE THREAD

**Issue by xuejmnet** [shuxinqin/Chloe#316]
ids.contains(o.id)

**Comment by shuxinqin** [comment]
我是根据遍历ids里每个id，通过ShardingOperator.Equal计算所在的表，然后union结果就是ids所定位到的表集合。
https://github.com/shuxinqin/Chloe/blob/master/src/Chloe/Sharding/Visitors/ShardingTableDiscoverer.cs#L241

**Comment by xuejmnet** [comment]
谢谢学习了
