### ISSUE TITLE
关于Update对象上下文跟踪

### ISSUE THREAD

**Issue by haozekang** [shuxinqin/Chloe#317]
因为项目使用的是MVVM架构，想问一下，可以先：
using (var my = Db.my)
{
    patient = my.QueryByKey<Patient>(key);
    my.TrackEntity(patient);
}
查询到数据，生产对象，然后WPF绑定到前端上，用户编辑完后，单击按钮，执行：
using (var my = Db.my)
{
    my.Update(patient);
}
这样对对象进行更新嘛？

**Comment by shuxinqin** [comment]
TrackEntity 只会作用于调用 TrackEntity 的dbcontext对象上。
