### ISSUE TITLE
关于超时的疑问

### ISSUE THREAD

**Issue by nodyang** [shuxinqin/Chloe#319]
![A~X4 {Z)VN I @5S FT~4I](https://user-images.githubusercontent.com/3090191/172974779-22745e7e-be77-4704-8ce5-dbe4a309d48f.png)

早晨误打误撞  连接了内网的一个数据库链接。网络并不通 但是程序一直么有报错 一直也没有超时
![image](https://user-images.githubusercontent.com/3090191/172975089-90ca615d-e4e9-48b7-94a5-c0f712e9e293.png)

![image](https://user-images.githubusercontent.com/3090191/172975107-b3d50220-3e1a-4b3b-86db-9c39e218c47c.png)

是不是应该报错。或者异常

**Comment by shuxinqin** [comment]
连不上会有报错的，会不会是你项目里把异常吃掉了？再调试下排查原因吧。

**Comment by nodyang** [comment]
![image](https://user-images.githubusercontent.com/3090191/172976881-2d20a990-dd2f-4f16-b780-26d617ad6a41.png)
感觉是我们的网络 有问题。好奇怪。啥反应没有
