### ISSUE TITLE
asp.net core的项目 用注入的方式 怎么可以连接多个库

### ISSUE THREAD

**Issue by zzs89117920** [shuxinqin/Chloe#32]
asp.net core的项目 用注入的方式 怎么可以连接多个库

**Comment by shuxinqin** [comment]
参考 https://mp.weixin.qq.com/s?__biz=MzAwNTMxMzg1MA==&mid=2654069898&idx=1&sn=b531a721928598fd99d119b28c671c59&chksm=80dbc0dfb7ac49c947c7b91a7f213350786b6b0c47e5e9d4b141f18cd4605f6e54d799e05e8c&mpshare=1&scene=23&srcid=0205wyY1oIKTX2vAbo8SbpKO#rd
