### ISSUE TITLE
使用MS 生成DbContext时候报 No provider specified.

### ISSUE THREAD

**Issue by z-jayden** [shuxinqin/Chloe#320]
使用MS 生成DbContext时候报 No provider specified.请问是哪里缺少配置么还是其他问题？

**Comment by shuxinqin** [comment]
使用方法参考：https://github.com/shuxinqin/Chloe/blob/master/src/ChloeDemo/MsSqlDemo.cs#L28

**Comment by z-jayden** [comment]
![image](https://user-images.githubusercontent.com/67751579/173214718-43797baf-a6aa-40cc-84d2-62e85525794c.png)
生成dbcontext的时候 好像会有问题。

**Comment by z-jayden** [comment]
生成DbContext的时候 dbContext.DefaultDbContextProvider threw an exception of type 'System.InvalidOperationException'

**Comment by shuxinqin** [comment]
MsSqlContext dbContext = new MsSqlContext("Data Source = .;Initial Catalog = Chloe;Integrated Security = SSPI;");

**Comment by z-jayden** [comment]
就是这个实例化有问题。 生成的dbContext使用报错

**Comment by z-jayden** [comment]
![微信截图_20220612124142](https://user-images.githubusercontent.com/67751579/173236355-06aa8d6c-0c29-450d-b323-036fd43e523b.png)

**Comment by shuxinqin** [comment]
把相关的nuget包全升级到最新的版本试试。

**Comment by shuxinqin** [comment]
下载源码，运行源码里的demo是没问题的。有问题可能是你的nuget包版本对不上。

**Comment by z-jayden** [comment]
确实是版本问题 非常感谢
