### ISSUE TITLE
跨库查询

### ISSUE THREAD

**Issue by liangfeng-hash** [shuxinqin/Chloe#324]
Chloe支持跨库的连表查询吗

**Comment by shuxinqin** [comment]
不支持哦~

**Comment by shuxinqin** [comment]
跨库查询目前只能手写sql

**Comment by xuejmnet** [comment]
跨库查询的话如果是join需要join的表所有库都在,可以参考ShardingShpere,将字典表用作为广播表（需要作者支持）,广播表的增删改涉及全部的datasource,这样就可以，不然的话跨库如果是同库下的应该是没问题

**Comment by nodyang** [comment]
有跨域的文档不。
