### ISSUE TITLE
可以支持依赖注入吗？如果可以怎么实现

### ISSUE THREAD

**Issue by Sheldon-NULL** [shuxinqin/Chloe#326]

**Comment by shuxinqin** [comment]
public void ConfigureServices(IServiceCollection services)
{
    //...
	
    services.AddScoped<Chloe.IDbContext>((serviceProvider) =>
    {
        return new Chloe.SqlServer.MsSqlContext("Your connection string");
    });
   
    //...
}

**Comment by Sheldon-NULL** [comment]
// Mysql是这样用吗？

public void ConfigureServices(IServiceCollection services)
{
//...

services.AddScoped<Chloe.IDbContext>((serviceProvider) =>
{
   return new Chloe.MySql.MySqlContext(new MySqlConnectionFactory(MySqlSettingConfig.ConnectionString));
});

//...
}

**Comment by shuxinqin** [comment]
每错.

**Comment by Sheldon-NULL** [comment]
有具体的使用Demo吗？

**Comment by shuxinqin** [comment]
这...得你自己去研究依赖注入相关的了啊

**Comment by Sheldon-NULL** [comment]
![image](https://user-images.githubusercontent.com/83170675/184051943-82a82992-3e81-4766-8ed0-0c7585fe1ef1.png)

![image](https://user-images.githubusercontent.com/83170675/184051995-97945ab7-2f8e-4e44-b34a-09993a2e68a5.png)
我尝试的没有得到效果，不知道是不是跟Nuget包有关系，我的版本是3.8.1

出来的是这个报错信息：System.InvalidOperationException: Unable to resolve service for type 'Chloe.MySql.MySqlContext' while attempting to activate......

**Comment by shuxinqin** [comment]
构造函数里应该使用IDbContext
public TestController(IDbContext dbContext)

**Comment by Sheldon-NULL** [comment]
确实是这样的，是我犯了非常愚蠢的错误。非常感谢！
