### ISSUE TITLE
Oracle sql查询 IN参数化查询如何写

### ISSUE THREAD

**Issue by 154681189** [shuxinqin/Chloe#334]
查询的代码
`  string sql = $@"
                select T1.B_MATERIAL_FK,T1.CPZLDJ,T2.TM from PS_WBOUT T1 LEFT OUTER JOIN BUSINESS_CODE T2
                    ON T1.PS_MOUT = T2.BUSINESSKEY_OID
                WHERE T1.DEL = 0 AND T2.BUSI_FLAG='{BarCodeTypeEnum.winding}'  AND T2.TM IN (:Pram) ";
            StringBuilder sb = new StringBuilder();
            if (codeList.Count == 0) {
                ReturnWarn("不存在的条码");
            }
            foreach (var item in codeList)
            {
                sb.Append($"'{item.TM}',");
            }
            string where1 = sb.ToString(0, sb.ToString().Length - 1);
           // sql = sql + "(" + where1 + ")";

            List<QueryPswBOutVo> queryPswBOutList = context.SqlQuery<QueryPswBOutVo>(sql,new DbParam(":Pram", where1)).ToList();`
![image](https://user-images.githubusercontent.com/12993943/185957462-bea1ce8f-cdde-4ef0-9a5e-633b42991798.png)

实际数据库是可以的
![image](https://user-images.githubusercontent.com/12993943/185957534-ea0f4a12-b23b-4ab9-a1b8-e4d5a670a3bd.png)

**Comment by shuxinqin** [comment]
拼sql的话，也要拼一个List<DbParam>
