### ISSUE TITLE
貌似在第一次查询的时候会很慢，后面查询就会快起来。有没什么方法可以预热下。

### ISSUE THREAD

**Issue by CHenBuCHen** [shuxinqin/Chloe#336]
貌似在第一次查询的时候会很慢
比如 dbContext.QueryByKey<Person>(1);
第二次再调用这个方法会快很多。
再比如 一个复杂的查询、连接查询。第一次调用的使用会花费数百毫秒。
第二次调用才几十毫秒。
有没什么办法预热下，让第一次调用的时候就快一些。

**Comment by shuxinqin** [comment]
c#以及数据库机制所致。第一次调用一般都是会慢。怎么让第一次调用快一些，我也不懂了- -
