### ISSUE TITLE
支持动态OR查询吗？

### ISSUE THREAD

**Issue by mengchaoxiong** [shuxinqin/Chloe#339]
比如拼接多个OR条件。
举个隔壁ORM的例子：
var exp= Expressionable.Create<Student>();
exp.OrIF(条件,it=>it.Id==1);//.OrIf 是条件成立才会拼接OR
exp.Or(it =>it.Name.Contains("jack"));//拼接OR
var list=db.Queryable<Student>().Where(exp.ToExpression()).ToList();

这种的

**Comment by shuxinqin** [comment]
框架没提供构造表达式树的相关类，得自己写哦~
在框架外自行拼接好表达式树传进Where就行。
