### ISSUE TITLE
是否支持根据实体模型生成 sql 并自动创建表

### ISSUE THREAD

**Issue by b1acksoil** [shuxinqin/Chloe#340]
例如有一个实体类：

```csharp
[Table("persons")]
public class Person
{
    [Column("id", IsPrimary = true)]
    [AutoIncrement]
    public int Id { get; set; }

    [Column("name")]
    public string Name { get; set; }

    [Column("age")]
    public int Age { get; set; }
}
```

能否支持使用类似 `IDbContext.CreateTable<Person>()` 的方式自动生成sql并在数据库中创建/更新该表，这样可以减少很多麻烦，并且可以避免硬编码大串sql，但是目前没有找到相关的方法

**Comment by shuxinqin** [comment]
https://github.com/shuxinqin/Chloe/blob/master/src/ChloeDemo/MsSqlDemo.cs#L35
new SqlServerTableGenerator(this.DbContext).CreateTables(TableCreateMode.CreateNew); 支持简单的生成表，生成表类型可能不是理想的，可能还得手动编辑下表结构。ps：不建议用于生产环境。

**Comment by b1acksoil** [comment]
试了一下 `SQLiteTableGenerator`，目前没有什么问题，感谢解答
