### ISSUE TITLE
根据条件批量更新

### ISSUE THREAD

**Issue by SC20121109** [shuxinqin/Chloe#352]
//这种批量更新只能写脚本吗
BomBaseContext.Session.ExecuteNonQuery("UPDATE Product_Stock SET Qty=0 WHERE  EXISTS(SELECT * FROM Product Pro WHERE UpdateDateTime<=@dt AND Pro.Id=ProductId)", new List<DbParam>() { new DbParam("@dt", updateDt) });

//下面这种没实现
await BomBaseContext.UpdateAsync<Product_Stock>(sto => BomBaseContext.Query<Product>().Any(pro => pro.Id == sto.ProductId && pro.UpdateDateTime < updateDt), sto => new Product_Stock() { Qty = 0 });

**Comment by shuxinqin** [comment]
呃，是的，上面这种语句不支持
