### ISSUE TITLE
希望能单独出个分表的demo

### ISSUE THREAD

**Issue by xj728** [shuxinqin/Chloe#354]
希望能单独出个分表的demo

**Comment by shuxinqin** [comment]
只分表的话其实简化版的分库分表（只有一个库），你理解 demo 里的 route 怎么编写的就知道怎么弄了，关键注释都有 https://github.com/shuxinqin/Chloe/blob/master/src/ChloeDemo/Sharding/OrderShardingRoute.cs

**Comment by xj728** [comment]
用了很多年这个插件，唯独这个分表的看不懂
能写一个简单的按CreateTime 的Year分表的demo吗？ 全部揉在一起，真的很难看懂
