### ISSUE TITLE
执行Query<T>()的时候发生未将对象引用的对象实例的异常

### ISSUE THREAD

**Issue by AHLIRL** [shuxinqin/Chloe#355]
代码:
 using (MsSqlContext db = GetContext())
                {
                    db.Session.CommandTimeout = 600;
                        var d = db.Query < T > ().ToList();
                        return d;
                }
db对象不是Null
异常信息:
   在 System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.Open()
   在 System.Data.AdoExtension.<Open>d__0.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Chloe.Data.AdoSession.<Activate>d__36.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Chloe.Data.AdoSession.<ExecuteReader>d__45.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Chloe.Data.AdoSession.ExecuteReader(String cmdText, DbParam[] parameters, CommandType cmdType, CommandBehavior behavior)
   在 Chloe.Data.AdoSession.ExecuteReader(String cmdText, DbParam[] parameters, CommandType cmdType)
   在 Chloe.Core.DbSession.ExecuteReader(String cmdText, CommandType cmdType, DbParam[] parameters)
   在 Chloe.Query.Internals.InternalQuery`1.<<GetEnumerator>b__3_0>d.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Chloe.Query.Internals.QueryEnumerator`1.<MoveNext>d__14.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Chloe.Query.Internals.QueryEnumerator`1.MoveNext()
   在 System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   在 System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   在 Chloe.Query.Query`1.ToList()

**Comment by shuxinqin** [comment]
升级最新版本呢？

**Comment by AHLIRL** [comment]
最新没试过, 我用的版本是5.1.1, 服务器上不想随便更新

**Comment by shuxinqin** [comment]
根据提供的异常看不出问题在哪哦~
