### ISSUE TITLE
两个表左关联的时候，两个表有相同字段，最终分页导致字段排序不明确 如何处理？

### ISSUE THREAD

**Issue by Eddy-Q** [shuxinqin/Chloe#356]
这是我的代码
![image](https://user-images.githubusercontent.com/45350458/224951684-e05df6f6-a84b-4d05-9eb6-a949a0e0ab37.png)

最终生成的sql 为 takepage ，我不理解根据什么
![image](https://user-images.githubusercontent.com/45350458/224951904-a808b901-a12a-488d-bbd4-0c4a5fa8dbed.png)
我尝试过  ：
1.给CUSTOMERNAME取别名，但是分页生成的sql 会带进去 导致sql报错 “列不存在”
生成sql效果
![image](https://user-images.githubusercontent.com/45350458/224957045-7aca18fb-2772-4fa7-b3aa-7cb99df68d4a.png)
2.也尝试过orderBy(“W_FEE_CUSTOMER.CUSTOMERNAME”) 代码会直接报错
![image](https://user-images.githubusercontent.com/45350458/224958343-d9a35e38-a6c1-4b08-8c2b-5bec2fb4c3ce.png)

**Comment by shuxinqin** [comment]
用法代码贴全来看看

**Comment by Eddy-Q** [comment]
作者你好， 这是我全部的代码
![1678843934048](https://user-images.githubusercontent.com/45350458/225181073-b0b37c30-3ffd-435d-a279-c0ca3e5156fa.jpg)
如果不加别名 就是我上面提示 列不明确。
这是在orderby 里面加别名的情况
![image](https://user-images.githubusercontent.com/45350458/225180980-9aa5dd86-4a8c-4b33-9b8a-d7ce40538ffa.png)

**Comment by shuxinqin** [comment]
Chloe 什么版本？我这重现不了你的问题

**Comment by Eddy-Q** [comment]
> Chloe 什么版本？我这重现不了你的问题
5.1.1 
![image](https://user-images.githubusercontent.com/45350458/225208900-3944f998-8ae2-4d9a-aa4a-98f4cffc836f.png)

**Comment by shuxinqin** [comment]
不懂了，你试着把Chloe.dll和Chloe.SqlServer升级成最新版看看吧~
ps：你们用的是否是nuget的版本？有没有对源代码改动过？

**Comment by Eddy-Q** [comment]
> 不懂了，你试着把Chloe.dll和Chloe.SqlServer以及Chloe.Extension都升级成最新版看看吧~ ps：你们用的是否是nuget的版本？有没有对源代码改动过？

好的 谢谢大大， 我试试看 其他办法。 
用的不是nuget版本。
