### ISSUE TITLE
ReplaceInto

### ISSUE THREAD

**Issue by MeisterLone** [shuxinqin/Chloe#357]
Hi shuxinqin

Thank you for your work on this project.

I am trying to do InsertRange orm function but I dont want exception on duplicate Primary key. I want to replace exiting record.
I can achieve this normally by using ReplaceInto SQL query. Does Chloe not support range replace?

Thanks!!

**Comment by shuxinqin** [comment]
Yes, Chloe is not support range replace now and i do not know how to implement it so far. - -
