### ISSUE TITLE
GroupBy后如何排序？

### ISSUE THREAD

**Issue by xj728** [shuxinqin/Chloe#359]
![image](https://user-images.githubusercontent.com/948376/226555949-c5e36dcc-7a00-4880-a5d2-b5cf6909860a.png)
提示Num字段错误

**Comment by shuxinqin** [comment]
GroupBy(a => a.Age).OrderByDesc(a => Sql.Count() ).Select。。。

**Comment by xj728** [comment]
还是有问题
![image](https://user-images.githubusercontent.com/948376/226576967-10baf773-c042-4425-a025-b9505f9488b0.png)

![image](https://user-images.githubusercontent.com/948376/226576923-f9d4bf85-403e-491f-82e9-ad8917a065a6.png)

**Comment by shuxinqin** [comment]
Q: 使用过程遇到问题/异常怎么办？

A: 请查看 ex.Message、ex.StackTrace 以及 ex.InnerException.Message、ex.InnerException.StackTrace 查找关键错误信息，以及仔细查看使用文档。当然你也可以在 github 上提 issue 或者咨询作者，不过寻求帮助时一定要把问题描述清楚，比如用法、框架版本、数据库、错误异常 Message 和 StackTrace 等重要信息，最好能一次性提供（搭配代码、截图更佳），以便对方高效理解和排查问题，节省你我时间。

**Comment by shuxinqin** [comment]
var count = dbContext.Query<Person>().GroupBy(a => a.Id).Select(a => new { a.Id, M = Sql.Sum(a.Age) }).Count();
            var result = dbContext.Query<Person>().GroupBy(a => a.Id).OrderByDesc(a => Sql.Sum(a.Age)).Select(a => new { a.Id, M = Sql.Sum(a.Age) }).TakePage(1,20).ToList();

分两次调用吧~求count的时候去掉order by
