### ISSUE TITLE
Select条件在mysql的情况下，怎么也出不来

### ISSUE THREAD

**Issue by lc273734858** [shuxinqin/Chloe#36]
public IEnumerable<TResult> GetListWithoutConn<TResult>(int brandsid)
        {
           return manager.Query<BrandsConnEntity>().Select(p => new { p.ID, p.BrandsID, p.DataBaseName, p.ConnectionType }).Where(p => p.BrandsID == brandsid).ToList<TResult>();
        }

不管是用官网的context.Query<User>().Ignore("Name", "Age").ToList();还是用Select都实验过了，

**Comment by shuxinqin** [comment]
改成 return manager.Query<BrandsConnEntity>().Where(p => p.BrandsID == brandsid).ToList<TResult>();

**Comment by lc273734858** [comment]
那我字段过滤就没用了？我就是要字段过滤，不要所有字段都选出来。

**Comment by shuxinqin** [comment]
context.Query().Ignore("Name", "Age").ToList(); 如果你的实体有 Name age两个字段，不可能还会被select出来的吧
还有，调用Ignore和带泛型的ToList《》方法，调用对象的泛型必须是实体类型

**Comment by lc273734858** [comment]
![image](https://user-images.githubusercontent.com/4981222/41693040-07206b8c-7536-11e8-8837-99575caf1161.png)

![image](https://user-images.githubusercontent.com/4981222/41693025-fd74c47a-7535-11e8-87b6-ca2223b296f0.png)

**Comment by lc273734858** [comment]
![image](https://user-images.githubusercontent.com/4981222/41693121-70ebbc74-7536-11e8-8367-74d9904a375c.png)
这里又是正常工作的...
