### ISSUE TITLE
使用过程出现了ExecuteReader 要求已打开且可用的 Connection。连接的当前状态为打开。

### ISSUE THREAD

**Issue by heyy1028** [shuxinqin/Chloe#361]
您好，使用过程出现了一下异常
ExecuteReader 要求已打开且可用的 Connection。连接的当前状态为打开。
不知道可能是什么原因

**Comment by shuxinqin** [comment]
可能是多线程问题，一个dbcontext不能同时被多个线程操作。你排查下吧

**Comment by heyy1028** [comment]
好的，谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年3月30日(星期四) 中午11:58
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [shuxinqin/Chloe] 使用过程出现了ExecuteReader 要求已打开且可用的 Connection。连接的当前状态为打开。 (Issue #361)





 
可能是多线程问题，一个dbcontext不能同时被多个线程操作。你排查下吧
