### ISSUE TITLE
not in怎么用这个orm实现

### ISSUE THREAD

**Issue by xcl-net** [shuxinqin/Chloe#370]
not in怎么用这个orm实现, 用户表排除一些userid, 这个userid大概有上万条

**Comment by shuxinqin** [comment]
var qq = this.DbContext.Query<City>().Select(c => c.Id);
q.Where(a => !qq.ToList().Contains(a.CityId)    ).ToList();

**Comment by xcl-net** [comment]
System.NotSupportedException
  HResult=0x80131515
  Message=Does not support method 'Queryable.Contains(IQueryable`1 source,Int64 item)'.
  Source=Chloe.MySql
![语法不支持](https://github.com/shuxinqin/Chloe/assets/15728845/7dd19a6d-dc77-44ad-8d47-03a558549971)

查询没有购买订单的用户, 这个动作怎么能直接在数据库完成, 而不是我先通过程序查出来该买订单的用户id集合

**Comment by xcl-net** [comment]
> System.NotSupportedException HResult=0x80131515 Message=Does not support method 'Queryable.Contains(IQueryable`1 source,Int64 item)'. Source=Chloe.MySql ![语法不支持](https://user-images.githubusercontent.com/15728845/274463538-7dd19a6d-dc77-44ad-8d47-03a558549971.jpg)
> 
> 查询没有购买订单的用户, 这个动作怎么能直接在数据库完成, 而不是我先通过程序查出来该买订单的用户id集合

改成右边的就可以, 但是这样把用户id都查询到内存里了, 我想着两个查询在一个sql里完成

**Comment by shuxinqin** [comment]
var orderIdQuery = this.DbContext.Query《Order》().Select(c => c.OrderId);
q.Where(a => !orderIdQuery.ToList().Contains(a.XXXId) ).ToList();

注意，orderIdQuery.ToList() 要写在 Where 方法的 lambda 里

ps：Chloe没有AsQueryable方法
