### ISSUE TITLE
子查询ToList()

### ISSUE THREAD

**Issue by Sheldon-NULL** [shuxinqin/Chloe#372]
什么时候能支持一个子查询ToList(()

![image](https://github.com/shuxinqin/Chloe/assets/83170675/6256a348-ace8-4a08-b8ef-bbfe35ce1d31)

会报不支持的错

**Comment by shuxinqin** [comment]
目前还不支持这种用法，图简单的话可以看下导航属性使用，目前我自己的项目里大量使用导航属性，很方便
https://github.com/shuxinqin/Chloe/wiki/Navigation-query

**Comment by Sheldon-NULL** [comment]
不得不说导航是非常方便的，早就想用的了，只是通过翻demo去找配置方法有点费劲，能不能完善一下文档，贴几个配置的图上去呢

**Comment by Sheldon-NULL** [comment]
不能迅速找到配置方法，是阻碍我使用的最大因素

**Comment by shuxinqin** [comment]
文档用特性配置 https://github.com/shuxinqin/Chloe/wiki/Entity
用fluentmapping配置：https://github.com/shuxinqin/Chloe/wiki/Fluent-mapping
都有啊

**Comment by shuxinqin** [comment]
说实在的，我个人也记不着那些特性，在我自己的项目里不用特性映射，都是用fluent mapping方式配置映射和导航属性
https://github.com/shuxinqin/Chloe/wiki/Fluent-mapping
ps：用fluent mapping的话手动编写映射文件很麻烦，我都是根据自己的开发框架代码结构用代码生成器直接生成实体，映射信息等代码
代码生成器可以参考：https://github.com/shuxinqin/acgen

**Comment by Sheldon-NULL** [comment]
fluentmapping，这玩意手写太麻烦了。代码生成器，对于习惯codefirst的人来说，就有点鸡肋了。还是习惯用特性。 https://github.com/shuxinqin/Chloe/wiki/Entity，这上面的demo太乱了，什么都堆一起，不太好理解。可能你是编写的人，看着没什么。用户角度来说，基本没法在上面找到导航特性配置的正确姿势。建议还是把导航的配置1对1.一对多，多对多，抽出来，单独出demo

**Comment by Sheldon-NULL** [comment]
刚刚把一对多试出来了，不知道是不是我支持不对啊，我是跟 https://github.com/shuxinqin/Chloe/wiki/Entity上面的玩法，大概就是  两边分别加上这两个
  [NavigationAttribute("CityId")]
    public City City { get; set; }

    [NavigationAttribute]
    public List<Person> Persons { get; set; }
，事实是这样玩，会造成序列化的时候反复依赖的报错的。还得加上忽略序列化的那个特性。
这样就不是很方便了，
    [NavigationAttribute（City.CityId）]
    public List<Person> Persons { get; set; }

这种方式会好很多

**Comment by shuxinqin** [comment]
是的，框架会把主对象赋值到子对象相应的属性上，刻意这样设计的，这是框架的一个特性。
ps：我做项目开发时不会把实体对象序列化到前端，而是建另外一个dto的类作为数据传输对象序列化出去。

**Comment by Sheldon-NULL** [comment]
你可不知道，没有标准demo。我很久之前就试过这个玩法了，但是看到这个依赖循环的报错，我就十分怀疑是自己写错了，毕竟看着这样写，也确实明显会出现这种问题，有点不加注释，后面再看，自己都要懵的感觉，然后就没敢继续试下去了。
ps:前台不直接序列化，返回ViewModel很一个很好的规范习惯。但是当做后台的时候，不偷这个懒，我觉得有点对不起自己。

**Comment by shuxinqin** [comment]
循环依赖这个问题之前也有人提过，但我是觉得有循环依赖在编写业务逻辑代码上很是方便，很有必要的一个特性，所以一直坚持这样做没改。不过以后会考虑加个参数或者配置啥的让用户自由选择是否要将主对象赋值到子对象相应的属性上~

**Comment by Sheldon-NULL** [comment]
嗯呢，的确有些场景，确实方便很多。非常同意你说的加配置这个优化，自由选择就好，在不需要的时候，还能简洁一些代码。

**Comment by shuxinqin** [comment]
最新版本已经取消循环依赖了，改成显示调用 IQuery.BindTwoWay() 才会相互绑定引用。
