### ISSUE TITLE
a.Id  

### ISSUE THREAD

**Issue by Daipengfei123** [shuxinqin/Chloe#373]
![1698659626148](https://github.com/shuxinqin/Chloe/assets/23495187/f4524fa9-f90c-4b55-802c-d551e1a0ac67)

System.InvalidOperationException:"a.ld"

a.Id errors often occur, is there something wrong with my usage?

**Comment by shuxinqin** [comment]
用法、相关信息贴全

**Comment by Daipengfei123** [comment]
发现应该是我热修改代码引起的。。
