### ISSUE TITLE
偶发性崩溃

### ISSUE THREAD

**Issue by nodyang** [shuxinqin/Chloe#374]
![00b1fe122eb48c7a97bf1b3c1cf00e1](https://github.com/shuxinqin/Chloe/assets/3090191/25f0b593-165f-4ead-b8d4-5defdd9907c4)
![1699836372181](https://github.com/shuxinqin/Chloe/assets/3090191/ce7510ce-f786-4181-b656-998c8c7a3f0d)
线上突然某一段时间就提示 异常。苦苦找了几天也不好。偶尔就崩溃 提示找不到IsDeleted 数据库一定有这个字段

**Comment by nodyang** [comment]
这个扩展很多地方在用 唯一的区别别的地方没用 
![1699839091487](https://github.com/shuxinqin/Chloe/assets/3090191/b7d237d3-0a44-445b-8737-76b69ee5a715)
锁。研究好几天了。不知道哪有问题。还不是必现。大分部场景是Mq 并发过来的。直接调用都么有问题

**Comment by shuxinqin** [comment]
看不出问题原因，先不调用 FilterDeletedAndDisabled 方法，改成 query.Where(a=>a.IsDelete == false).Where(a=>a.IsEnabled == false) 试试看效果

**Comment by shuxinqin** [comment]
![image](https://github.com/shuxinqin/Chloe/assets/11437679/62520023-2adf-4846-aeee-d089cb260cfc)
确定一下是否就是这个方法引发的异常？

**Comment by nodyang** [comment]
> 看不出问题原因，先不调用 FilterDeletedAndDisabled 方法，改成 query.Where(a=>a.IsDelete == false).Where(a=>a.IsEnabled == false) 试试看效果

目前改成这样了 我在试试。就双11 出现过这样的问题。还是偶发性的。

**Comment by shuxinqin** [comment]
出现那个异常有几种情况：
1 dbContext.Query《Entity》()  Entity有IsDeleted属性，但配置了不映射数据库
2 IsDeleted属性映射了数据库，但使用如 dbContext.Query《Entity》().Select(a=> new Entity { Id = a.Id, Name = a.Name ... } ).Where(a=>a.IsDeleted ==true )  ，其中 Select lamda 里不包含 IsDeleted，后续Where又使用了  IsDeleted 属性也会报错

不过这两种用法的情况都是必现的，不会是偶发性。所以目测我也不好猜哪里的问题- -

**Comment by nodyang** [comment]
> 出现那个异常有几种情况： 1 dbContext.Query《Entity》() Entity有IsDeleted属性，但配置了不映射数据库 2 IsDeleted属性映射了数据库，但使用如 dbContext.Query《Entity》().Select(a=> new Entity { Id = a.Id, Name = a.Name ... } ).Where(a=>a.IsDeleted ==true ) ，其中 Select lamda 里不包含 IsDeleted，后续Where又使用了 IsDeleted 属性也会报错
> 
> 不过这两种用法的情况都是必现的，不会是偶发性。所以目测我也不好猜哪里的问题- -

**Comment by nodyang** [comment]
我是研究了2天。无果才问得。之前都没有问题。最近双11 出现的。 没事我已经改了。双11 也过去了

**Comment by shuxinqin** [comment]
怎么说？还出现这个异常吗？
