### ISSUE TITLE
Could not load file or assembly 'Microsoft.Data.SqlClient

### ISSUE THREAD

**Issue by xj728** [shuxinqin/Chloe#376]
Could not load file or assembly 'Microsoft.Data.SqlClient, Version=5.0.0.0, Culture=neutral, PublicKeyToken=23ec7fc2d6eaa4a5'. 系统找不到指定的文件。

![91e9ea2d03fa9b8b28e3103f6b5bd7d](https://github.com/shuxinqin/Chloe/assets/948376/5e043899-603a-44a0-a789-3d3b832e0d5c)

**Comment by shuxinqin** [comment]
应该是驱动安装问题。查看写nuget包安装情况。
在程序里运行下 SqlConnection conn = new SqlConnection(this._connString);，看能不能运行
