### ISSUE TITLE
是否支持查看执行的sql语句

### ISSUE THREAD

**Issue by IGwen** [shuxinqin/Chloe#378]

**Comment by shuxinqin** [comment]
IQuery.ToString() 能看个大概
或者用拦截器 https://github.com/shuxinqin/Chloe/wiki/Interceptor

**Comment by IGwen** [comment]
IQuery.ToString()能看一些，我在使用PagingAsync的时候看不了。

**Comment by shuxinqin** [comment]
用拦截器吧
