### ISSUE TITLE
mysql 查询报错

### ISSUE THREAD

**Issue by sbeduc163com** [shuxinqin/Chloe#379]
在 MySql.Data.MySqlClient.MySqlConnection.set_Reader(MySqlDataReader value)
   在 MySql.Data.MySqlClient.MySqlDataReader.Close()
   在 Chloe.Data.InternalDataReader.Close()
   在 Chloe.Query.Internals.DataReaderEnumerator.Dispose()
   在 Chloe.Query.Internals.QueryEnumerator`1.Dispose()
   在 System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   在 System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   在 Chloe.Query.Query`1.ToList()

很奇怪  加上筛选条件就会报错

**Comment by sbeduc163com** [comment]
![微信截图_20240111170517](https://github.com/shuxinqin/Chloe/assets/156299767/1536aeca-6ea0-4076-b7f6-dfac0a2ec1f0)
同样的查询  加上这句where就会报错    使用的是Chloe 5.18.0

**Comment by shuxinqin** [comment]
我这复现不了哦~
