### ISSUE TITLE
多表联合查询，能左边表select all吗 类似 sugarsql那样

### ISSUE THREAD

**Issue by neludo** [shuxinqin/Chloe#381]
当左连接 左边表的字段很多的时候，或者需要连续多个表左连接的时候，new 里面的字段写吐了啊

**Comment by shuxinqin** [comment]
Select((a, b) => new { a.Name, B = b } )

**Comment by neludo** [comment]
> Select((a, b) => new { a.Name, B = b } )

谢谢老大 我试试。。感谢感谢，不知道有这个写法。。可能文档没看仔细。。。

**Comment by neludo** [comment]
> Select((a, b) => new { a.Name, B = b } )

这样相当于要定义 一个属性B了，但是我前端需要用到 b里的字段 ，加了B 前端列表展示会有问题，有没有类似这种写法：
            Select((a, b) => new ArticleNewsEntity
            {
                F_Id = a.F_Id.SelectAll(),
                F_CategoryName = b.F_FullName,
            }).MergeTable();

**Comment by shuxinqin** [comment]
F_Id = a.F_Id.SelectAll(), 啥意思不太懂...

**Comment by neludo** [comment]
> SelectAll()

你好 老大，我截个图给你 应该就相当于sql里的 select a.*
[参考链接](https://www.donet5.com/doc/1/1186)
![image](https://github.com/shuxinqin/Chloe/assets/62051644/b8ed184e-5b6d-43ad-8b4a-ef25fc85c58d)

**Comment by shuxinqin** [comment]
看不懂这样用有什么结果- -
这设计让人莫名其妙。。。

**Comment by shuxinqin** [comment]
而且这犯了一个严重的sql基本用法问题，select * 很容易造成性能问题~

**Comment by neludo** [comment]
> 而且这犯了一个严重的sql基本用法问题，select * 很容易造成性能问题~

就是左表的字段不用重复写了。。本来大部分情况就是要全部写的
