### ISSUE TITLE
临时切换ConnectionString

### ISSUE THREAD

**Issue by nodyang** [shuxinqin/Chloe#382]
![image](https://github.com/shuxinqin/Chloe/assets/3090191/5a07bfc6-3798-405f-8f71-2f764856353b)
我想动态的切换ConnectionString 我这样切 还是用以前的链接。
我们是一个用户一个库 不想创建好多的 MsSqlContext 有好的方案不

**Comment by shuxinqin** [comment]
试试 DbContext.Session.CurrentConnection.ConnectionString = "...";
如果不行，那只能创建新的 DbContext 了。

**Comment by shuxinqin** [comment]
ps：建议创建新的 DbContext，不然切换后用完还要切换回去，增加代码复杂度。

**Comment by nodyang** [comment]
3Q
