### ISSUE TITLE
PgSqlContext 更新实体对象timestamp列异常问题

### ISSUE THREAD

**Issue by AHLIRL** [shuxinqin/Chloe#384]
实体类中列UpdateTime在PgSql数据库中的类型是timestamp, 在类中是DateTime
使用 PgSqlContext 的Update(data)方法时发生异常
UpdateTime列 要参与排序的, 也作为时间条件使用.
现在怎么处理程序才不用大改呢
异常信息:
An exception occurred while executing DbCommand. For details please see the inner exception. Cannot write DateTime with Kind=Unspecified to PostgreSQL type 'timestamp with time zone', only UTC is supported. Note that it's not possible to mix DateTimes with different Kinds in an array, range, or multirange.
参数名: value

**Comment by shuxinqin** [comment]
试着设置 UpdateTime=DateTime.UtcNow; 更新看看会不会有问题~
