### ISSUE TITLE
5.18版本在linux系统上连接windows系统的sql server提示当前平台不支持

### ISSUE THREAD

**Issue by sbeduc163com** [shuxinqin/Chloe#386]
Microsoft.Data.SqlClient is not supported on this platform. 这个应该怎么解决？

**Comment by shuxinqin** [comment]
驱动支持的问题。
1. 理论上 Microsoft.Data.SqlClient 没问题，你上网或自己分析下具体原因是什么，试着变更下 Microsoft.Data.SqlClient 版本号试试（nuget 安装指定的版本）...
2. 尝试换个驱动，比如 System.Data.SqlClient ，换驱动后通过构建 dbConnectionFactory 工厂对象创建  MsSqlContext 对象即可，参考构造重载 https://github.com/shuxinqin/Chloe/blob/master/src/Chloe.SqlServer/MsSqlContext.cs#L15

**Comment by shuxinqin** [comment]
https://github.com/dotnet/SqlClient/issues/2030  参考下~

**Comment by shuxinqin** [comment]
https://hatchjs.com/microsoft-data-sqlclient-is-not-supported-on-this-platform/

**Comment by sbeduc163com** [comment]
可能是centos8对.net6支持的不好的原因
