### ISSUE TITLE
异步事务

### ISSUE THREAD

**Issue by Sheldon-NULL** [shuxinqin/Chloe#387]
有异步事务的支持吗，我看文档那里没有。UseTransaction这个API也没有异步版本的

**Comment by Sheldon-NULL** [comment]
哦 不对，好像是UseTransaction这个API直接包含了异步版本了。我看没有UseTransactionAsync还以为没有呢，转到定义才看到

![image](https://github.com/shuxinqin/Chloe/assets/83170675/e3ddb570-23af-4cc1-aac1-af6efff89889)

**Comment by Sheldon-NULL** [comment]
![image](https://github.com/shuxinqin/Chloe/assets/83170675/67410651-0df2-4c8e-9ca0-8d98669b91e1)
 这样写有问题吗

**Comment by shuxinqin** [comment]
可以的，没问题
