### ISSUE TITLE
Include使用的疑问

### ISSUE THREAD

**Issue by AHLIRL** [shuxinqin/Chloe#389]
数据库Sql Server 2008R2
1. 在TakPage方法之后调用Include, 发生异常: Cannot call 'Include' method now. 在TakePage之前调用没问题
2. 在InnerJoin方法之后调用Include, 发生异常: Cannot call 'Include' method now. 不管InnerJoin之后有没有TakePage都会有异常
请问Include的执行逻辑是什么?
按我理解TakePage之后和Join之后已经排除了部分数据, 再关联导航表, 这样需要关联的数据应该更少吧, 系统开销应该也更少才对

**Comment by shuxinqin** [comment]
1. Include目前必须在TakePage之前调用没
2. InnerJoin,LeftJoin等操作不支持Include
3. 开销这块...有道理！

**Comment by AHLIRL** [comment]
补充一个情况, Join不支持, 但是Join之后执行Select方法后就支持了, 在Select方法后执行Include还是发生异常: Cannot call 'Include' method now

**Comment by shuxinqin** [comment]
按我理解TakePage之后和Join之后已经排除了部分数据, 再关联导航表, 这样需要关联的数据应该更少吧, 系统开销应该也更少才对

目前是会先对主表分页后jion的
![image](https://github.com/shuxinqin/Chloe/assets/11437679/69a2093c-0689-406c-889d-39d9f819132f)

**Comment by shuxinqin** [comment]
> 补充一个情况, Join不支持, 但是Join之后执行Select方法后就支持了, 在Select方法后执行Include还是发生异常: Cannot call 'Include' method now

目前显示InnerJoin,LeftJoin不支持Include操作，同时Include后不支持Select操作~

**Comment by AHLIRL** [comment]
说到分页我就想说一下, 我之前都是用的5.1.1版本, 分页还支持选择PagingMode, 现在最新的5.19没这个东西了, 然后我翻了一下更新日志也没见哪个版本更新上说取消了这个, 再有就是 如果都用OFFSET, 那2008的数据库怎么搞, 2008不支持OFFSET的吧

**Comment by shuxinqin** [comment]
PagingMode 移到Options里了。
https://github.com/shuxinqin/Chloe/blob/master/src/Chloe.SqlServer/MsSqlOptions.cs
![image](https://github.com/shuxinqin/Chloe/assets/11437679/c57cdd18-2e13-4960-be68-a836ab7fe800)
