### ISSUE TITLE
Idea: Impliment System.Linq.IQueryProvider

### ISSUE THREAD

**Issue by david-higgins** [shuxinqin/Chloe#39]
I was looking for an orm that could take a `System.Data.IDbConnection`, and create `System.Linq.IQueryable` objects.  This lib comes so close!

It's for users of the library I'm working on which accept the linq IQueryable.

Any plans to add a IQueryable wrapper that maps to your LINQ-like IQuery interface?

**Comment by shuxinqin** [comment]
Oh, sorry. I have no plans to support IQueryable for the time being.

**Comment by david-higgins** [comment]
No problem, It's still a great library and you should be proud! 👍 EF is so heavy!
