### ISSUE TITLE
InsertRangeAsync 实际也就300多

### ISSUE THREAD

**Issue by nodyang** [shuxinqin/Chloe#392]
The incoming request has too many parameters. The server supports a maximum of 2100 parameters. Reduce the number of parameters and resend the request.

**Comment by nodyang** [comment]
这个在5.1 版本是么有问题的。

**Comment by nodyang** [comment]
/// <summary>执行 InsertRange 插入数据时，默认分批插入的数据条数</summary>
    public int DefaultInsertCountPerBatchForInsertRange { get; set; } = 10000; 会不会跟这个有关系

**Comment by nodyang** [comment]
public int DefaultInsertCountPerBatchForInsertRange { get; set; } = 100 我改成100好了。

**Comment by shuxinqin** [comment]
SqlServer吗？

**Comment by shuxinqin** [comment]
复现了，你先用之前的版本吧，我更新新版本

**Comment by shuxinqin** [comment]
因为数据库有参数个数限制，所报错。更新了一个版本，增加参数限制，升级到v5.24.0就好了。

**Comment by nodyang** [comment]
麻烦了
