### ISSUE TITLE
BulkInsertAsync InsertRand  我怎么选择 根据集合的数量

### ISSUE THREAD

**Issue by nodyang** [shuxinqin/Chloe#393]
BulkInsertAsync InsertRand  我怎么选择 根据集合的数量

**Comment by shuxinqin** [comment]
BulkInsert 是利用 SqlBulkCopy 批量插入数据。插入速度快，性能好，可插入大批量数据
InsertRange生成 insert into TableName(...) values(...),(...)...语句插入，效率一般，只能说比循环插入好一点点吧

**Comment by nodyang** [comment]
ok
