### ISSUE TITLE
更新后。系统报了很多 llethod not found: 'void Chloe. Dboptions. set DefaultInsertCountPerbatchforInsertRange(Int32)’

### ISSUE THREAD

**Issue by nodyang** [shuxinqin/Chloe#394]
method not found: 'void Chloe. Dboptions. set DefaultInsertCountPerbatchforInsertRange(Int32)’

**Comment by nodyang** [comment]
可不可以帮我排查下 怎么原因。没搜索出问题了

**Comment by nodyang** [comment]
![7022eb3a52a10da1f1389668f8525f3](https://github.com/user-attachments/assets/f8034003-5dae-4e81-ba10-f03c0f6602a3)

**Comment by nodyang** [comment]
#[error]ChimsApplication/DB/ChimsCholeDb/BaseCholeDb.cs(30,30): Error CS1061: 'MsSqlOptions' does not contain a definition for 'DefaultBatchSizeForInsertRange' and no accessible extension method 'DefaultBatchSizeForInsertRange' accepting a first argument of type 'MsSqlOptions' could be found (are you missing a using directive or an assembly reference?)

**Comment by nodyang** [comment]
这个是系统日子 跟踪出来的

**Comment by nodyang** [comment]
目前的恢复到5.23 似乎好了

**Comment by shuxinqin** [comment]
Chloe.SqlServer.dll 和 Chloe.Dll 版本对不上
可能是vs缓存原因
1. 清理解决方案
2. 把相关的nuget包都改到最新版本

**Comment by shuxinqin** [comment]
DefaultInsertCountPerbatchforInsertRange 改名了，改成了 DefaultBatchSizeForInsertRange 了

**Comment by nodyang** [comment]
我们昨天发布的时候。更新了到最新的。晚上就崩溃了。半夜起来回滚。我们也找了半天。Chloe.SqlServer.dll 和 Chloe.Dll 一般都是同步去更新的。

**Comment by shuxinqin** [comment]
如果版本对不上，应该编译不通过啊

**Comment by nodyang** [comment]
先这样吧。以后不晚上发布了。折腾了一晚上。白天发。哈哈 麻烦了
