### ISSUE TITLE
支持Find_IN_SET吗？

### ISSUE THREAD

**Issue by Sheldon-NULL** [shuxinqin/Chloe#395]
支持这个函数吗？数据有用逗号分隔的

**Comment by shuxinqin** [comment]
框架自身不支持。得需要自己扩展，扩展方式有两种：
https://github.com/shuxinqin/Chloe/wiki/Custom-function
https://github.com/shuxinqin/Chloe/wiki/Method-handler

**Comment by Sheldon-NULL** [comment]
我使用第二种方法拓展出来了，是否需要把这个代码合并进去，丰富一下。

**Comment by shuxinqin** [comment]
可以啊，提交吧

**Comment by shuxinqin** [comment]
FindInSet是MySql特有的函数，放在Chloe.dll里感觉不大合适，所以我改成放到Chloe.MySql.dll里去了
https://github.com/shuxinqin/Chloe/blob/master/src/Chloe.MySql/MySqlFunctions.cs
注：为了让函数参数使用方式与mysql一致，所以我也调整了下 FindInSet 方法的参数顺序

**Comment by Sheldon-NULL** [comment]
~我放到Chloe里面是因为其他数据库，虽然没有这个函数但是，有其他名称不同的函数或者可能有其他方法可以实现这个功能。
所以把这个FindInSet其实是当做一个跟Contains一样的东西，不同数据库做不同适配这样。
或许我当时就应该起一个更好一点的名字？哈哈哈
这是我当时考虑放哪里的时候查了一下GPT给的答复：

其他数据库系统的类似实现：

PostgreSQL: 你可以用 string_to_array 函数配合 unnest 实现类似的效果。

SQL Server: 可以使用 CHARINDEX 或 STRING_SPLIT 实现类似功能，但没有直接等价的函数。

因此，FIND_IN_SET 是 MySQL 特有的，如果你使用其他数据库，需要找到相应的替代方案。

所以~ 嗯，其实给其他数据库做一下这个功能的适配也未尝不可。

&nbsp;


紫禁城...唯美
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年9月22日(星期天) 晚上11:09
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [shuxinqin/Chloe] 支持Find_IN_SET吗？ (Issue #395)














 
FindInSet是MySql特有的函数，放在Chloe.dll里感觉不大合适，所以我改成放到Chloe.MySql.dll里去了
 https://github.com/shuxinqin/Chloe/blob/master/src/Chloe.MySql/MySqlFunctions.cs
 注：为了让函数参数使用方式与mysql一致，所以我也调整了下 FindInSet 方法的参数顺序

**Comment by shuxinqin** [comment]
嗯，暂时先当特有处理吧
