### ISSUE TITLE
数据库实例对象释放出现异常的问题

### ISSUE THREAD

**Issue by AHLIRL** [shuxinqin/Chloe#398]
代码:
//这里每次调用的时候,  GetContext都会实例化一个新的MsSqlContext实例
                using (MsSqlContext db = GetContext())
                {
                    db.Session.CommandTimeout = 600;
                    if (express != null)
                    {
   行号188                     var d = db.Query<T>().FirstOrDefault(express);
    行号189                    return d;
                    }
                    else
                    {
  行号193                      var d = db.Query<T>().FirstOrDefault();
  行号194                      return d; 
                    }
                }
在执行代码的时候, 会爆异常: 未将对象设置引用到对象的实例
异常是在194行
[NullReferenceException: 未将对象引用设置到对象的实例。]
   Chloe.DbContextButler.Dispose() +100
   Chloe.DbContext.Dispose(Boolean disposing) +10
   Chloe.DbContextBase.Dispose() +29
问题1:
虽然存在多个数据查询(来自Web端), 但每个请求的
MsSqlContext都是新实例, 且调试时候 CurrentConnection 不为null, 为什么释放的时候 会有这个 对象为NULL的异常, 究竟是哪个对象为null, 怎么解决
问题 2: 
表达式 express 不是null,  但是异常出现在194是行, 而不是189行, 实际调试的时候, 异常也确实在194行, 且express不为null , 估计根源还是在问题1
db.Query<T>().Where(表达式) 查询也有这个异常, 
这样的问题出现过很多次了

**Comment by shuxinqin** [comment]
异常堆栈全贴出来看看
