### ISSUE TITLE
mapper 的时候 可以对 类型为 object 字段处理吗？ 

### ISSUE THREAD

**Issue by itlizhi** [shuxinqin/Chloe#40]
比如数据库 是 string，用 object 接收就会报错。

另外数据库 是int，但是数据都是 0/1，用 bool 接收也会报错。

**Comment by shuxinqin** [comment]
1. 不支持 object 接收
2. 如果是sqlserver/pgsql自身有bit/bool类型数据，不要用int表示。若是mysql或者oracle用int是没问题的。
