### ISSUE TITLE
如何实现不定长参数的函数映射？

### ISSUE THREAD

**Issue by softworm** [shuxinqin/Chloe#400]
比如sql中的concat方法，可以支持传入任意多个参数拼接。
``` sql
select concat('a', 'b', a.Id), concat('1', a.Name)
```
如何在函数映射或者自定义方法中实现不定长参数？

``` csharp 
// 是否可以这样声明
public static string PgConcat(params string[] args) { }

// 处理方法如何处理？
public void Process(DbMethodCallExpression exp, SqlGeneratorBase generator)
{
    
}

**Comment by shuxinqin** [comment]
参考：https://github.com/shuxinqin/Chloe/blob/master/src/Chloe.MySql/MethodHandlers/EndsWith_Handler.cs

**Comment by softworm** [comment]
感谢回复。不过EndsWith在调用时只会传入一个参数，因此可以明确取出第一个参数生成sql。

假设concat要拼接的参数个数不确定，可能有两个，也可能有三个甚至更多；同时拼接的参数可以为列、字符串。这时该如何实现？

``` csharp
// DbFunctions.cs
public static string Concat(params string[] strs) 
{
}

// 调用
Db.Query<Foo>().Select(t => DbFunctions.Concat(t.Name, " (", t.Code, ")"))

```

**Comment by shuxinqin** [comment]
params string[] strs  语法糖来的，其实就是一个类型为数组的参数，你用反射看下方法的原型就知道了

**Comment by softworm** [comment]
确实，这也是引起疑问的地方。
``` csharp
public void Process(DbMethodCallExpression exp, SqlGeneratorBase generator)
{
    // exp.Arguments.First() 
        这里会有一个string[]类型的参数，需要遍历元素并转换.
        1. 如果是列访问，即包含"."，则转换为 DbColumnAccessExpression
        2. 如果是普通内容，则转换为 DbParameterExpression
     
      请问这样是否正确，以及是否有相应的转换方法（尤其是DbColumnAccessExpression）？
}
```

**Comment by shuxinqin** [comment]
...省略其他逻辑
//想下面这样就行
foreach(item in  exp.Arguments)
{
 item.Accept(generator);
}

**Comment by shuxinqin** [comment]
https://github.com/shuxinqin/Chloe/blob/master/src/Chloe/RDBMS/MethodHandlers/Contains_HandlerBase.cs#L64
参考上面链接的 64行，想计算 exp.Arguments 第一个参数的值（也就是exp.Arguments.First()）
然后得到的应该是一个 IEnumerable 对象，
然后在参考 https://github.com/shuxinqin/Chloe/blob/master/src/Chloe/RDBMS/MethodHandlers/Contains_HandlerBase.cs#L99 99行根据每个item 实际情况遍历处理

**Comment by softworm** [comment]
感谢，不过测试之后发现了新问题，如下写法会抛出异常：`System.NotImplementedException:“t”`

```
Db.Query<Foo>().Select(t => DbFunctions.PgConcatMulti(t.CreateUser, t.CreateUserName)).ToList();
```

而且异常抛出的时机在执行自定义方法处理器之前，想必是对内容有所要求？
如果将PgConcatMulti参数换成字符串常量，则没有这个问题，求解如何修改？

**Comment by shuxinqin** [comment]
遍历 exp.Arguments 的每个item，你调试一下item是什么类型的对象，然后在做相应的处理，如果是 DbExpression 直接 ((DbExpression)item).Accept(generator); 就行

**Comment by softworm** [comment]
`System.NotImplementedException:“t”`，此异常在方法处理器执行之前就会抛出。还没有机会执行到遍历。 @shuxinqin
