### ISSUE TITLE
咨询一个问题在 9687808 提交内，SUM的返回值都设置成可空，这是因为什么原因呢？

### ISSUE THREAD

**Issue by wolfherder** [shuxinqin/Chloe#402]
咨询一个问题在 9687808 提交内，SUM的返回值都设置成可空，这是因为什么原因呢？

**Comment by shuxinqin** [comment]
不记得了，可能是因为数据库里的sum有可能返回null的缘故吧

**Comment by shuxinqin** [comment]
版本更新记录在 https://github.com/shuxinqin/Chloe/blob/master/%E6%9B%B4%E6%96%B0%E6%97%A5%E5%BF%97.md
具有破坏性更新的目测就 v5.18.0 版本，其他的版本有变更，但应该不影响curd结果~

**Comment by wolfherder** [comment]
版本更新记录看过一遍了，感觉对我这里影响不大，v5.18.0 是如果只是影响导航查询，因该对我项目没有影响，感谢回复。
