### ISSUE TITLE
postgresql查询

### ISSUE THREAD

**Issue by authshuker** [shuxinqin/Chloe#42]
大佬，postgres实体转查询语句的时候，全都小写了。如果数据库字段大小写区分的话（postgres数据库区分大小写），添加特性也没有用，依旧是小写的

**Comment by shuxinqin** [comment]
PostgreSQLContext.ConvertToLowercase = false; 就不会自动全转小写了。
https://github.com/shuxinqin/Chloe/blob/master/src/Chloe.PostgreSQL/PostgreSQLContext.cs#L33
