### ISSUE TITLE
sqlite dbtransaciton

### ISSUE THREAD

**Issue by KINGGUOKUN** [shuxinqin/Chloe#43]
当使用Sqlite驱动时候，发现DbContext.Session.CurrentTransaction返回的事务不是DbTransaction类型的，而且DbContext.Session.CurrentTransaction返回的事务类型是internal类型，外部无法使用。希望能将底层事务类型调整为System.Data通用事务类型，或者最起码，在接口/API层面公布底层Transaction。否则没法和外部SQL操作纳入同一个事务。

**Comment by shuxinqin** [comment]
好的，回头公开底层Transaction

**Comment by shuxinqin** [comment]
已经修改 https://github.com/shuxinqin/Chloe/blob/master/src/Chloe.SQLite/ChloeSQLiteTransaction.cs#L27
