### ISSUE TITLE
更新数据的时候能否增加匿名对象的支持

### ISSUE THREAD

**Issue by loyldg** [shuxinqin/Chloe#46]
更新数据的时候,目前的方式写的代码稍微有点繁琐,
能否增加匿名方法的支持,像下面这样:
`public class TestModel
{
public int Id{get;set;}
public string Name{get;set;}
}`

var m=new TestModel();
m.Name="TestName";
现在的更新方式:
db.Update<TestModel>(p=>p.Id==1,a=>new TestModel{Name=m.Name});
期望支持的方式:
db.Update<TestModel>(p=>p.Id==1,new {m.Name});

**Comment by shuxinqin** [comment]
可以写个扩展方法转成 db.Update(p=>p.Id==1,new {m.Name}); --> db.Update(p=>p.Id==1,a=>new TestModel{Name=m.Name}); 
参考这个扩展 https://github.com/shuxinqin/Chloe/blob/master/src/Chloe.Extension/DbContextExtension.cs#L32

**Comment by rainrcn** [comment]
@loyldg  这种更新的方式我也很喜欢，不过好像没加到Chloe扩展库里？

**Comment by loyldg** [comment]
> 喜欢

嗯,自己加一个扩展方法就可以用了.
