### ISSUE TITLE
关于Context上下文回收问题

### ISSUE THREAD

**Issue by SongWenJie** [shuxinqin/Chloe#47]
Chole文档上说，注意：DbContext 实例非线程安全，不能设置为单例。同时，用完务必要将 DbContext 释放。这里指的是使用using显式释放资源吗？因为项目一般是分为多层，所以可能因为代码原因导致在一次请求中使用了不同的上下文，也就是您所说的DbContext 实例非线程安全。因为会使用unitwork模式来实现事务操作，所以维护上下文也是一项很重要的工作。目前我从网上搜索到的方案一般是：
1.保证线程级别的安全 例如使用HttpContext
2.仓储采用依赖注入模式，并且使用ioc框架，利用其进行生命周期的管理
如果使用这两种方案是不是就意味着不用进行using显式释放了呢？

希望您能帮忙解惑一下，感谢！最后给Chloe点赞，非常喜欢！

**Comment by shuxinqin** [comment]
1. DbContext和DbConnection以及EF的DbContext同样的性质，非线程安全，之前怎么保证DbConnection或EF.DbContext线程安全，就怎么管理 Chloe.DbContext
2. 没错，可以，IOC管理生命周期也是释放DbContext的一种方式。

**Comment by SongWenJie** [comment]
好的 非常感谢
