### ISSUE TITLE
The host  does not support SSL connections.

### ISSUE THREAD

**Issue by male110** [shuxinqin/Chloe#49]
Mysql The host  does not support SSL connections.
server=localhost;port=3306;database=member;user=root;password=123456;SslMode=none;
我已经加了SslMode=none了还是无效；

**Comment by shuxinqin** [comment]
框架对连接字符串不做任何处理或加工，同时框架和数据库驱动解耦的，所以具体原因你网上搜下吧。

**Comment by male110** [comment]
你用什么驱动？

**Comment by shuxinqin** [comment]
MySqlConnector
