### ISSUE TITLE
部分属性定义在父类中，会报错

### ISSUE THREAD

**Issue by fengxuanll** [shuxinqin/Chloe#5]
实体有部分属性是继承自父类的，在查询的时候会报错。
\Chloe\Query\MappingObjectExpression.cs
GetMemberExpression方法，返回了NULL值。

**Comment by shuxinqin** [comment]
目前确实是会有这么个问题。谢谢你的发现。

**Comment by shuxinqin** [comment]
继承支持会对框架有不小的调整，也会对性能有些许影响，得深思熟虑要不要支持。短时间内可能改善不了，非常抱歉。

**Comment by 1002237913** [comment]
有点遗憾啊，哎。就因为这个原因我暂时放弃这个框架了。。

**Comment by shuxinqin** [comment]
感谢关注Chloe。思考了许久，还是决定要支持继承。现在我们内部版本已经可以使用支持继承，下次更新会对外发布该特性。这是我们的内部版本https://github.com/shuxinqin/Chloe/tree/shuxin_dev，欢迎关注。

**Comment by shuxinqin** [comment]
该问题已经在最新版本中修改。非常感谢您的提醒。
