### ISSUE TITLE
字段没有取到值 

### ISSUE THREAD

**Issue by male110** [shuxinqin/Chloe#50]
CREATE TABLE `sms_record` (
	`Send_Time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP COMMENT '发送时间',
	`Create_Time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
	`Sms_Type` TINYINT(4) NULL DEFAULT '1' COMMENT '1 消费 2充值',
	`User_id` INT(11) NULL DEFAULT '0',
	`Store_id` INT(11) NULL DEFAULT '0',
	`Send_Id` VARCHAR(33) NULL DEFAULT NULL,
	PRIMARY KEY (`Id`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=3
;

  `  [Table("sms_record")]
    public class SmsRecord
    {
        public SmsRecord()
        {
        }
        [Column("Send_Time")]
        public DateTime SendTime { get; set; }
        [Column("Create_Time")]
        public DateTime CreateTime { get; set; }
        [Column("Sms_Type")]
        public int SmsType { get; set; }
        [Column("User_id")]
        public int UserId { get; set; }
        [Column("Store_id")]
        public int StoreId { get; set; }
    }`

public List<SmsRecord> GetUnSend(int pageSize)
{
            var sql = "select * from sms_record where State=0 order by Id asc limit 0," + pageSize;
            return this._context.SqlQuery<SmsRecord>(sql).ToList();
}
Send_Time, Create_Time这些带下划线的字段，没有值，不知道哪儿里错了？

**Comment by shuxinqin** [comment]
Column这个特性不作用于 SqlQuery 方法

**Comment by shuxinqin** [comment]
不是bug，是设计如此。

**Comment by male110** [comment]
只能说，无法使用

**Comment by male110** [comment]
IQuery<User> q = context.Query<User>();

q.Where(a => a.Id == 1).FirstOrDefault();
如果是用这种模式支持吗？
还是用你的吧，必竟都是中国人

**Comment by male110** [comment]
你应该引导我用另外一种可以用的方式，不能简单的回答不能用，这是技巧问题好吧。
