### ISSUE TITLE
给伟大开发者的建议

### ISSUE THREAD

**Issue by DingTaiKeji** [shuxinqin/Chloe#51]
以下是本人的一点小小建议，如若有理希望伟大的开发者采纳
Where可否支持如下
`IQuery<User> q = context.Query<User>();`
`Where<User> where = new Where<User>();`
`where.And(a=>a.name == "zhangsan");`
`where.Or(a=>a.name == "lisi");`
`var users = q. Where(where).ToList();`

另外比如数据库的主键Guid类型的，插入的时候是数据库默认的，但是在代码里面Insert的时候主键不赋值就会报错，有没有办法解决呢

**Comment by shuxinqin** [comment]
Where<User> where = new Where<User>(); 这种用法自行扩展就可以了，拼好表达式树传给IQuery.Where就行。暂不打算集成在框架中
目前框架不支持数据库默认值（暂也没支持的计划）。

**Comment by DingTaiKeji** [comment]
好吧，只是表达式树操作有点抽象不好理解
