### ISSUE TITLE
连接查询select如何返回指定类型

### ISSUE THREAD

**Issue by OsricX** [shuxinqin/Chloe#52]
实体类 InvClass 主键 InvCCode；Inventory 主键 InvCode 外键 InvCCode，
Inventory 有类型为 InvClass 的属性。

定义Inventory 左连接 InvClass查询
var joiningQuery = context.Query<Inventory>().LeftJoin<InvClass>((inventory, invclass) => inventory.InvCCode == class.InvCCode);

连接查询对象Select得到匿名类型
var query = joiningQuery.Select((inventory, invclass) => new {Inventory = inventory, invClass = invclass});

Select 返回指定类型
var result = query.Select(a=>new Inventory{ InvCode = a.Inventory.InvCode, ... ... InvClass = a.invClass});

此处，返回指定类型时，能不能返回Inventory，并且对 Inventory.InvClass 进行赋值， 不需要对其中大量的属性在新建对象中一个一个赋值

另，QQ群满了，什么时候考虑开个新群啊

**Comment by shuxinqin** [comment]
var result = query.Select(a=> a.Inventory); 就行

**Comment by OsricX** [comment]
这里需要先对Inventory.InvClass赋值，然后再得到a.Inventory。请问怎么处理呢
