### ISSUE TITLE
不支持ParameterDirection.ReturnValue？如何调用自定义函数？

### ISSUE THREAD

**Issue by lake2** [shuxinqin/Chloe#53]
RT

**Comment by shuxinqin** [comment]
用户自定义函数 http://www.52chloe.com/Wiki/Document/1010894292295749632

**Comment by lake2** [comment]
额。没太看明白。
我的意思是比如我有一个自定义函数Fx（@a VARCHAR(20),@b int）,如何传入参数获得返回值呢，只能用context.SqlQuery<decimal>("select dbo.Fx(@a,@b)",x,x)吗

**Comment by shuxinqin** [comment]
嗯，是的

**Comment by lake2** [comment]
谢谢
