### ISSUE TITLE
如何批量更新数据？

### ISSUE THREAD

**Issue by male110** [shuxinqin/Chloe#54]
如果我有一千条，如何批量更新？

**Comment by shuxinqin** [comment]
不支持批量更新哦

**Comment by male110** [comment]
建义支持一下。
如果我一万条，一条条更新，要连接一万次，时间花在了TCP连接上。
如果我可以批量更新，减少连接次数，那性能上提升是十分可观的。
所以在很多时候是需要批量提交更新的。这个真的很有用。

**Comment by male110** [comment]
而且你的SQL只有SqlQuery没有NoneQuery

**Comment by shuxinqin** [comment]
有的。DbContext.Session

**Comment by rickxie** [comment]
这个应该可以支持一下吧，但批量也有最大数量限制的
