### ISSUE TITLE
作者大大有没有计划添加UpdateOrInsert操作,或者叫Upsert操作?

### ISSUE THREAD

**Issue by crystalsis** [shuxinqin/Chloe#56]
我现在遇到这种操作的时候是先单条update,然后如果0行受影响就insert,不过框架内应该是可以判断主键那个值有没有赋值的吧,如果主键没赋值或者是初始值直接insert节省一步操作,而且像SQL Server和Oracle还有MERGE语句貌似更快

**Comment by shuxinqin** [comment]
1. 在框架外也可以判断主键那个值有没有赋值，如果有必要自己写个扩展也是可以的。暂还未考虑集成进框架内
2. SQL Server和Oracle的MERGE语句回头考虑下，是否可以集成进框架。
