### ISSUE TITLE
请问是否支持where动态拼接or

### ISSUE THREAD

**Issue by coolzymzm** [shuxinqin/Chloe#58]
比如： query = query.Where(a => cityCodes.Contains(a.CityCode) || (a.CityCode == null && a.TaskAddress.Contains(search.cityName)));

假如a.TaskAddress.Contains(search.cityName)这段有多个的话，该怎么写

**Comment by rickxie** [comment]
请问这个不是数据库like写法吗 为啥不支持

**Comment by shuxinqin** [comment]
看错了- -，支持 a.TaskAddress.Contains 的，最后转成 like 语法..
