### ISSUE TITLE
你好大神，很你喜欢的chloe作品，官方的qq群满了。

### ISSUE THREAD

**Issue by sundayisblue** [shuxinqin/Chloe#59]
你好，首先说声抱歉，我实在没办法，只能在这里留言给你。
我想加入官方的qq群，但是群满了。希望能解决下，或许开个2群，至少我是没在git或官网上看到有2群的消息。
我觉得在qq群里更能更好的沟通和解决问题。

**Comment by sundayisblue** [comment]
你的QQ我也尝试过添加过，但是需要填写验证问题的答案：我不知道你的真实姓名。
我想知道，如果是db first开发模式，有代码生成工具？

**Comment by shuxinqin** [comment]
代码生成工具用网上的就行，根据自己需求改改模版就可以了
