### ISSUE TITLE
[question] 使用context.SqlQuery<T>(sql)查询数据，实体的列名映射不生效？

### ISSUE THREAD

**Issue by hin-longkid** [shuxinqin/Chloe#60]
@shuxinqin 你好，请教一下如何能够使用context.SqlQuery<T>(sql)时候，实体属性的数据库列名映射也生效呢？希望不是在sql把各个字段都as [alias]一遍...
实体定义：
``` cs
[Table("Employee")]
public class User
{
    [Column("DepartmentCode1")]
    public string DepartmentCode { get; set; }
}
```
执行sql：
``` sql
select e.DepartmentCode1 from Employee as e
```
执行代码：
``` cs
var users = _dbContext.SqlQuery<User>(sql);
```
查询数据库：
![image](https://user-images.githubusercontent.com/1326875/46862348-39a64d00-ce47-11e8-920b-eb7e029cac78.png)
代码执行结果：
![image](https://user-images.githubusercontent.com/1326875/46862270-14194380-ce47-11e8-88dd-78f5d152511f.png)

**Comment by shuxinqin** [comment]
呃，Column特性不作用于SqlQuery这个方法哦

**Comment by hin-longkid** [comment]
@shuxinqin 有SqlQuery支持Column特性的计划吗？对比了其他几款轻量级的orm均支持的

**Comment by shuxinqin** [comment]
目前还没哦
