### ISSUE TITLE
请问，怎样才能支持链接数据库

### ISSUE THREAD

**Issue by ThisIsSteinsGate** [shuxinqin/Chloe#64]
因为项目需要
有两个分别部署在不同服务器上的数据库
想要连表查询
一般我是使用了链接数据库实现
使用Chloe的话就没办法了，没法SELECT链接数据库中的内容
ToString查看生成的SQL，是拼接的时候出错了，稍微改一下就能运行的
现在我是使用视图来暂时替代
还是说，这种情况有更好的解决方法？

**Comment by shuxinqin** [comment]
这个真没办法哦

**Comment by ThisIsSteinsGate** [comment]
> 这个真没办法哦

感觉就差一点点
这个是直接在那个数据库执行，生成的SQL
SELECT [OM_MOMain].[MOID] AS [C]
FROM [OM_MOMain] AS [OM_MOMain];
这个是使用链接数据库的
SELECT [OM_MOMain].[MOID] AS [MOID]
FROM [U8Context].[UFDATA_114_2018].[dbo].[OM_MOMain] AS [OM_MOMain];
其实改变就只有FROM的那个表
真的没办法吗

不论如何Chloe都是很棒的

**Comment by rickxie** [comment]
应该不难支持 用tableattribute 不是可以支持吗？

**Comment by ThisIsSteinsGate** [comment]
> 应该不难支持 用tableattribute 不是可以支持吗？

尝试使用过tableattribute ，最后转换出来的SQL无法执行的

**Comment by focus508** [comment]
这已经超出了ORM的范畴，因为联机查询已经含分布式的味道，你需要抽象一个数据中间层，它下边管理着N个数据库， 查询的时候，实际上是针对中间层查询，由中间层负责取实际的底层数据。另一种临时的老旧方案，是将数据做个主从同步，然后就仅需要查询一个数据库了。

**Comment by ThisIsSteinsGate** [comment]
就是因为经常会跨服务器跨库查询
所以才想使用SQL Server的“链接服务器”的特性
这样才能省去同步之类的麻烦，而且也能事实了
使用SQL直接查询时，也和直接操作本地的数据库差不多，只不过要添加一些前缀
但是在Chloe里，生成的sql，会不能执行，因为会缺一些“[”，"]"符号而导致执行时出错
或许可以使用同义词？
