### ISSUE TITLE
我需要一些关于时间的建议

### ISSUE THREAD

**Issue by aefj11** [shuxinqin/Chloe#66]
最近自己练习的东西老是涉及到时间日期，比如我需要今天的数据，或者我需要这个星期的数据，但是不知道该怎么使用框架实现，胡乱测试老是出现错误或者获取不到数据，让我很苦恼，目前就直接使用sql实现，但是我觉得应该有更简单的办法，所以来咨询下您，如果您有更好的建议的话请您告诉我下，非常非常感谢！

**Comment by shuxinqin** [comment]
举个例子

**Comment by aefj11** [comment]
context.SqlQuery<jilu>("select * from jilu where date_format(jilu.shijian,'%Y-%m-%d')='" + DateTime.Now.ToString("yyyy-MM-dd") + "'").ToList();
比如我现在需要当天数据，我应该怎么弄？或者：
context.SqlQuery<jilu>("select * from jilu where date_format(jilu.shijian,'%Y-%m-%d')>='"+dateTimePicker1.Value.ToString("yyyy-MM-dd")+"' and date_format(jilu.shijian,'%Y-%m-%d')<='"+dateTimePicker2.Value.ToString("yyyy-MM-dd") + "'").ToList();
我需要一个起始日期和终止日期之间的数据，我应该怎么处理，非常感谢您！

**Comment by shuxinqin** [comment]
用 jilu.shijian.Date==DateTime.Now.Date 试试

**Comment by aefj11** [comment]
还是不行，我最后把数据的datetime改为了string，还是不可以

**Comment by shuxinqin** [comment]
日期比较 用 用 jilu.shijian.Date==DateTime.Now.Date这种方式可以的啊，我们一直这样用着呢。

**Comment by focus508** [comment]
@shuxinqin 你那是lambda用法，他明显是自己在拼原生sql，还不带参数。。
@aefj11 你把要比较日期设个参数，把用户选择的日期传给参数，就可以了，这样还不会有注入风险。

这个Issue关了吧  没讨论的必要
