### ISSUE TITLE
出现了这个错误，怎么解决呢？

### ISSUE THREAD

**Issue by zhhbo** [shuxinqin/Chloe#67]
{"Please make sure that the member of the column 'Id'(0,int (11),System.Int32) map is the correct type."}
用的是sqlite，4万多条数据，每到最后60条就出现这个问题
改成int也不行

**Comment by shuxinqin** [comment]
能定位是哪条数据的问题么？

**Comment by zhhbo** [comment]
发现问题了，最后只有59行数据，但返回的条数是60，导致take 60 出错

**Comment by shuxinqin** [comment]
为什么take 60 会出错？

**Comment by zhhbo** [comment]
我也想知道

**Comment by focus508** [comment]
看源码，这个错误，一定是Map到对象的时候产生的，代码中获取IDataReader中的数据用的是迭代器，似乎迭代到最后一条的时候，NEXT仍然有效，而实际NEXT已经没有数据了，从错误信息看，取到了Id=0的记录，正常数据库表中Id应该都是从1开始的，Id=0似乎是一条无效的记录，这应该是一条极其隐晦的BUG
@zhhbo 将带表结构的数据传一份上来，标明一下sqlite版本，就好定位错误了

**Comment by shuxinqin** [comment]
如果表有10条数据，take(11)会不会出错？ @zhhbo

**Comment by zhhbo** [comment]
没有测试

**Comment by shuxinqin** [comment]
麻烦提供更加详细的描述或者提供一个demo啥的可以让我复现问题，这样我才能定位问题在哪
