### ISSUE TITLE
需要执行一个字符串大小与的比对该怎么办？

### ISSUE THREAD

**Issue by aefj11** [shuxinqin/Chloe#69]
需要执行一个sql语句为
SELECT * FROM instock WHERE (`start` <= 'w00000' and `stop` >= 'w00000') OR (`start` <= 'w00012' and `stop` >= 'w00012') or (`start` >= 'w00000' and `stop` <= 'w00012')
写的时候发现不允许进行string类型的大小于比对，现在用拼接，没想到怎么解决，如果您能解决的话非常感谢

用了这么长时间，感觉非常顺手，就是QQ群满了，碰到问题时只能在这里提问，不能很快的拿到答案感到非常沮丧，如果有可能的话希望还有群可以加入，非常感谢！

**Comment by shuxinqin** [comment]
lambda表达式里目前是不能支持字符串的大小于对比哦。
这个大小于对比问题你已经是第N个提出的了，看来的考虑支持了- -

**Comment by aefj11** [comment]
知道自己写的没错误就很高兴了，谢谢了

**Comment by ThisIsSteinsGate** [comment]
String.CompareTo()
这种Lambda不支持吗

**Comment by shuxinqin** [comment]
接下来会发布一个版本，支持字符串大小对比的方法。https://github.com/shuxinqin/Chloe/blob/shuxin_dev/src/Chloe/Sql.cs#L40
