### ISSUE TITLE
请问那个实体跟踪TrackingEntityContainer会不会很占内存呢？

### ISSUE THREAD

**Issue by linhongping** [shuxinqin/Chloe#70]
请问那个实体跟踪TrackingEntityContainer会不会很占内存呢？项目中用到这个框架，结果里面有个Chloe.Core.EntityState占了600多M多内存空间
![image](https://user-images.githubusercontent.com/33215426/49777160-3b529b00-fd3a-11e8-9754-b93e88a96572.png)

**Comment by shuxinqin** [comment]
这个对象是要保存实体的每个属性值，会占用不少空间。如果查询一个实体对象出来占1kb内存资源，那么track后至少要占2kb+，简单的可以认为track 后多出了一个实体的copy。因此，如果只查不更新的话，最好不要track。
