### ISSUE TITLE
ORACLE 生成的SQL 异常

### ISSUE THREAD

**Issue by kakapo99** [shuxinqin/Chloe#71]
ORACLE 生成的SQL 在FROM后会生成两次表明 类似 SELECT * FROM TABLEA TABLEA WHERE A = '0'; ，并且 ORACLE11G中不支持SQL参数含有双引号。

**Comment by shuxinqin** [comment]
后面的是表别名。
在lambda中使用常量是不会参数化的，如需参数化请用变量。
