### ISSUE TITLE
关于跨库事物的建议

### ISSUE THREAD

**Issue by 2821840032** [shuxinqin/Chloe#72]
非常喜欢Chloe 简单，方便，易管理，对项目没有侵入性，关注很久了。
最近在研究微服务 ，涉及到跨库事物。
有看到CAP ，用起来还是不太顺手。
不知道作者有没有想把CAP和Chloe结合做成 支持分布式的ORM呢？
据我了解还没有一款支持分布式的ORM @shuxinqin

**Comment by shuxinqin** [comment]
CAP和Chloe结合做成 支持分布式这个想法目前还不知道可行性如何，有待调研与思考……

**Comment by 2821840032** [comment]
我觉得可行性很高，看好Chloe哦。
