### ISSUE TITLE
数据库与实体类型不一致时出错

### ISSUE THREAD

**Issue by ArgoZhang** [shuxinqin/Chloe#73]
由于项目需求要求通过配置能够从SQLServer切换到SQLite或者MySQL或者MongoDB，所以不同数据库主键ID是不一样的（各个库数据不一样），SQLServer数据库主键都是ID类型为int自增长，MongoDB主键为GUID所以业务实体类主键定义为string类型以便适应所有类型数据库。问题如下：
db.Query<T>("tableName").ToList();
上面语句可以调整表名称与业务实体类名称不一致的问题，但是由于数据库类型为int，实体类属性类型为string，所以报错。
dapper/sqlSugar都不报错，请问这个怎么设置或者更改能够达到需要的效果呢？

**Comment by shuxinqin** [comment]
在数据类型这块Chloe要求稍微严谨点，数据库是int类型，属性就必须得是int类型。

**Comment by ArgoZhang** [comment]
> 在数据类型这块Chloe要求稍微严谨点，数据库是int类型，属性就必须得是int类型。

这样就很难满足要求了，谢谢啦，我再看看别的脚手架

**Comment by shuxinqin** [comment]
当然，Chloe也保留了扩展接口支持类型转换，参考：
https://github.com/shuxinqin/Chloe/blob/master/src/ChloeDemo/Program.cs#L19
https://github.com/shuxinqin/Chloe/blob/master/src/ChloeDemo/String_MappingType.cs
重写IMappingType.ReadFromDataReader 方法，在里面做数据类型转换即可。

**Comment by ArgoZhang** [comment]
这就太好了，直接给我这个例子就方便多了，PetaPoco也是这个思路，有一个全局的Mapper可以注册，你的这个架构我还是很喜欢的，不同的数据库不同的dll这样很干净，不像SqlSugar把所有5个数据库依赖的dll全部都引用进项目
