### ISSUE TITLE
追加判断语法

### ISSUE THREAD

**Issue by 2821840032** [shuxinqin/Chloe#75]
![a](https://user-images.githubusercontent.com/29800454/51227128-dec44a80-198d-11e9-80d6-d3984f369bbd.png)
我感觉这种写法非常好用，希望chloe能够加上
能够追加where语句 最后在ToList()

**Comment by 2821840032** [comment]
![a](https://user-images.githubusercontent.com/29800454/51229581-dd981b00-1997-11e9-9966-9efc4f06cd11.png)

我用委托把操作存储起来，最后在进行Tolist 
结果是可行的。
listResult结果是没有进行where查询
funcList结果是进行了where查询

**Comment by 2821840032** [comment]
@shuxinqin 
我不知道有没有这种的写法，
不过写出来的感觉好爽啊

**Comment by 2821840032** [comment]
它只执行了第二个函数的条件语句，可能是把第一个覆盖了。

**Comment by shuxinqin** [comment]
rows = rows.Where()。。。
rows = rows.Where()。。。

**Comment by 2821840032** [comment]
可以吗？原来是赋值操作啊，我试试。这点我没有在文档里看到。没有注意观察，失误-_-!!

**Comment by 2821840032** [comment]
可行的，太感谢了。
