### ISSUE TITLE
Connection must be valid and open.

### ISSUE THREAD

**Issue by shizhengzl** [shuxinqin/Chloe#81]
我前端里有2个异步请求，结构输出异常 Connection must be valid and open.
环境是netcore  加载时注入
   services.AddScoped<Chloe.IDbContext>((serviceProvider) =>
            {
                return new Chloe.MySql.MySqlContext(new MySqlConnectionFactory(Configuration.GetConnectionString("mysql")));
            });

下面是Conntrol 
  private readonly IDbContext _mySqlContext;
        public PermissionStore(IDbContext mySqlContext)
        {
            _mySqlContext = mySqlContext;
        }
 我改怎么办？

**Comment by shuxinqin** [comment]
1. 可能是多线程同时操作了同一个DbContext对象导致，IDbContext是非线程安全对象，异步下使用要注意！！
2. 可能是异步代码里有可能使用了已经被销毁的DbContext对象。
