### ISSUE TITLE
项目下载之后无法使用vs2015打开

### ISSUE THREAD

**Issue by zhejiang10086** [shuxinqin/Chloe#85]
项目下载之后无法使用vs2015打开, 错误信息如下
G:\TDDownload\Chloe-master\Chloe-master\src\Chloe\Chloe.csproj : error  : 无法识别元素 <PackageReference> 中的特性“Version”。  G:\TDDownload\Chloe-master\Chloe-master\src\Chloe\Chloe.csproj

G:\TDDownload\Chloe-master\Chloe-master\src\Chloe.SqlServer\Chloe.SqlServer.csproj : error  : 项目的默认 XML 命名空间必须为 MSBuild XML 命名空间。如果项目是用 MSBuild 2003 格式创建的，请将 xmlns="http://schemas.microsoft.com/developer/msbuild/2003" 添加到 <Project> 元素中。如果项目是用旧的 1.0 或 1.2 格式创建的，请将其转换为 MSBuild 2003 格式。  G:\TDDownload\Chloe-master\Chloe-master\src\Chloe.SqlServer\Chloe.SqlServer.csproj
这里只列了二条, 解决方案的其他项目错误信息类似, 就不列出来了.

根据度娘建议, 必须使用vs2017才行.
现在开发电脑上装的开发环境和软件太多, 跑不起vs2017, 请问楼主否提供vs2015的版本?拜谢, 不胜感激!

**Comment by shuxinqin** [comment]
不好弄- -建议装个2017吧
