### ISSUE TITLE
oracle 自增id,不指定sequence获取方式

### ISSUE THREAD

**Issue by try3** [shuxinqin/Chloe#86]
比如我为表user创建了一个sequence，然后再为这个表创建了一个触发器，有此触发器来为插入数据准备自增id
create or replace trigger TRG_SYSMGR_USER before insert on SYSMGR_USER for each row
begin
select SYSMGR_USER_SEQ.nextval into :new.ID from dual;
end;
 
在新增user的时候，实体上不指定sequence，数据库插入的记录可以正确获取到自增id，但是有个问题，就是获取不到新增记录的id值。

**是否可以在实体字段，IsAutoIncrement 的情况下，不指定sequence，加 RETURNING "ID" INTO :R_ID语句返回id值呢**

OracleContext.cs
`
if (propertyDescriptor.HasSequence())
 {
                    DbMethodCallExpression getNextValueForSequenceExp = PublicHelper.MakeNextValueForSequenceDbExpression(propertyDescriptor);
                    insertColumns.Add(propertyDescriptor, getNextValueForSequenceExp);
                    outputColumns.Add(propertyDescriptor);
                    continue;
}

//新增的

 if(propertyDescriptor.IsAutoIncrement)
 {
                    outputColumns.Add(propertyDescriptor);
                    continue;
  }

`

**Comment by shuxinqin** [comment]
v3.9.0已经支持AutoIncrement http://www.52chloe.com/Home/UpgradeNotes/3325175022200291328
