### ISSUE TITLE
About MySQL TableName

### ISSUE THREAD

**Issue by Mcgrady2009** [shuxinqin/Chloe#89]
when i set TableAttribute Name=iafc_ams.customer_account
the sql will be 

> _SELECT ``iafc_ams.customer_account`.`custom_num`` AS `cunum`……FROM ``iafc_ams.customer_account`` AS ``iafc_ams.customer_account``_

caused an error

**Comment by shuxinqin** [comment]
[TableAttribute("customer_account",  Schema="iafc_ams")]
