### ISSUE TITLE
Oracle In 1000

### ISSUE THREAD

**Issue by levenwan** [shuxinqin/Chloe#9]
没有考虑Oracle in 语句最多不能超多1000个.
 var str = qq1.Select(p => p.FID).ToArray(); //2000个字符串数组
var qq = Ctx.Query<T_MATERIAL>().Where (p=>str.Contains (p.FID ));
 这个有异常. 

另外是否可以考虑支持  客户端的表达式创建和序列化问题 ,如  JSON等.

**Comment by shuxinqin** [comment]
1.Oracle in 语句最多不能超多1000个，目前没打算在框架里做限制，即使做in个数限制处理，当超过1000个时也是以抛出异常方式。恐怕这个得在自个儿做限制了。
2.客户端的表达式创建和序列化？不是很明白你的意思，能描述更加详细点么？

**Comment by levenwan** [comment]
1.	Oracle In
我的意思是是否可以价格判断,当这种语句超过1000时, 自动扩展成多个表达式,并且用或链接.
如  where fid in(2000字符串列表)  
拆成  where  ( fid in (1000字符串列表) or fid in (1000字符串列表) )

2.	客户端以及web前端
就是想在客户端根据用户选择的条件可以动态生成条件表达式,并传输(序列化)到服务端执行.
这里有3点:  1. 动态表达式创建  2. 表达式支持序列化  3. 服务端可以解析表达式.
现在前端开发的需求很多. 可以在web前端动态创建的json格式的表达式,传到服务端解析.

3.	优化建议
能否创建Query的时候不要使用DbContext, 直接 new Query<T>就行了.
感觉Query表达式越中性越好.他表述的是实体与实体之间的逻辑关系.和具体数据源关系不大.
当需要生成sql或数据的时候在提供dbcontext.

另外将来是否可以支持查询 xml 和 json 等.还有 MogoDB
动态的表达式能否对内存数据进行过滤等. 基本上查询逻辑都是从客户端传来的. 如  List<T> 等.

以上建议仅作为参考. 谢谢

比Dapper 进了一步. 
支持…

**Comment by shuxinqin** [comment]
1.Oracle In：您提的这个处理方式很好（涨知识了，thx）。我查了下，对于oracle不同的版本的in个数限制有不同，得考虑下是不是有必要这样处理以及怎么处理不同版本之间in个数限制不同的好，感谢建议。
2.客户端以及web前端：这种需求看来不少，以后会考虑以扩展的方式支持
3.优化建议：有一定道理，不过不知道这么做的意义和必要性有多大。

xml 和 json 应该不会支持。MogoDB的驱动api貌似也挺好操作的了，最后要不要支持看情况吧。
非常感谢支持！

**Comment by levenwan** [comment]
另外追加2个
1. 在 join 的时候能否加个这样的重载.
 var qry = Ctx_UserMgr.Query<User>();
            qry.LeftJoin<UserInDepartments>((a, b) => a.SN == b.UserSN);
不要每次join的时候都要生成一个 dbcontext.query<T>.发现同一个语句的dbcontext应该都是一样的吧.

2. 发现join子表后不能直接where,非要select后才能使用where.
    一般习惯应该都是这样的吧.
     Query<T>.join<T>.where().select()
    而不是
    Query<T>.join<T>.select().where()

谢谢

**Comment by shuxinqin** [comment]
1.Query对象没调用一次都会生成一个新的Query对象，这和linq一致的设计思想。一个query对象就是一个“状态”，这个原则可以做很多事，比如多层的子查询，如果任何的筛选和其他操作（take，skip...）都在同一个query对象上，这是没法做到的。如,var newQuery = query.Take(20) 操作，query.Count()会生成满足条件的所有条数sql（select count(1) from users where xxx），newQuery.Count() 则会生成select count(1) from (select top 20 * from users where xxx) as T，很多稍微“复杂”点的用法都是基于这个原则实现。当然，带来的一个坏处就是多次赋值的问题，但总的来说利远大于弊。
2.这个习惯确实有悖于sql习惯，目前之所以这样设计主要受限于实现逻辑以及框架复杂度，之前考虑许久都没相到好办法解决。

**Comment by levenwan** [comment]
关于第一个, 我的意思是可以多加一个重载,在重载方法体里面新建Query<T>. 不需要使用者每次join子表时手动再写一行代码生成. 新建Query<T>时肯定的, 就是jion的时候可以更快速的写代码而已.

**Comment by shuxinqin** [comment]
抱歉，之前没细看，误解了你的意思，现在清楚了。你是想要这样快速连接是么：qry.LeftJoin((a, b) => a.SN == b.UserSN).LeftJoin((a,b,c) => b.Id==c.BId)...这样确实能省一次手动通过创建query对象（context.Query()）过程，这个重载后续会考虑加入，thx！

**Comment by levenwan** [comment]
是的.  谢谢
这样写起来快多了.尽量能够链式操作.
 qry.LeftJoin<T>((a, b) => a.SN == b.UserSN).LeftJoin<T>((a,b,c) => b.Id==c.BId)

**Comment by shuxinqin** [comment]
最新版本v2.5已经支持 query.LeftJoin((a, b) => a.SN == b.UserSN).LeftJoin((a,b,c) => b.Id==c.BId) 操作，感谢建议！！

**Comment by levenwan** [comment]
好的,谢谢

**Comment by shuxinqin** [comment]
Oracle In 1000，当这种语句超过1000时, 自动扩展成多个表达式用或链接 where ( fid in (1000字符串列表) or fid in (1000字符串列表) )
最新版本已经支持
https://github.com/shuxinqin/Chloe/commit/383b4a57566bc718c5cf3c7ac8fb7f42f4f1529a#diff-49b7407cb60cdfb4a7b0a88be2cb66cbR314
