### ISSUE TITLE
MapTo导致生成sql没有Distinct关键字

### ISSUE THREAD

**Issue by swpudp** [shuxinqin/Chloe#90]
var query = ctx.Query\<DrawHeader>().LeftJoin\<BusinessDocument>((d, b) => d.Number == b.Number);
//一些判断操作
return query.Select((d, b) => d).Distinct().MapTo\<DrawHeaderModel>().ToPagedResults(param);
使用Distinct().MapTo<DrawHeaderModel>()生成的sql没有Distinct关键字，去掉.MapTo<DrawHeaderModel>()生成的sql就有Distinct关键字了。
请确认下这是bug还是不支持这种写法？

**Comment by shuxinqin** [comment]
v3.9.0 已经修改。http://www.52chloe.com/Home/UpgradeNotes/3325175022200291328
