### ISSUE TITLE
是否有必要在IQuery接口上增加 “Or” 函数使用 “or” 连接多个查询条件，以对应 “Where”的“and”连接方式？

### ISSUE THREAD

**Issue by daoye** [shuxinqin/Chloe#91]
通常多个条件限定可以这样写：
`.Where(x=> x.Id == 1 && x.Sex == 1);`

或者：
`.Where(x=> x.Id == 1).Where(x=> x.Sex == 1)`

多数情况下第一种写法是比较方便的，不过第二种写法可以应对查询条件动态组合的场景。
例如：`x.Sex == 1`这个条件要根据逻辑来判断是否加上，那么可以这样写：

`
var query = .Where(x=> x.Id == 1);
if(some condition){
    query = query.Where(x=> x.Sex == 1);
}
`
不过比较遗憾的是，目前仅支持and的动态组合，不支持or或者两者混合的组合方式。

大家觉得是否有必要实现这种方式？

**Comment by ThisIsSteinsGate** [comment]
举双手赞成



------------------ 原始邮件 ------------------
发件人: "daoye"<notifications@github.com>; 
发送时间: 2019年4月30日(星期二) 上午10:36
收件人: "shuxinqin/Chloe"<Chloe@noreply.github.com>; 
抄送: "Subscribed"<subscribed@noreply.github.com>; 
主题: [shuxinqin/Chloe] 是否有必要在IQuery接口上增加 “Or” 函数使用 “or” 连接多个查询条件，以对应 “Where”的“and”连接方式？ (#91)




通常多个条件限定可以这样写：
 .Where(x=> x.Id == 1 && x.Sex == 1);
 
或者：
 .Where(x=> x.Id == 1).Where(x=> x.Sex == 1)
 
多数情况下第一种写法是比较方便的，不过第二种写法可以应对查询条件动态组合的场景。
 例如：x.Sex == 1这个条件要根据逻辑来判断是否加上，那么可以这样写：
 
var query = .Where(x=> x.Id == 1); if(some condition){ query = query.Where(x=> x.Sex == 1); }
 不过比较遗憾的是，目前仅支持and的动态组合，不支持其他or或者两者混合的组合方式。
 
大家觉得是否有必要实现这种方式？
 
&mdash;

**Comment by zanderzhg** [comment]
不是有whereif吗?

**Comment by shuxinqin** [comment]
网上有很多lambda把、拼接的库。先拼接好lambda，然后传进Where参数就可以了。

**Comment by daoye** [comment]
目前我通过动态构建表达式的方式来处理的，这样是能够达到目的，不过不算是很方便的做法。


            var parameterExpression = Expression.Parameter(typeof(T), "x");
            Expression nameExpress = null;

            foreach (var t in response.Current.Tags)
            {
                var constant = Expression.Constant(t.Name);
                var property = Expression.Property(parameterExpression, "The object's property name");
                var method = typeof(string).GetMethod("Contains", new[] { typeof(string) });

                Expression expression = Expression.Call(property, method, constant);

                if (null == nameExpress)
                {
                    nameExpress = expression;
                }
                else
                {
                    nameExpress = Expression.Or(nameExpress, expression);
                }
            }

            var exp = Expression.Lambda<Func<T, bool>>(nameExpress, parameterExpression);

            _context.Query<T>()
                    .Where(exp);

**Comment by scymen** [comment]
先拼接好查询条件的 Lambda 表达式，再传入确实是个解决办法。
网上找了个拼接的实现，但是没效果，不知道哪里的问题。
能否帮小白看看？

`
    public static class PredicateBuilder
    {
        public static Expression<Func<T, bool>> True<T>() { return f => true; }
        public static Expression<Func<T, bool>> False<T>() { return f => false; }

        public static Expression<Func<T, bool>> Or<T>(this Expression<Func<T, bool>> expr1, Expression<Func<T, bool>> expr2)
        {
            var invokedExpr = Expression.Invoke(expr2, expr1.Parameters.Cast<Expression>());

            return Expression.Lambda<Func<T, bool>>
                  (Expression.OrElse(expr1.Body, invokedExpr), expr1.Parameters);
        }

        public static Expression<Func<T, bool>> And<T>(this Expression<Func<T, bool>> expr1, Expression<Func<T, bool>> expr2)
        {
            var invokedExpr = Expression.Invoke(expr2, expr1.Parameters.Cast<Expression>());

            return Expression.Lambda<Func<T, bool>>
                (Expression.AndAlso(expr1.Body, invokedExpr), expr1.Parameters);
        }

        public static Expression<Func<T, bool>> AndAlso<T>(this Expression<Func<T, bool>> expr1, Expression<Func<T, bool>> expr2)
        {
            var parameter = Expression.Parameter(typeof(T));

            var leftVisitor = new ReplaceExpressionVisitor(expr1.Parameters[0], parameter);
            var left = leftVisitor.Visit(expr1.Body);

            var rightVisitor = new ReplaceExpressionVisitor(expr2.Parameters[0], parameter);
            var right = rightVisitor.Visit(expr2.Body);

            return Expression.Lambda<Func<T, bool>>(Expression.AndAlso(left, right), parameter);
        }


        private class ReplaceExpressionVisitor : ExpressionVisitor
        {
            private readonly Expression _oldValue;
            private readonly Expression _newValue;

            public ReplaceExpressionVisitor(Expression oldValue, Expression newValue)
            {
                _oldValue = oldValue;
                _newValue = newValue;
            }

            public override Expression Visit(Expression node)
            {
                if (node == _oldValue)
                    return _newValue;
                return base.Visit(node);
            }
        }
`

使用

`     var predicate = PredicateBuilder.True<Sys_User>();
            predicate.And(x => x.UserName.Contains("admi"));

dbContext.Query<Sys_User>().Where(predicate).ToList();

`

会查出所有的记录，生成的SQL 没有 where 里指定的条件。

了解的朋友希望帮忙看看，非常感谢。

另外：

根据需要，生成查询条件，我想这个需求应该是很多人的需求，不知道大家是如何实现的？

作者的QQ群已满员，
大家遇到的问题，讨论的问题，能否多发 ISSUE？

这样下一个遇到同样问题的人，就可以直接查阅，寻求解决办法，节省大量时间。

**Comment by shuxinqin** [comment]
predicate = predicate.And(x => x.UserName.Contains("admi"));

**Comment by scymen** [comment]
！ ~！OMG... 

谢谢指明低级错误

` public static class PredicateBuilder2
    {
        public static Expression<Func<T, bool>> True<T>() { return f => true; }
        public static Expression<Func<T, bool>> False<T>() { return f => false; }
        public static Expression<T> Compose<T>(this Expression<T> first, Expression<T> second, Func<Expression, Expression, Expression> merge)
        {
            // build parameter map (from parameters of second to parameters of first)
            var map = first.Parameters.Select((f, i) => new { f, s = second.Parameters[i] }).ToDictionary(p => p.s, p => p.f);

            // replace parameters in the second lambda expression with parameters from the first
            var secondBody = ParameterRebinder.ReplaceParameters(map, second.Body);

            // apply composition of lambda expression bodies to parameters from the first expression 
            return Expression.Lambda<T>(merge(first.Body, secondBody), first.Parameters);
        }

        public static Expression<Func<T, bool>> And<T>(this Expression<Func<T, bool>> first, Expression<Func<T, bool>> second)
        {
            return first.Compose(second, Expression.And);
        }

        public static Expression<Func<T, bool>> Or<T>(this Expression<Func<T, bool>> first, Expression<Func<T, bool>> second)
        {
            return first.Compose(second, Expression.Or);
        }

    }


    public class ParameterRebinder : ExpressionVisitor
    {
        private readonly Dictionary<ParameterExpression, ParameterExpression> map;

        public ParameterRebinder(Dictionary<ParameterExpression, ParameterExpression> map)
        {
            this.map = map ?? new Dictionary<ParameterExpression, ParameterExpression>();
        }

        public static Expression ReplaceParameters(Dictionary<ParameterExpression, ParameterExpression> map, Expression exp)
        {
            return new ParameterRebinder(map).Visit(exp);
        }

        protected override Expression VisitParameter(ParameterExpression p)
        {
            ParameterExpression replacement;
            if (map.TryGetValue(p, out replacement))
            {
                p = replacement;
            }
            return base.VisitParameter(p);
        }

    }`
