### ISSUE TITLE
LeftJoin关联查询为NULL异常如何处理？

### ISSUE THREAD

**Issue by codesee** [shuxinqin/Chloe#94]
我目前遇到这样的问题：存在A表 和 B表，B表的(int、datetime类型)字段不可空，但当A表 LeftJoin B表时，由于B表数据与A表数据不完全对应，导致联结查询B表为NULL的情况，当 Select 查询返回结果时，由于实体(int、datetime类型)属性不可空，导致查询异常，请问，该问题如何处理？

**Comment by shuxinqin** [comment]
1. 设置属性可空
2. Select(a=> { A = a.Age??0 })

**Comment by codesee** [comment]
好的，非常感谢。
另外，对于第2点Select(a=> { A = a.Age??0 })，能否在ORM内部实现？也就是说如果左联查询为NULL的字段（属性）自动设置默认值，即如你回复的，如果int类型的Age为null，则给默认值0，datetime类型则给默认值DateTime.MinValue？

**Comment by shuxinqin** [comment]
这类的默认值暂时不打算考虑支持哦。

**Comment by codesee** [comment]
好的，非常感谢
