### ISSUE TITLE
Chloe.DbContext何时释放连接资源

### ISSUE THREAD

**Issue by zuowj** [shuxinqin/Chloe#95]
Chloe.DbContext何时释放连接资源？正如问题：https://github.com/shuxinqin/Chloe/issues/47 这里面所说，非IOC注入的DbContext实例必需使用using或显式调用dispose方法，而IOC注入的DbContext实例是怎么管理连接资源的？何时释放连接？不会是等着DbContext被GC回收后，才能释放资源吧？如果是这样，可能还是会存在性能问题，存在连接资源不足的情况。建议内部应该有连接资源管理机制，不能被动的等着DbContext回收时去调用dispose方法再来释放连接。

**Comment by zuowj** [comment]
也可以看看我基于Dapper二次封装了一个易用的ORM工具类：SqlDapperUtil：https://www.cnblogs.com/zuowj/p/9570956.html  ,在这个里面我就解决了释放的问题，默认如果没有使用事务，则用完即释放，若使用事务则不释放，需要显式dispose，当然如果程序员忘记dispose，在SqlDapperUtil类被GC回收时也会通过析构函数执行关闭连接、回滚事务操作，确保资源及时释放掉，当然这不一定是最好方案，也可以参考EF的内部实现方式。

**Comment by shuxinqin** [comment]
IOC管理的对象都有生命周期，在asp.net中用IOC注入一般请求结束后就会释放。
