### ISSUE TITLE
Query单表查询数据时报错

### ISSUE THREAD

**Issue by CodeSirLi** [shuxinqin/Chloe#98]
C# .net Core 
数据库字段time(7)映射字段TimeSpan
根据此字段查询时报错：
An exception occurred while executing DbCommand. For details please see the inner exception. Failed to convert parameter value from a TimeSpan to a DateTime.”

求解！
QQ:284158913
期望作者帮助下，你的忠实粉丝。

**Comment by CodeSirLi** [comment]
开发环境
VS2017  
.net core 2.2
mssql 2017

**Comment by shuxinqin** [comment]
目前不支持time(7)哦

**Comment by CodeSirLi** [comment]
好的 
大佬能再开一个QQ群吗？官网的QQ群满了，一直加不进去！
