### ISSUE TITLE
多个操作数据库命令同时执行，报以下错误

### ISSUE THREAD

**Issue by xingfengshi** [shuxinqin/Chloe#99]
使用c#调用mysql，一个线程不断的插入数据到表中，另一个线程执行查询的命令时，会抛异常
InnerException = {"There is already an open DataReader associated with this Connection which must be closed first."}，请问这个问题如何解决？

**Comment by shuxinqin** [comment]
DbContext是非线程安全对象。多个线程同时操作一个DbContext会有问题。

**Comment by xingfengshi** [comment]
那面对这种业务场景，该如何处理？场景就是有一个线程不断的插入数据，另外可能会有一些业务操作从该表中查数据

**Comment by shuxinqin** [comment]
那就避免多个线程同时操作一个DbContext啊。
